#!/usr/bin/python3
"""PORT M1.B S1 — GENERATED report (m1/generation_v2/GEN_V2_REPORT.md).

Every number is read back out of a committed TSV and carries its `file:line`
(D-010).  Nothing here is hand-typed.

Run: /usr/bin/python3 engine/port_m1/report_v2.py
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import m1_common as M
import b8_generation_v2 as G
from report import Tsv, num, cite, md_table

OUT = M.out_path(G.OUT_DIR, "GEN_V2_REPORT.md")

HEADER = (
    "Generated by `engine/port_m1/report_v2.py`. Specs: "
    "`design/PORT_M1B_SPEC.md` sha16 `%s` (S1) and `design/PORT_M1_SPEC.md` "
    "sha16 `%s` (CC-M1-3, the binding rulings). Prototype: "
    "`engine/port_m1/b8_generation_v2.py` — THE FROZEN DIFFERENTIAL ORACLE for "
    "the C++ generation lane (S2). Every number carries its source `file:line`."
    % (M.SPEC_M1B_SHA16, M.SPEC_SHA16))


def _seat_rollup(seat, a, yrs):
    rs = [(r, ln) for r, ln in zip(seat.rows, seat.lines)
          if r[seat.i("asset")] == a
          and (yrs is None or int(r[seat.i("year")]) in yrs)]
    return rs


def main():
    fam = Tsv(M.out_path(G.OUT_DIR, "census_family_value.tsv"))
    exc = Tsv(M.out_path(G.OUT_DIR, "census_family_exclusive.tsv"))
    rec = Tsv(M.out_path(G.OUT_DIR, "census_union_recall.tsv"))
    seat = Tsv(M.out_path(G.OUT_DIR, "census_union_seatable.tsv"))
    bld = Tsv(M.out_path(G.OUT_DIR, "roster_build.tsv"))
    mrg = Tsv(M.out_path(G.OUT_DIR, "family_marginals.tsv"))
    old = Tsv(M.out_path("generation", "census_union_recall.tsv"))
    vwd = Tsv(M.out_path("levels_v2", "vwap_d053_differential.tsv"))

    L = ["# PORT M1.B S1 — GENERATION v2 (CC-M1-3) + RE-CENSUS", "", HEADER, ""]
    if not rec:
        L.append("_re-census not yet complete_")
        open(OUT, "w").write("\n".join(L) + "\n")
        return 1

    # ------------------------------------------------------------ verdict ---
    L.append("## Gate P-M1f — catchable recall >= 99%/asset @$1,000\n")
    rows = []
    verdict = {}
    for a in M.ASSET_ORDER:
        for era in (M.ERA_FIT, M.ERA_GATE, M.ERA_ALL):
            r, ln = rec.one(asset=a, dropped_exclusive_family="NONE", era=era)
            if r is None:
                continue
            if era == M.ERA_ALL:
                verdict[a] = r[rec.i("gate_catchable_ge_99")]
            rows.append([a, era, num(r, rec, "n_legs", "%.0f"),
                         num(r, rec, "n_catchable", "%.0f"),
                         num(r, rec, "n_structural_gap", "%.0f"),
                         num(r, rec, "recall_catchable_1000", "%.4f"),
                         num(r, rec, "recall_raw_1000", "%.4f"),
                         num(r, rec, "n_structural_captured_1000", "%.0f"),
                         num(r, rec, "gate_catchable_ge_99") or "-",
                         cite(rec, ln)])
    L.append(md_table(["asset", "era", "legs", "catchable", "structural gap",
                       "CATCHABLE recall @$1k", "RAW recall @$1k",
                       "structural legs captured anyway", "gate", "source"],
                      rows))
    L.append("\nGate verdict (era ALL): "
             + ", ".join("%s %s" % (a, verdict.get(a, "n/a"))
                         for a in M.ASSET_ORDER)
             + ". CC-M1-3.4a: a leg whose FULL SPAN is < %ds is a "
               "STRUCTURAL_GAP (price travels the whole leg inside the "
               "confirm-plus-delay window, so no design of this shape can "
               "enter it); the gate applies to CATCHABLE legs and BOTH "
               "numbers are reported.\n" % G.STRUCTURAL_SPAN)

    # ------------------------------------------------- M1.A comparison ------
    L.append("## Against the M1.A census (same oracle legs, old roster)\n")
    rows = []
    for a in M.ASSET_ORDER:
        o, oln = old.one(asset=a, dropped_exclusive_family="NONE",
                         era=M.ERA_ALL)
        n, nln = rec.one(asset=a, dropped_exclusive_family="NONE",
                         era=M.ERA_ALL)
        rows.append([a, num(o, old, "recall_1000", "%.4f"),
                     num(n, rec, "recall_raw_1000", "%.4f"),
                     num(n, rec, "recall_catchable_1000", "%.4f"),
                     cite(old, oln), cite(rec, nln)])
    L.append(md_table(["asset", "M1.A union recall @$1k (all legs)",
                       "v2 RAW recall @$1k", "v2 CATCHABLE recall @$1k",
                       "M1.A source", "v2 source"], rows))

    # ------------------------------------------------------- sensitivity ----
    L.append("\n## $900 / $1,100 sensitivity (era ALL)\n")
    rows = []
    for a in M.ASSET_ORDER:
        r, ln = rec.one(asset=a, dropped_exclusive_family="NONE",
                        era=M.ERA_ALL)
        rows.append([a, num(r, rec, "recall_catchable_900", "%.4f"),
                     num(r, rec, "recall_catchable_1000", "%.4f"),
                     num(r, rec, "recall_catchable_1100", "%.4f"),
                     num(r, rec, "recall_catchable_1000_screened", "%.4f"),
                     num(r, rec, "recall_raw_900", "%.4f"),
                     num(r, rec, "recall_raw_1100", "%.4f"), cite(rec, ln)])
    L.append(md_table(["asset", "catchable @$900", "catchable @$1,000",
                       "catchable @$1,100", "catchable @$1k tradeable-spread "
                       "screened", "raw @$900", "raw @$1,100", "source"], rows))

    # ---------------------------------------------------------- roster ------
    L.append("\n## Union roster and per-family walled certificates\n")
    rows = []
    for a in M.ASSET_ORDER:
        for f in list(G.FAMILIES) + ["UNION"]:
            r, ln = fam.one(asset=a, family=f)
            if r is None:
                continue
            rows.append([a, f, num(r, fam, "n_candidates", "%.0f"),
                         num(r, fam, "positive_frac", "%.3f"),
                         num(r, fam, "mean_cert_usd", "$%.2f"),
                         num(r, fam, "median_cert_usd", "$%.2f"),
                         num(r, fam, "mean_positive_cert_usd", "$%.0f"),
                         cite(fam, ln)])
    L.append(md_table(["asset", "family", "candidates", "positive share",
                       "mean cert", "median cert",
                       "CONDITIONAL value (mean positive cert)", "source"],
                      rows))
    L.append("\nRetired and NOT generated: G3-RATE, G3-FLOW (CC-M1-3.2). "
             "Retired as level sources, so their touches no longer make G2 "
             "candidates: %s (CC-M1-3.3); KEPT six: %s.\n"
             % (", ".join(G.RETIRED_LEVEL_FAMILIES),
                ", ".join(G.KEPT_LEVEL_FAMILIES)))

    # -------------------------------------------------------- marginals -----
    L.append("## Marginal contribution of each family (era ALL)\n")
    rows = []
    for a in M.ASSET_ORDER:
        for f in G.FAMILIES:
            r, ln = mrg.one(asset=a, family=f, era=M.ERA_ALL)
            if r is None:
                continue
            rows.append([a, f + (" (NEW)" if f in G.NEW_FAMILIES else ""),
                         num(r, mrg, "n_candidates", "%.0f"),
                         num(r, mrg, "n_exclusive_total", "%.0f"),
                         num(r, mrg, "conditional_value_usd", "$%.0f"),
                         num(r, mrg, "marginal_recall_catchable_pp", "%+.3f"),
                         num(r, mrg, "marginal_recall_raw_pp", "%+.3f"),
                         num(r, mrg, "exclusive_dp_add_median_usd", "$%.0f"),
                         num(r, mrg, "exclusive_dp_add_mean_usd", "$%.0f"),
                         cite(mrg, ln)])
    L.append(md_table(["asset", "family", "candidates", "exclusive candidates",
                       "conditional value", "marginal CATCHABLE recall (pp)",
                       "marginal RAW recall (pp)", "exclusive DP add median/day",
                       "exclusive DP add mean/day", "source"], rows))
    L.append("\nMarginal = union minus the roster with that family's "
             "EXCLUSIVE candidates removed. The DP add is saturated by "
             "construction (CC-M1-3.2 already replaced it as a retirement "
             "metric: ~600 candidates compete for ~3 seats), so it is "
             "reported, not gated.\n")

    # ------------------------------------------------------- fast-open ------
    L.append("## G1-FAST-OPEN and G1-FINE build statistics\n")
    rows = []
    for a in M.ASSET_ORDER:
        rs = [(r, ln) for r, ln in zip(bld.rows, bld.lines)
              if r[bld.i("asset")] == a]
        if not rs:
            continue
        tot = lambda c: sum(float(r[bld.i(c)]) for r, _ in rs)   # noqa: E731
        rows.append([a, len(rs), "%.0f" % tot("n_g1_confirmations"),
                     "%.0f" % tot("n_union_candidates"),
                     "%.0f" % tot("n_fast_open_candidates"),
                     "%.0f" % tot("n_g2_events"),
                     "%.0f" % tot("n_g2_dropped_retired_level"),
                     "%.0f" % tot("n_g2_dropped_reclaim_bound"),
                     "%.0f" % tot("n_coarse_conf_only_v2"),
                     "%.0f" % tot("n_coarse_conf_only_m1a"),
                     cite(bld, rs[0][1])])
    L.append(md_table(["asset", "sessions", "confirmations (4-rung ladder)",
                       "union candidates", "FAST-OPEN candidates",
                       "G2 events kept", "G2 dropped: retired level source",
                       "G2-RECLAIM dropped: 30-min bound",
                       "ladder drift (v2 only)", "ladder drift (M1.A only)",
                       "source"], rows))
    L.append("\nLADDER DIFFERENTIAL: both drift columns are 0 by assertion in "
             "`engine/port_m1/b8_generation_v2.py` (the run aborts otherwise) "
             "— adding the FINE rung leaves the m0 3-rung confirmation set "
             "untouched, confirmation for confirmation.\n")

    # ------------------------------------------------------- occupancy ------
    L.append("## Occupancy DP re-run (for the record)\n")
    rows = []
    for a in M.ASSET_ORDER:
        for era, yrs in ((M.ERA_FIT, M.FIT_YEARS), (M.ERA_GATE, (2025,)),
                         (M.ERA_ALL, None)):
            rs = _seat_rollup(seat, a, yrs)
            if not rs:
                continue
            dp = [float(r[seat.i("union_dp_close_usd")]) for r, _ in rs]
            nc = [float(r[seat.i("n_union")]) for r, _ in rs]
            ns = [float(r[seat.i("n_seated_union")]) for r, _ in rs]
            rows.append([a, era, len(rs), "$%.0f" % M.med(dp),
                         "$%.0f" % M.mean(dp), "%.0f" % M.med(nc),
                         "%.0f" % M.med(ns), cite(seat, rs[0][1])])
    L.append(md_table(["asset", "era", "sessions", "union DP median/day",
                       "union DP mean/day", "candidates/day", "seated/day",
                       "source"], rows))
    L.append("\nORACLE CERTIFICATE CEILINGS on the M0 convention (walled "
             "phase-close, one position), never forecasts.\n")

    # -------------------------------------------------------- D-053 ---------
    L.append("## D-053 (VWAP bands) acknowledgement\n")
    n_ok = sum(1 for r in vwd.rows if r[vwd.i("verdict")] == "PASS")
    L.append("The VWAP level family was rebuilt as the VWAP LINE plus "
             "+-2.0/+-2.5 x sigma_vwap (session and phase), replacing "
             "+-1/+-2. The ledger was regenerated into `m1/levels_v2/` by "
             "re-running the frozen §4 builder with the new bands "
             "(`engine/port_m1/b7_levels_v2.py`); this census reads that "
             "ledger, so every recall / value / DP number above is on the "
             "D-053 configuration. Rebuild differential: %d/%d sampled "
             "sessions PASS — every non-VWAP ledger row identical to the M1.A "
             "ledger, every VWAP row a D-053 band (%s).\n"
             % (n_ok, len(vwd.rows), cite(vwd, vwd.lines[0] if vwd.lines
                                          else 0)))

    # -------------------------------------------------------- readings ------
    L.append("""## Pinned readings and spec ambiguities (for adjudication)

1. **G1-FAST-OPEN is ADDITIVE.** CC-M1-3.4b gives it a *separate family tag*,
   so the 15s candidate is emitted BESIDE the tau*=120s candidate of the same
   confirmation, not instead of it. PORT_M1B_SPEC §1 S2's shorthand
   "tau*=120s (15s in open windows)" would also admit a REPLACEMENT reading.
   The additive reading is the superset (it can only help a recall gate) and it
   is the only one under which the family's marginal contribution is
   measurable, so it is what this oracle emits. The C++ lane must match it
   candidate-exact; if the orchestrator intends replacement, that is a
   one-line change here and a re-census.
2. **The 15s delay applies to G1 rungs only.** CC-M1-3.4b says "decision delay
   15s on all rungs"; rungs are a G1 object, so G2 candidates keep tau* even
   inside an open window.
3. **The 30-min RECLAIM bound is enforced at generation**, on the ledger's
   first-reclaim record. That is exactly equivalent to bounding the ledger's
   own search (the §4 state machine returns the EARLIEST reclaim confirmation,
   so an out-of-bounds first reclaim implies no in-bounds one) and it is the
   hook b3_levels deliberately left: "§6 states no bound; the elapsed time is
   recorded so M1.B can pin one".
4. **Phase opens** = session second 0 plus every phase-tag change of the frozen
   3-phase table (CC-M1-3.6 folds the §4(c) overnight segment away). The window
   is half-open [open, open+300): a confirmation exactly 300s after the open is
   outside it. Red-first covered (`engine/port_m1/test_m1b.py`).
5. **STRUCTURAL_GAP is a leg property, not a miss excuse**: the split is
   computed from the oracle leg's own full span, before any roster is
   consulted, so it cannot be tuned by the roster.
""")
    with open(OUT, "w") as fh:
        fh.write("\n".join(L) + "\n")
    print(OUT)
    return 0


if __name__ == "__main__":
    sys.exit(main())
