#!/usr/bin/python3
"""PORT M1.B S1 — GENERATED report (m1/generation_v2/GEN_V2_REPORT.md).

Every number is read back out of a committed TSV and carries its `file:line`
(D-010).  Nothing here is hand-typed.

Run: /usr/bin/python3 engine/port_m1/report_v2.py
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import m1_common as M
import b7_sane as B7
import b8_generation_v2 as G
from report import Tsv, num, cite, md_table

OUT = M.out_path("generation_v2", "GEN_V2_REPORT.md")
NOMASK = "generation_v2_nomask"

HEADER = (
    "Generated by `engine/port_m1/report_v2.py`. Specs: "
    "`design/PORT_M1B_SPEC.md` sha16 `%s` (S1) and `design/PORT_M1_SPEC.md` "
    "sha16 `%s` (CC-M1-3 + CC-M1-4, the binding rulings). Prototype: "
    "`engine/port_m1/b8_generation_v2.py` — THE FROZEN DIFFERENTIAL ORACLE for "
    "the C++ generation lane (S2). Every number carries its source `file:line`."
    % (M.SPEC_M1B_SHA16, M.SPEC_SHA16))


def _rollup(t, a, yrs, col, stat="med"):
    rs = [(r, ln) for r, ln in zip(t.rows, t.lines)
          if r[t.i("asset")] == a and (yrs is None
                                       or int(r[t.i("year")]) in yrs)]
    if not rs:
        return float("nan"), None, 0
    v = [float(r[t.i(col)]) for r, _ in rs if r[t.i(col)] != ""]
    f = M.med(v) if stat == "med" else M.mean(v)
    return f, rs[0][1], len(rs)


def main():
    fam = Tsv(M.out_path("generation_v2", "census_family_value.tsv"))
    exc = Tsv(M.out_path("generation_v2", "census_family_exclusive.tsv"))
    rec = Tsv(M.out_path("generation_v2", "census_union_recall.tsv"))
    seat = Tsv(M.out_path("generation_v2", "census_union_seatable.tsv"))
    bld = Tsv(M.out_path("generation_v2", "roster_build.tsv"))
    mrg = Tsv(M.out_path("generation_v2", "family_marginals.tsv"))
    imp = Tsv(M.out_path("generation_v2", "mask_impact.tsv"))
    old = Tsv(M.out_path("generation", "census_union_recall.tsv"))
    nom = Tsv(M.out_path(NOMASK, "census_union_recall.tsv"))
    vwd = Tsv(M.out_path("levels_v2", "vwap_d053_differential.tsv"))
    tdl = Tsv(M.out_path("levels_v3", "sane_touch_delta.tsv"))
    san = Tsv(M.out_path("sane", "sane_thresholds.tsv"))

    L = ["# PORT M1.B S1 — GENERATION v2 (CC-M1-3) UNDER THE D-054 MID-SANITY "
         "MASK (CC-M1-4)", "", HEADER, ""]
    if not rec:
        L.append("_re-census not yet complete_")
        open(OUT, "w").write("\n".join(L) + "\n")
        return 1

    # ------------------------------------------------------------ verdict ---
    L.append("## Gate P-M1f — recall >= 99%/asset @$1,000 on the SANE oracle\n")
    rows, verdict = [], {}
    for a in M.ASSET_ORDER:
        for era in (M.ERA_FIT, M.ERA_GATE, M.ERA_ALL):
            r, ln = rec.one(asset=a, dropped_exclusive_family="NONE", era=era)
            if r is None:
                continue
            if era == M.ERA_ALL:
                verdict[a] = r[rec.i("gate_ge_99")]
            rows.append([a, era, num(r, rec, "n_legs", "%.0f"),
                         num(r, rec, "n_gate_legs", "%.0f"),
                         num(r, rec, "n_news_untradeable", "%.0f"),
                         num(r, rec, "recall_gate_1000", "%.4f"),
                         num(r, rec, "recall_all_1000", "%.4f"),
                         num(r, rec, "n_news_captured_1000", "%.0f"),
                         r[rec.i("gate_ge_99")] or "-", cite(rec, ln)])
    L.append(md_table(["asset", "era", "oracle legs", "gate legs",
                       "NEWS_UNTRADEABLE", "GATE recall @$1k",
                       "ALL-legs recall @$1k", "news legs captured anyway",
                       "gate", "source"], rows))
    L.append("\n**Gate verdict (era ALL): "
             + ", ".join("%s %s" % (a, verdict.get(a, "n/a"))
                         for a in M.ASSET_ORDER)
             + "**. CC-M1-4.3: the STRUCTURAL_GAP class is retired — those legs "
               "were wide-book artifacts and the mask deletes them at source. "
               "A post-mask leg completing in under %ds is NEWS_UNTRADEABLE and "
               "sits beside the gate, never inside it.\n" % G.NEWS_SPAN)

    # ----------------------------------------------- D-054 mask + impact ----
    L.append("## D-054 / CC-M1-4 — the mid-sanity mask\n")
    L.append("Rule: a second is SANE iff TWO_SIDED **and** spread_$ <= "
             "min(%.0f x trailing-phase-median spread_$, $%.0f). Insane seconds "
             "are typed-excluded (never interpolated) from the oracle legs, the "
             "offer census, the ZigZag spine, entry mids, certificate forward "
             "paths and level touches — `engine/port_m1/b7_sane.py` owns the "
             "mask and rewrites each session's observed-second view, so every "
             "downstream routine sees sane seconds only.\n"
             % (B7.SANE_MULT, B7.SANE_CAP_USD))
    rows = []
    for a in M.ASSET_ORDER:
        for ph in ("TOKYO", "LONDON", "NY"):
            rs = [(r, ln) for r, ln in zip(san.rows, san.lines)
                  if r[san.i("asset")] == a and r[san.i("phase")] == ph]
            if not rs:
                continue
            ins = [float(r[san.i("insane_frac")]) for r, _ in rs
                   if r[san.i("insane_frac")] != ""]
            thr = [float(r[san.i("threshold_usd")]) for r, _ in rs]
            rows.append([a, ph, len(rs), "%.4f" % M.mean(ins),
                         "%.4f" % M.med(ins), "$%.0f" % M.med(thr),
                         cite(san, rs[0][1])])
    L.append(md_table(["asset", "phase", "sessions", "insane_frac mean",
                       "insane_frac median", "threshold median", "source"],
                      rows))
    L.append("\nWorked verification of the user's case (NKD 2022-09-08, the "
             "session that produced a phantom $5,110 leg in 9 seconds): "
             "seconds 0-9 carry a 3,220-point book (spread $16,100) and the mid "
             "jumps 27,260 -> 28,282.5 when a bid arrives. Under the mask the "
             "first sane second is 20 and the first-60s mid range is "
             "27,732.5 - 27,735.0 ($12.50). The leg was the spread collapsing, "
             "not price travelling.\n")

    if imp:
        L.append("### Before/after impact (CC-M1-4.4, mandatory)\n")
        L.append("Both arms are the same pipeline on the same sessions with "
                 "the same families and the same D-053 levels; the only "
                 "difference is the mask, so every delta is attributable to "
                 "it. BEFORE = `m1/%s/`, AFTER = `m1/generation_v2/`.\n"
                 % NOMASK)
        rows = []
        for a in M.ASSET_ORDER:
            for metric in ("offer_best_leg_median_FULL",
                           "offer_range_median_FULL", "dp_seatable_median",
                           "wall_mae_p95", "wall_mae_p99", "recall_all_1000",
                           "recall_gate_1000", "n_oracle_legs",
                           "candidates_per_session_median",
                           "insane_frac_mean"):
                r, ln = imp.one(asset=a, era=M.ERA_ALL, metric=metric)
                if r is None:
                    continue
                rows.append([a, metric, num(r, imp, "before_mask", "%.4f"),
                             num(r, imp, "after_mask", "%.4f"),
                             num(r, imp, "pct_change", "%+.2f%%"),
                             r[imp.i("flag")], cite(imp, ln)])
        L.append(md_table(["asset", "metric (era ALL)", "before mask",
                           "after mask", "change", "flag", "source"], rows))
        flags = [r for r in imp.rows if r[imp.i("flag")]]
        if flags:
            L.append("\n**ORCHESTRATOR ADDENDUM REQUIRED** — %d "
                     "verdict-relevant medians move more than %.0f%%:\n"
                     % (len(flags), 5.0))
            L.append(md_table(["asset", "era", "metric", "before", "after",
                               "change"],
                              [[r[imp.i("asset")], r[imp.i("era")],
                                r[imp.i("metric")],
                                "%.2f" % float(r[imp.i("before_mask")]),
                                "%.2f" % float(r[imp.i("after_mask")]),
                                "%+.1f%%" % float(r[imp.i("pct_change")])]
                               for r in flags]))
            L.append("\nSource: `%s`.\n" % imp.rel())
        else:
            L.append("\nNo verdict-relevant median moves more than 5% — no "
                     "M0 verdict addendum is triggered by the mask.\n")
    if tdl:
        d = [float(r[tdl.i("touch_delta_pct")]) for r in tdl.rows
             if r[tdl.i("touch_delta_pct")] != ""]
        L.append("\nLevel ledger under the mask (`m1/levels_v3/`): sampled "
                 "touch count changes by %+.2f%% on average vs the unmasked "
                 "`m1/levels_v2/` (%s).\n"
                 % (M.mean(d), cite(tdl, tdl.lines[0] if tdl.lines else 0)))

    # ------------------------------------------------- M1.A comparison ------
    L.append("## Recall across the three configurations\n")
    rows = []
    for a in M.ASSET_ORDER:
        o, oln = old.one(asset=a, dropped_exclusive_family="NONE",
                         era=M.ERA_ALL)
        nm, nmln = (nom.one(asset=a, dropped_exclusive_family="NONE",
                            era=M.ERA_ALL) if nom else (None, None))
        n, nln = rec.one(asset=a, dropped_exclusive_family="NONE",
                         era=M.ERA_ALL)
        rows.append([a, num(o, old, "recall_1000", "%.4f"),
                     num(nm, nom, "recall_all_1000", "%.4f") if nm else "n/a",
                     num(n, rec, "recall_all_1000", "%.4f"),
                     num(n, rec, "recall_gate_1000", "%.4f"),
                     cite(old, oln), cite(rec, nln)])
    L.append(md_table(["asset", "M1.A families, unmasked",
                       "v2 families, unmasked", "v2 families, MASKED (all "
                       "legs)", "v2 families, MASKED (gate legs)",
                       "M1.A source", "v2 source"], rows))

    # ------------------------------------------------------- sensitivity ----
    L.append("\n## $900 / $1,100 sensitivity (era ALL, masked arm)\n")
    rows = []
    for a in M.ASSET_ORDER:
        r, ln = rec.one(asset=a, dropped_exclusive_family="NONE",
                        era=M.ERA_ALL)
        rows.append([a, num(r, rec, "recall_gate_900", "%.4f"),
                     num(r, rec, "recall_gate_1000", "%.4f"),
                     num(r, rec, "recall_gate_1100", "%.4f"),
                     num(r, rec, "recall_gate_1000_screened", "%.4f"),
                     num(r, rec, "recall_all_900", "%.4f"),
                     num(r, rec, "recall_all_1100", "%.4f"), cite(rec, ln)])
    L.append(md_table(["asset", "gate @$900", "gate @$1,000", "gate @$1,100",
                       "gate @$1k, tradeable-spread screened", "all legs @$900",
                       "all legs @$1,100", "source"], rows))

    # ---------------------------------------------------------- roster ------
    L.append("\n## Union roster and per-family walled certificates\n")
    rows = []
    for a in M.ASSET_ORDER:
        for f in list(G.FAMILIES) + ["UNION"]:
            r, ln = fam.one(asset=a, family=f)
            if r is None:
                continue
            rows.append([a, f, num(r, fam, "n_candidates", "%.0f"),
                         num(r, fam, "positive_frac", "%.3f"),
                         num(r, fam, "mean_cert_usd", "$%.2f"),
                         num(r, fam, "median_cert_usd", "$%.2f"),
                         num(r, fam, "mean_positive_cert_usd", "$%.0f"),
                         cite(fam, ln)])
    L.append(md_table(["asset", "family", "candidates", "positive share",
                       "mean cert", "median cert",
                       "CONDITIONAL value (mean positive cert)", "source"],
                      rows))
    L.append("\nNot generated at all: G3-RATE, G3-FLOW (CC-M1-3.2). Retired as "
             "level sources, so their touches no longer make G2 candidates: %s "
             "(CC-M1-3.3); KEPT six: %s.\n"
             % (", ".join(G.RETIRED_LEVEL_FAMILIES),
                ", ".join(G.KEPT_LEVEL_FAMILIES)))

    # -------------------------------------------------------- marginals -----
    L.append("## Marginal contribution of each family (era ALL)\n")
    rows = []
    for a in M.ASSET_ORDER:
        for f in G.FAMILIES:
            r, ln = mrg.one(asset=a, family=f, era=M.ERA_ALL)
            if r is None:
                continue
            rows.append([a, f + (" (NEW)" if f in G.NEW_FAMILIES else ""),
                         num(r, mrg, "n_candidates", "%.0f"),
                         num(r, mrg, "n_exclusive_total", "%.0f"),
                         num(r, mrg, "conditional_value_usd", "$%.0f"),
                         num(r, mrg, "marginal_recall_gate_pp", "%+.3f"),
                         num(r, mrg, "marginal_recall_all_pp", "%+.3f"),
                         num(r, mrg, "exclusive_dp_add_median_usd", "$%.0f"),
                         num(r, mrg, "exclusive_dp_add_mean_usd", "$%.0f"),
                         cite(mrg, ln)])
    L.append(md_table(["asset", "family", "candidates", "exclusive candidates",
                       "conditional value", "marginal GATE recall (pp)",
                       "marginal ALL-legs recall (pp)",
                       "exclusive DP add median/day",
                       "exclusive DP add mean/day", "source"], rows))
    L.append("\nMarginal = union minus the roster with that family's EXCLUSIVE "
             "candidates removed. The DP add is saturated by construction "
             "(CC-M1-3.2 already replaced it as a retirement metric: hundreds "
             "of candidates compete for ~3 seats), so it is reported, not "
             "gated.\n")

    # ------------------------------------------------------- build stats ----
    L.append("## Build statistics (masked arm)\n")
    rows = []
    for a in M.ASSET_ORDER:
        rs = [(r, ln) for r, ln in zip(bld.rows, bld.lines)
              if r[bld.i("asset")] == a]
        if not rs:
            continue

        def tot(c, rs=rs):
            return sum(float(r[bld.i(c)]) for r, _ in rs)
        rows.append([a, len(rs), "%.0f" % tot("n_g1_confirmations"),
                     "%.0f" % tot("n_union_candidates"),
                     "%.0f" % tot("n_fast_open_candidates"),
                     "%.0f" % tot("n_g2_events"),
                     "%.0f" % tot("n_g2_dropped_retired_level"),
                     "%.0f" % tot("n_g2_dropped_reclaim_bound"),
                     "%.0f" % tot("n_coarse_conf_only_v2"),
                     "%.0f" % tot("n_coarse_conf_only_m1a"),
                     cite(bld, rs[0][1])])
    L.append(md_table(["asset", "sessions", "confirmations (4-rung ladder)",
                       "union candidates", "FAST-OPEN candidates",
                       "G2 events kept", "G2 dropped: retired level source",
                       "G2-RECLAIM dropped: 30-min bound",
                       "ladder drift (v2 only)", "ladder drift (M1.A only)",
                       "source"], rows))
    L.append("\nLADDER DIFFERENTIAL: the drift columns count confirmations "
             "where the m0 3-rung set differs from the M1.A reference "
             "(`m1/decay/g1_conf_*.npz`). In the UNMASKED arm this is an "
             "ASSERTION — prepending the FINE rung may not perturb the m0 "
             "ladder, and the run aborts otherwise; it measured **0 / 0 on all "
             "three assets** there. In the MASKED arm it is a MEASUREMENT: the "
             "ZigZag spine itself moves because insane seconds leave the mid "
             "series, and the M1.A reference was built before D-054. The "
             "values below are that measurement (SPEC_DEFECTS D16).\n")

    # ------------------------------------------------------- occupancy ------
    L.append("## Occupancy DP re-run (for the record)\n")
    rows = []
    for a in M.ASSET_ORDER:
        for era, yrs in ((M.ERA_FIT, M.FIT_YEARS), (M.ERA_GATE, (2025,)),
                         (M.ERA_ALL, None)):
            dp, ln, n = _rollup(seat, a, yrs, "union_dp_close_usd")
            dpm, _, _ = _rollup(seat, a, yrs, "union_dp_close_usd", "mean")
            nc, _, _ = _rollup(seat, a, yrs, "n_union")
            ns, _, _ = _rollup(seat, a, yrs, "n_seated_union")
            if not n:
                continue
            rows.append([a, era, n, "$%.0f" % dp, "$%.0f" % dpm, "%.0f" % nc,
                         "%.0f" % ns, cite(seat, ln)])
    L.append(md_table(["asset", "era", "sessions", "union DP median/day",
                       "union DP mean/day", "candidates/day", "seated/day",
                       "source"], rows))
    L.append("\nORACLE CERTIFICATE CEILINGS on the M0 convention (walled "
             "phase-close, one position), never forecasts.\n")

    # -------------------------------------------------------- D-053 ---------
    L.append("## D-053 (VWAP bands) acknowledgement\n")
    n_ok = sum(1 for r in vwd.rows if r[vwd.i("verdict")] == "PASS")
    L.append("The VWAP level family is now the VWAP LINE plus +-2.0/+-2.5 x "
             "sigma_vwap (session and phase), replacing +-1/+-2. The ledger was "
             "regenerated by re-running the frozen §4 builder with the new "
             "bands (`engine/port_m1/b7_levels_v2.py`) into `m1/levels_v2/` "
             "(unmasked control) and `m1/levels_v3/` (D-053 + D-054 mask, what "
             "this census consumes). D-053 rebuild differential: %d/%d sampled "
             "sessions PASS — every non-VWAP ledger row identical to the M1.A "
             "ledger, every VWAP row a D-053 band (%s).\n"
             % (n_ok, len(vwd.rows),
                cite(vwd, vwd.lines[0] if vwd.lines else 0)))

    # -------------------------------------------------------- readings ------
    L.append("""## Pinned readings and spec ambiguities (for adjudication)

1. **G1-FAST-OPEN is ADDITIVE.** CC-M1-3.4b gives it a *separate family tag*,
   so the 15s candidate is emitted BESIDE the tau*=120s candidate of the same
   confirmation, not instead of it. PORT_M1B_SPEC §1 S2's shorthand
   "tau*=120s (15s in open windows)" would also admit a REPLACEMENT reading.
   The additive reading is the superset (it can only help a recall gate) and it
   is the only one under which the family's marginal contribution is
   measurable, so it is what this oracle emits. The C++ lane must match it
   candidate-exact; if the orchestrator intends replacement, that is a one-line
   change here and a re-census. (SPEC_DEFECTS D13.)
2. **The 15s delay applies to G1 rungs only** — CC-M1-3.4b says "on all rungs",
   and rungs are a G1 object, so G2 keeps tau* even inside an open window.
   (SPEC_DEFECTS D14.)
3. **"trailing-phase-median spread"** (D-054) is built causally: the exact
   pooled median of two-sided spreads over the same phase of the trailing 60
   sessions (integer tick histograms — the repo's existing trailing-60-session
   clock-norm convention), strictly prior to the session being masked. Phases
   with no trailing observation (the first sessions) fall back to the $500 cap
   alone. If the orchestrator meant the M0 per-year phase-median object
   instead, the thresholds change slightly; the pathological books are killed
   by the cap either way.
4. **The 30-min RECLAIM bound is enforced at generation**, on the ledger's
   first-reclaim record — exactly equivalent to bounding the ledger's own
   search (the §4 state machine returns the EARLIEST reclaim confirmation) and
   the hook b3_levels deliberately left for M1.B.
5. **Phase opens** = session second 0 plus every phase-tag change of the frozen
   3-phase table. The FAST-OPEN window is half-open [open, open+300).
6. **The gate/news split is computed from the oracle leg's own span** on the
   sane series, before any roster is consulted, so it cannot be tuned by the
   roster.
""")
    with open(OUT, "w") as fh:
        fh.write("\n".join(L) + "\n")
    print(OUT)
    return 0


if __name__ == "__main__":
    sys.exit(main())
