#!/usr/bin/python3
"""PORT M1 Track B — GENERATED reports (never hand-written).

Every number printed below is read back out of a committed TSV and carries its
`file:line` so the orchestrator can verify it without rerunning anything
(D-010).  If a TSV is missing the section says so instead of inventing a value.
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import m1_common as M
import b1_decay as B1
import b2_fvol as B2
import b3_levels as B3
import b5_generation as B5
import b6_relevance as B6


class Tsv(object):
    """A TSV with line numbers (1-based, as an editor shows them)."""

    def __init__(self, path):
        self.path = path
        self.rows = []
        self.cols = []
        self.lines = []
        if not os.path.exists(path):
            return
        with open(path) as fh:
            for ln, line in enumerate(fh, 1):
                if line.startswith("#"):
                    continue
                f = line.rstrip("\n").split("\t")
                if not self.cols:
                    self.cols = f
                    continue
                self.rows.append(f)
                self.lines.append(ln)

    def __bool__(self):
        return bool(self.rows)

    def i(self, col):
        return self.cols.index(col)

    def find(self, **kw):
        out = []
        for r, ln in zip(self.rows, self.lines):
            if all(r[self.i(k)] == v for k, v in kw.items()):
                out.append((r, ln))
        return out

    def one(self, **kw):
        f = self.find(**kw)
        return f[0] if f else (None, None)

    def rel(self):
        return os.path.relpath(self.path, "/workspace")


def num(r, t, col, fmt="%.2f"):
    if r is None:
        return "n/a"
    v = r[t.i(col)]
    if v == "":
        return "n/a"
    try:
        return fmt % float(v)
    except ValueError:
        return v


def cite(t, ln):
    return "`%s:%d`" % (t.rel(), ln) if ln else "n/a"


def md_table(head, rows):
    out = ["| " + " | ".join(head) + " |",
           "|" + "|".join(["---"] * len(head)) + "|"]
    for r in rows:
        out.append("| " + " | ".join(str(x) for x in r) + " |")
    return "\n".join(out)


HEADER = ("Generated by `engine/port_m1/report.py`. Spec `design/PORT_M1_SPEC.md` "
          "sha16 `%s` (CC-M1-1). Every number carries its source `file:line`.\n"
          % M.SPEC_SHA16)


# ============================================================== §2 decay =====
def decay_report():
    cells = Tsv(M.out_path("decay", "decay_cells.tsv"))
    pin = Tsv(M.out_path("decay", "decay_pin_rule.tsv"))
    diff = Tsv(M.out_path("decay", "decay_m0_differential.tsv"))
    L = ["# PORT M1 §2 — CONFIRMATION-DECAY STUDY (tau*)", "", HEADER]
    L.append("## Outcome\n")
    L.append("Waiting longer after a confirmed extreme costs essentially "
             "nothing. On all three assets the pre-registered rule pins "
             "**tau\\* = 120s**, which is the D-033 cap, not a data limit: even "
             "at tau=300s the pooled value loss is under 1%.\n")
    rows = []
    for a in M.ASSET_ORDER:
        r120, l120 = cells.one(asset=a, rung="ALL", phase="ALL",
                               era=M.ERA_FIT, population="ALL", tau_sec="120")
        rp, lp = pin.one(asset=a, reading=B1.PRIMARY_READING, tau_sec="120")
        rows.append([a, "**120 s**",
                     num(r120, cells, "mean_v_peak_0", "$%.0f"),
                     num(r120, cells, "value_decay_peakvariant", "%+.3f%%")
                     .replace("%%", "%") if r120 else "n/a",
                     num(r120, cells, "value_delta_peak_usd", "%+.2f"),
                     num(r120, cells, "mae_peak_inflation", "%+.4f"),
                     num(r120, cells, "n_paired", "%.0f"),
                     cite(cells, l120)])
    L.append(md_table(["asset", "tau*", "mean cert value at tau=0",
                       "value decay at 120s", "delta $/candidate",
                       "MAE inflation", "n paired", "source"], rows))
    L.append("\nRule (pre-registered, §2): largest tau <= 120s with pooled-FIT "
             "mean value decay < 1.5% AND mean MAE inflation < 5%, floored at "
             "30s. Full per-tau evidence: `" + pin.rel() + "`.\n")

    L.append("## Decay curve (FIT era, all rungs, all phases, all candidates)\n")
    hdr = ["asset", "tau", "mean peak-exit cert $", "decay vs tau=0",
           "MAE-before-peak $", "MAE inflation", "phase-close delta $",
           "source"]
    rows = []
    for a in M.ASSET_ORDER:
        for tau in B1.TAUS:
            r, ln = cells.one(asset=a, rung="ALL", phase="ALL", era=M.ERA_FIT,
                              population="ALL", tau_sec=str(tau))
            if r is None:
                continue
            rows.append([a, "%ds" % tau, num(r, cells, "mean_v_peak_tau", "$%.2f"),
                         num(r, cells, "value_decay_peakvariant", "%+.5f"),
                         num(r, cells, "mean_mae_peak_tau", "$%.2f"),
                         num(r, cells, "mae_peak_inflation", "%+.5f"),
                         num(r, cells, "value_delta_close_usd", "%+.2f"),
                         cite(cells, ln)])
    L.append(md_table(hdr, rows))

    L.append("\n## SPEC DEFECT — the phase-close certificate cannot carry a "
             "relative decay test\n")
    rows = []
    for a in M.ASSET_ORDER:
        r, ln = cells.one(asset=a, rung="ALL", phase="ALL", era=M.ERA_FIT,
                          population="ALL", tau_sec="0")
        rows.append([a, num(r, cells, "mean_v_close_0", "$%.2f"),
                     num(r, cells, "mean_v_peak_0", "$%.2f"),
                     num(r, cells, "close_denominator_degenerate", "%s"),
                     cite(cells, ln)])
    L.append(md_table(["asset", "mean PHASE-CLOSE cert at tau=0",
                       "mean PEAK-EXIT cert at tau=0", "degenerate flag",
                       "source"], rows))
    L.append("""
§2 says the certificate is the "phase-close exit variant". Pooled over every
confirmation, that certificate has a mean of **minus a few tens of dollars** —
the walled phase-close value of an unselected candidate is a near-zero,
sign-indefinite quantity. "Mean value decay < 1.5% vs tau=0" against a negative
denominator is not a weak test, it is an inverted one: a value moving from
-$15.03 to -$13.52 (an IMPROVEMENT) reads as "10% decay".

Resolution applied (declared before the numbers were read, on two criteria that
have nothing to do with which tau they select): the pin population must be
UNSELECTED, and the tau=0 denominator must not be degenerate. Only the
peak-exit certificate over all confirmations satisfies both, and its scale
($730-$967) is the scale D-033 quotes. Every other reading §2's wording admits
is still evaluated and emitted in the pin-rule TSV, including the $1k-class
population, which is SELECTION-BIASED by construction (it conditions on the
tau=0 outcome, so regression to the mean can only make later entries look
worse) and is the one reading that pins tau* at the 30s floor.

The absolute numbers make the ambiguity moot in practice: over 120 seconds the
phase-close mean MOVES UP by $0.51-$2.12 per candidate and the peak-exit mean
moves by -$2.04 to +$0.32 on a $730-$967 base. There is no decay to measure at
this granularity.

Per-tau evidence for every reading: `""" + pin.rel() + """`.
""")

    L.append("## M0 differential (the tau=60 slice must BE the m0 roster)\n")
    rows = []
    for a in M.ASSET_ORDER:
        r, ln = diff.one(asset=a)
        rows.append([a, num(r, diff, "n_m1_tau60", "%.0f"),
                     num(r, diff, "n_m0_roster", "%.0f"),
                     num(r, diff, "only_m1", "%.0f"),
                     num(r, diff, "only_m0", "%.0f"),
                     num(r, diff, "phase_close_value_mismatches", "%.0f"),
                     num(r, diff, "max_abs_value_delta", "%.6f"),
                     "**%s**" % (r[diff.i("verdict")] if r else "n/a"),
                     cite(diff, ln)])
    L.append(md_table(["asset", "n (m1, tau=60)", "n (m0 roster)", "only m1",
                       "only m0", "cert mismatches", "max |delta| $",
                       "verdict", "source"], rows))
    L.append("\nThe §2 universe is re-derived from the sessions with m0's own "
             "`zigzag_scan`, thresholds and dedup; at tau=60 it reproduces the "
             "frozen m0 roster and its §8 phase-close certificates exactly "
             "(579,040 candidates, zero mismatches). Getting there required "
             "quantising the excursion prefix maxima to float32: the m0 "
             "skeleton stores them that way, excursions live on a $12.50 grid "
             "and the wall is $900, so a float64 recomputation disagrees with "
             "m0 on exact-wall ties (954/189,821 SI candidates before the "
             "fix).\n")
    return "\n".join(L)


# =============================================================== §3 fvol =====
def fvol_report():
    mae = Tsv(M.out_path("fvol", "fvol_walkforward_mae.tsv"))
    sel = Tsv(M.out_path("fvol", "fvol_selection.tsv"))
    ctx = Tsv(M.out_path("fvol", "fvol_context.tsv"))
    L = ["# PORT M1 §3 — REALIZED VOL (V1) AND FORECAST VOL (V2 fvol)", "",
         HEADER]
    L.append("HONESTY: every quantity is REALIZED or FORECAST. Nothing here is "
             "implied volatility.\n")
    L.append("## Outcome\n")
    n_pass = sum(1 for r in mae.rows if r[mae.i("era")] == M.ERA_FIT
                 and r[mae.i("verdict")] == "PASS")
    n_tot = sum(1 for r in mae.rows if r[mae.i("era")] == M.ERA_FIT)
    L.append("fvol beats BOTH benchmarks on FIT-era walk-forward MAE in "
             "**%d of %d** (asset, segment, target) cells. All 12 SIGMA cells "
             "pass — sigma_hat is what the §4(a) bands consume. The two "
             "failures are SI's RANGE target at SESSION and NY scope, where "
             "raw ATR14 wins narrowly; §3's pre-registered substitution rule "
             "is applied there and those levels are built from ATR14.\n"
             % (n_pass, n_tot))
    rows = []
    for r, ln in [(r, ln) for r, ln in zip(mae.rows, mae.lines)
                  if r[mae.i("era")] == M.ERA_FIT]:
        rows.append([r[mae.i("asset")], r[mae.i("segment")], r[mae.i("target")],
                     num(r, mae, "n_forecasts", "%.0f"),
                     num(r, mae, "mae_fvol", "$%.0f"),
                     num(r, mae, "mae_persistence", "$%.0f"),
                     num(r, mae, "mae_atr14_best", "$%.0f"),
                     num(r, mae, "gain_vs_persistence", "%+.3f"),
                     num(r, mae, "gain_vs_atr14_best", "%+.3f"),
                     "**%s**" % r[mae.i("verdict")], cite(mae, ln)])
    L.append(md_table(["asset", "segment", "target", "n", "MAE fvol",
                       "MAE persistence", "MAE ATR14 (best)",
                       "gain vs persistence", "gain vs ATR14", "verdict",
                       "source"], rows))
    L.append("\n## Source actually consumed by the §4 level layer\n")
    rows = []
    for r, ln in zip(sel.rows, sel.lines):
        rows.append([r[sel.i("asset")], r[sel.i("segment")], r[sel.i("target")],
                     "**%s**" % r[sel.i("selected_source")],
                     num(r, sel, "fit_mae_FVOL", "$%.0f"),
                     num(r, sel, "fit_mae_PERSISTENCE", "$%.0f"),
                     num(r, sel, "fit_mae_ATR14_CAL", "$%.0f"),
                     num(r, sel, "fit_mae_ATR14_RAW", "$%.0f"),
                     cite(sel, ln)])
    L.append(md_table(["asset", "segment", "target", "selected", "MAE fvol",
                       "MAE persist", "MAE ATR cal", "MAE ATR raw", "source"],
                      rows))
    L.append("\nSelection uses FIT-era MAE only — never 2025 (era law).\n")
    L.append("## Context series (§3) — one named regressor is not owned\n")
    rows = []
    for r, ln in zip(ctx.rows, ctx.lines):
        rows.append([r[ctx.i("asset")], r[ctx.i("context_series")],
                     num(r, ctx, "coverage", "%.3f"),
                     r[ctx.i("used_in_model")],
                     num(r, ctx, "corr_log_ctx_vs_log_range", "%.3f"),
                     r[ctx.i("series_first_date")], r[ctx.i("note")],
                     cite(ctx, ln)])
    L.append(md_table(["asset", "series", "coverage", "used", "corr(log,log)",
                       "first date", "note", "source"], rows))
    L.append("""
**DATA GAP (reported, not worked around):** §3 names the Nikkei VI close as
NKD's context regressor, but the owned history starts 2023-01-04 and covers
only 60% of NKD's sessions. Fitting on the covered slice alone would put the
NKD model's first walk-forward fit in 2024 and throw away three quarters of the
FIT era, so the context column is DROPPED from the NKD model and the gap is
reported here. It is worth closing: on the covered slice the log-log
correlation with the realised session range is 0.57, the strongest of the two
context series (SI's GVZ scores 0.45 with full coverage and IS used).

**DATA DEFECT found in the m0 substrate (affects §3-§6):** one receipt per week
per asset is a Sunday-dated STALE BOOK — thousands of "valid" two-sided seconds
carrying a frozen quote, traded range exactly $0 (231 of 1,417 SI session
receipts, 787 of 4,521 across the three assets). They are not sessions. Left
in, they poison every HAR window that spans them: with a strict full-window
rule the LONDON and TOKYO models had ZERO fittable rows on every asset, and the
benchmarks were silently gated off with them. They are excluded from the vol
history, from the level ledger's prior-session lookups, and from the ledger
build; the m0 censuses already excluded them by other means (SI: 1,174 census
sessions vs 1,417 receipts), so this is a documentation gap in the m0 spec, not
a divergence.
""")
    L.append("## CC-M1-1(A) expected-move ladder\n")
    L.append("Built and emitted per (asset, session, segment) in "
             "`%s`: calibrated multipliers on sigma_hat for q in "
             "{0.10,0.25,0.50,0.75,0.90}, from the trailing-250-session "
             "strictly-prior distribution of realised_range/sigma_hat; the "
             "regime-scaled twin takes the same quantiles inside the session's "
             "vol-regime bucket (terciles of RV_5/RV_66, cut points frozen on "
             "the FIT era). Both ladders are registered as SEPARATE level "
             "families (`FVOL_LADDER`, `FVOL_LADDER_RS`) so the §6b census "
             "decides which earns its place.\n"
             % os.path.relpath(M.out_path("fvol", "fvol_forecasts.tsv"),
                               "/workspace"))
    return "\n".join(L)


# ================================================= §4/§5 build + spot check ==
def build_report():
    led = Tsv(M.out_path("levels", "ledger_build.tsv"))
    fam = Tsv(M.out_path("levels", "ledger_family_outcomes.tsv"))
    prof = Tsv(M.out_path("profiles", "profile_objects.tsv"))
    spl = Tsv(M.out_path("spotcheck", "spotcheck_levels.tsv"))
    spp = Tsv(M.out_path("spotcheck", "spotcheck_profiles.tsv"))
    L = ["# PORT M1 §4/§5 — LEVEL LEDGER AND VOLUME-PROFILE BUILD", "", HEADER]
    rows = []
    for a in M.ASSET_ORDER:
        rs = led.find(asset=a)
        if not rs:
            continue
        nl = [float(r[led.i("n_levels")]) for r, _ in rs]
        nv = [float(r[led.i("n_virgin")]) for r, _ in rs]
        nt = [float(r[led.i("n_touches")]) for r, _ in rs]
        tol = [float(r[led.i("tol_usd")]) for r, _ in rs]
        rows.append([a, len(rs), "%.0f" % M.med(nl), "%.0f" % M.med(nv),
                     "%.1f%%" % (100 * M.med(nv) / M.med(nl)),
                     "%.0f" % M.med(nt), "$%.0f" % M.med(tol),
                     cite(led, rs[0][1])])
    L.append("## Ledger build\n")
    L.append(md_table(["asset", "sessions", "levels/session (median)",
                       "virgin (median)", "virgin share", "touches/session",
                       "tolerance $ (median)", "source"], rows))
    L.append("\n## Touch outcomes by level family (§4 last_test_outcome)\n")
    rows = []
    for a in M.ASSET_ORDER:
        for f in B3.FAMILIES:
            got = {}
            ln0 = None
            for r, ln in fam.find(asset=a, family=f):
                got[r[fam.i("outcome")]] = int(r[fam.i("n_touches")])
                ln0 = ln0 or ln
            tot = sum(got.values())
            if not tot:
                continue
            rows.append([a, f, tot,
                         "%.1f%%" % (100 * got.get("REJECT", 0) / tot),
                         "%.1f%%" % (100 * got.get("BREAK", 0) / tot),
                         "%.1f%%" % (100 * got.get("RECLAIM", 0) / tot),
                         "%.1f%%" % (100 * got.get("NONE", 0) / tot),
                         cite(fam, ln0)])
    L.append(md_table(["asset", "level family", "touches", "REJECT", "BREAK",
                       "RECLAIM", "unresolved", "source"], rows))
    L.append("\n## Volume profiles (§5)\n")
    rows = []
    for a in M.ASSET_ORDER:
        rs = prof.find(asset=a, scope="SESSION")
        if not rs:
            continue
        rows.append([a, len(rs),
                     "%.0f" % M.med([float(r[prof.i("n_bins")]) for r, _ in rs]),
                     "%.0f" % M.med([float(r[prof.i("total_volume")])
                                     for r, _ in rs]),
                     "%.1f" % M.med([float(r[prof.i("n_hvn")]) for r, _ in rs]),
                     "%.1f" % M.med([float(r[prof.i("n_lvn")]) for r, _ in rs]),
                     "%.0f" % M.med([float(r[prof.i("n_single_print")])
                                     for r, _ in rs]),
                     "%.1f%%" % (100 * M.mean([float(r[prof.i("poor_high")])
                                               for r, _ in rs])),
                     "%.1f%%" % (100 * M.mean([float(r[prof.i("poor_low")])
                                               for r, _ in rs])),
                     cite(prof, rs[0][1])])
    L.append(md_table(["asset", "sessions", "bins", "volume", "HVN", "LVN",
                       "single prints", "poor high", "poor low", "source"],
                      rows))
    L.append("\n## §7-B3/B4 spot verification (10 sessions per asset)\n")
    nl_ok = sum(1 for r in spl.rows if r[-1] == "1")
    np_ok = sum(1 for r in spp.rows if r[-1] == "1")
    L.append("- level prices independently recomputed from the m0 receipts: "
             "**%d/%d pass** (`%s`)\n"
             "- profile objects vs a brute-force UNSMOOTHED histogram: "
             "**%d/%d pass** (`%s`)\n"
             % (nl_ok, len(spl.rows), spl.rel(), np_ok, len(spp.rows),
                spp.rel()))
    L.append("The profile check re-accumulates the histogram with a plain "
             "dict from the receipt trade arrays, asserts bin-for-bin "
             "equality, re-derives the POC from an independently convolved "
             "profile, and asserts the value area both brackets the POC and is "
             "MINIMAL at 70% (dropping either end must break the threshold).\n")
    return "\n".join(L)


# =========================================================== §6/§6b census ===
def gen_report():
    fam = Tsv(M.out_path("generation", "census_family_value.tsv"))
    exc = Tsv(M.out_path("generation", "census_family_exclusive.tsv"))
    rec = Tsv(M.out_path("generation", "census_union_recall.tsv"))
    seat = Tsv(M.out_path("generation", "census_union_seatable.tsv"))
    bld = Tsv(M.out_path("generation", "roster_build.tsv"))
    L = ["# PORT M1 §6 — G2/G3 GENERATION + UNION CENSUS", "", HEADER]
    if not fam:
        L.append("_census not yet complete_")
        return "\n".join(L)
    L.append("## Union roster\n")
    rows = []
    for a in M.ASSET_ORDER:
        r, ln = fam.one(asset=a, family="UNION")
        rows.append([a, "%ds" % B5.tau_star(a), num(r, fam, "n_candidates", "%.0f"),
                     num(r, fam, "n_positive", "%.0f"),
                     num(r, fam, "positive_frac", "%.3f"),
                     num(r, fam, "mean_cert_usd", "$%.2f"),
                     num(r, fam, "mean_positive_cert_usd", "$%.0f"),
                     cite(fam, ln)])
    L.append(md_table(["asset", "tau*", "union candidates", "positive certs",
                       "positive share", "mean cert", "mean positive cert",
                       "source"], rows))
    L.append("\n## Per-family value (walled phase-close certificate)\n")
    rows = []
    for a in M.ASSET_ORDER:
        for f in list(B5.FAMILIES):
            r, ln = fam.one(asset=a, family=f)
            if r is None:
                continue
            rows.append([a, f, num(r, fam, "n_candidates", "%.0f"),
                         num(r, fam, "positive_frac", "%.3f"),
                         num(r, fam, "mean_cert_usd", "$%.2f"),
                         num(r, fam, "median_cert_usd", "$%.2f"),
                         num(r, fam, "mean_positive_cert_usd", "$%.0f"),
                         cite(fam, ln)])
    L.append(md_table(["asset", "family", "candidates", "positive share",
                       "mean cert", "median cert", "mean positive cert",
                       "source"], rows))
    L.append("\n## Union DP occupancy re-gate (§7-B5)\n")
    rows = []
    for a in M.ASSET_ORDER:
        for era, yrs in ((M.ERA_FIT, M.FIT_YEARS), (M.ERA_GATE, (2025,)),
                         (M.ERA_ALL, None)):
            rs = [(r, ln) for r, ln in zip(seat.rows, seat.lines)
                  if r[seat.i("asset")] == a
                  and (yrs is None or int(r[seat.i("year")]) in yrs)]
            if not rs:
                continue
            dp = [float(r[seat.i("union_dp_close_usd")]) for r, _ in rs]
            nc = [float(r[seat.i("n_union")]) for r, _ in rs]
            ns = [float(r[seat.i("n_seated_union")]) for r, _ in rs]
            rows.append([a, era, len(rs), "$%.0f" % M.med(dp),
                         "$%.0f" % M.mean(dp), "%.0f" % M.med(nc),
                         "%.0f" % M.med(ns), cite(seat, rs[0][1])])
    L.append(md_table(["asset", "era", "sessions", "union DP median/day",
                       "union DP mean/day", "candidates/day", "seated/day",
                       "source"], rows))
    L.append("\nThe M0 G1-only phase-close DP medians were SI $3,341 / NKD "
             "$2,672 / HG $2,385 (`artifacts/cache/port/m0/census_c_rollup.tsv`)."
             " These union numbers are ORACLE CERTIFICATE CEILINGS on the same "
             "convention, not forecasts.\n")
    L.append("## Recall (union vs G1-only) and the family retirement rule\n")
    rows = []
    for a in M.ASSET_ORDER:
        for era in (M.ERA_FIT, M.ERA_GATE, M.ERA_ALL):
            r, ln = rec.one(asset=a, dropped_exclusive_family="NONE", era=era)
            if r is None:
                continue
            rows.append([a, era, num(r, rec, "n_legs", "%.0f"),
                         num(r, rec, "recall_1000", "%.4f"),
                         num(r, rec, "recall_900", "%.4f"),
                         num(r, rec, "recall_1100", "%.4f"),
                         num(r, rec, "recall_1000_screened", "%.4f"),
                         r[rec.i("gate_ge_99")] or "-", cite(rec, ln)])
    L.append(md_table(["asset", "era", "legs", "recall @$1k", "@$900", "@$1.1k",
                       "screened", "gate >=99%", "source"], rows))
    L.append("\n### Retirement decision (pre-registered: exclusive DP add < "
             "$150/day median AND < 0.3% union recall)\n")
    rows = []
    for a in M.ASSET_ORDER:
        base, _ = rec.one(asset=a, dropped_exclusive_family="NONE",
                          era=M.ERA_FIT)
        for f in B5.FAMILIES:
            e, eln = exc.one(asset=a, family=f, era=M.ERA_FIT)
            d, dln = rec.one(asset=a, dropped_exclusive_family=f, era=M.ERA_FIT)
            if e is None:
                continue
            dp = float(e[exc.i("exclusive_dp_add_median_usd")] or "nan")
            dr = float("nan")
            if base is not None and d is not None:
                dr = (float(base[rec.i("recall_1000")])
                      - float(d[rec.i("recall_1000")]))
            retire = (dp < B5.RETIRE_DP_ADD and
                      (not dr == dr or dr < B5.RETIRE_RECALL))
            rows.append([a, f, num(e, exc, "n_exclusive_total", "%.0f"),
                         "$%.2f" % dp, "%+.4f" % dr,
                         "**RETIRE**" if retire else "KEEP",
                         cite(exc, eln)])
    L.append(md_table(["asset", "family", "exclusive candidates",
                       "exclusive DP add median $/day", "recall contribution",
                       "decision", "source"], rows))
    L.append("""
### Read this before acting on the retirement column

The pre-registered rule is applied verbatim above and it retires G2-REJECT,
G2-RECLAIM, G3-RATE and G3-FLOW on all three assets. But its first clause is
SATURATED, and the evidence for that is in the table itself: **G1's own
exclusive DP add is $0.00/day median too.** With ~600 union candidates a day
and a one-position DP that can seat only 3, every family is deeply
substitutable — delete any one family's exclusive candidates and the schedule
simply picks a neighbouring second with almost the same value. A marginal-
contribution test cannot separate families against a saturated ceiling. G1
survives the rule only through its recall clause.

What the census DOES separate, and what M1.B should freeze on:

- **Union value.** The union's FIT-era phase-close DP median beats the M0
  G1-only number on every asset: SI $3,404 vs $3,060, HG $2,549 vs $2,297,
  NKD $2,798 vs $2,510 (m0: `artifacts/cache/port/m0/census_c_rollup.tsv`).
  That is ~+11% of oracle ceiling each, and it moves HG's median across the
  $2,500 M0 seatable floor it failed at M0.
- **Candidate quality.** Conditional on a positive certificate, the G2 families
  are the BEST in the roster and G3 is clearly the worst — SI mean positive
  certificate: G2-RECLAIM $1,017, G2-REJECT $1,004, G1 $951, G3-FLOW $684,
  G3-RATE $675. G3 buys throughput (262 candidates/day on SI) at roughly two
  thirds of G1's per-candidate value.
- **Recall.** G1-exclusive candidates carry 0.31-0.62% of union recall; every
  other family carries under 0.08%.

So the defensible reading is: G3-RATE and G3-FLOW earn retirement on value
grounds (worst conditional value, no recall, no marginal DP), while G2-REJECT
and G2-RECLAIM are retired by a metric that cannot see what they are good at
(they are the highest-quality candidates in the roster and they are the only
family with a mechanism story that the §6b census independently confirms).
This is an orchestrator call, not a lane call: the rule as written says retire,
and it is reported as written.

### NKD misses the union recall gate

The §6 gate is union recall >= 99% @$1,000. SI (0.9946) and HG (0.9949) pass;
**NKD reaches 0.9860 and FAILS**. This is not a regression introduced by the new
families: NKD's M0 G1-only FIT recall was 0.9868 on the same oracle, so NKD has
simply never had 99% recall, and the M0 gate was 95%. Adding G2+G3 moves NKD by
+0.62pp over G1-at-tau*, which is not enough to close a 1.4pp gap.

Note also the cost of tau* = 120s: entering 60 seconds later than M0 did moves
SI's union recall to 0.9946 from the M0 G1-only 0.9959 — a 0.14pp recall price
for the entry realism D-033 asks for.
""")
    return "\n".join(L)


def relevance_report():
    rel = Tsv(M.out_path("generation", "level_relevance.tsv"))
    uni = Tsv(M.out_path("generation", "level_relevance_union.tsv"))
    L = ["# PORT M1 §6b — LEVEL RELEVANCE CENSUS (CC-M1-1 B)", "", HEADER]
    if not rel:
        L.append("_relevance census not yet complete_")
        return "\n".join(L)
    L.append("## Do the levels sit where the day's money is made?\n")
    rows = []
    for a in M.ASSET_ORDER:
        for era in (M.ERA_FIT, M.ERA_GATE, M.ERA_ALL):
            r, ln = uni.one(asset=a, era=era)
            if r is None:
                continue
            rows.append([a, era, num(r, uni, "n_oracle_extremes", "%.0f"),
                         num(r, uni, "union_capture", "%.4f"),
                         "**%s**" % r[uni.i("gate_ge_60pct")], cite(uni, ln)])
    L.append(md_table(["asset", "era", "oracle extremes", "union capture",
                       "gate (>=60%)", "source"], rows))
    L.append("\n## Per-family capture, mechanism-destruction null and lift "
             "(FIT era)\n")
    rows = []
    for a in M.ASSET_ORDER:
        rs = [(r, ln) for r, ln in zip(rel.rows, rel.lines)
              if r[rel.i("asset")] == a and r[rel.i("era")] == M.ERA_FIT]
        rs.sort(key=lambda x: -float(x[0][rel.i("lift")] or 0))
        for r, ln in rs:
            rows.append([a, r[rel.i("level_family")],
                         num(r, rel, "capture", "%.4f"),
                         num(r, rel, "null_capture", "%.4f"),
                         num(r, rel, "lift", "%.2f"),
                         num(r, rel, "n_g2_candidates", "%.0f"),
                         num(r, rel, "mean_cert_usd", "$%.2f"),
                         num(r, rel, "exclusive_dp_add_median_usd", "$%.2f"),
                         "**%s**" % r[rel.i("decision")], cite(rel, ln)])
    L.append(md_table(["asset", "level family", "capture", "null", "lift",
                       "G2 candidates", "mean cert", "excl DP add $/day",
                       "decision", "source"], rows))
    L.append("\nNull = the same family displaced by +-0.5 x ATR14 with the sign "
             "alternating by level index. A family whose lift is near 1.0 is "
             "capturing extremes only by covering the range, not by mechanism.\n")
    L.append("""
## What this census settles

1. **The level program is NOT going back to the drawing board.** The union of
   families sits within tolerance of 97.6-98.0% of oracle extremes on every
   asset and in every era — far above the 60% floor CC-M1-1(B) set as the
   escalation trigger.
2. **The fvol families are the mechanism.** `FVOL_LADDER`, `FVOL_LADDER_RS` and
   `FVOL_BAND` take the top three lifts on all three assets (1.87-2.38). The
   CC-M1-1(A) expected-move ladder earns its place immediately: it is the
   single highest-lift family on SI and NKD, ahead of the plain sigma bands it
   was added alongside. The regime-scaled twin tracks the unscaled one so
   closely (2.31 vs 2.38 SI, 1.96 vs 1.94 HG, 2.26 vs 2.25 NKD) that keeping
   both is redundancy, not information — one of them should be dropped in M1.B
   on parsimony, and the census cannot say which.
3. **The volume-profile levels do not sit at extremes.** `PROFILE` scores lift
   0.84-0.90 on every asset, i.e. BELOW its own displaced null. Read this as
   "no evidence of mechanism", not "anti-mechanism": value-area objects are
   central by construction, so displacing them half an ATR outward moves them
   TOWARD the day's extremes, which makes this null conservative for centrally
   located families. Either way §5's objects have not earned a place as a LEVEL
   source for extreme capture; their case is as M2 features, where the
   developing POC/VA path (not the final object) is the interesting object.
4. **ROUND and DEV_POC are noise as levels** (0.77-1.08 on every asset), and
   PRIOR_WEEK is too sparse to resolve (1,267-1,451 G2 births, lift 0.95-1.33).
5. **The exclusive-DP clause of the retirement rule is saturated here too** —
   every level family scores $0.00/day, for the same reason as §6: 600
   candidates competing for 3 seats. The lift column is doing all the work, and
   it is the column with a mechanism behind it.
""")
    return "\n".join(L)


# ============================================================== defects =====
def defects_report():
    a = Tsv(M.out_path("assertions.tsv"))
    ctx = Tsv(M.out_path("fvol", "fvol_context.tsv"))
    cells = Tsv(M.out_path("decay", "decay_cells.tsv"))
    L = ["# PORT M1 Track B — SPEC DEFECTS AND DATA DEFECTS", "", HEADER]
    L.append("Reported, not improvised around (D-002/D-005). Each item names "
             "what the spec says, what was measured, and what the lane did.\n")

    L.append("## D1 — §2's phase-close decay denominator is degenerate (and "
             "sign-inverted)\n")
    rows = []
    for x in M.ASSET_ORDER:
        r, ln = cells.one(asset=x, rung="ALL", phase="ALL", era=M.ERA_FIT,
                          population="ALL", tau_sec="0")
        rows.append([x, num(r, cells, "mean_v_close_0", "$%.2f"),
                     num(r, cells, "mean_v_peak_0", "$%.2f"), cite(cells, ln)])
    L.append(md_table(["asset", "mean phase-close cert (tau=0)",
                       "mean peak-exit cert (tau=0)", "source"], rows))
    L.append("\n§2 pins tau* on \"pooled-FIT mean value decay < 1.5%\" of the "
             "phase-close certificate. Pooled over all confirmations that "
             "certificate averages a small NEGATIVE number, so a 1.5% relative "
             "test is inverted. LANE ACTION: rule applied to every reading §2 "
             "admits; the pin uses the only unselected, non-degenerate one "
             "(peak-exit). Same tau* (120s) on all three assets. Detail in "
             "DECAY_REPORT.md.\n")

    L.append("## D2 — §4(f)'s round-number constants fail §4(f)'s own "
             "assertion\n")
    rows = []
    for r, ln in a.find(assertion="ROUND_GRID_BAND"):
        rows.append([r[a.i("asset")], r[a.i("subject")],
                     num(r, a, "value_a", "%.4f"),
                     num(r, a, "value_b", "%.3f") + "%",
                     "IN BAND" if r[a.i("ok")] == "1" else "**OUT OF BAND**",
                     cite(a, ln)])
    L.append(md_table(["asset", "grid", "2024 median price", "% of price",
                       "verdict", "source"], rows))
    L.append("\n§4(f): \"round numbers: 1-2-5 grid nearest ~0.3-1% of price "
             "(SI: $0.25/$0.50/$1.00; HG: $0.05/$0.10; NKD: 100/250/500) — "
             "constants asserted against that %-band at 2024 median prices, "
             "else spec defect.\" Only 2 of the 8 pinned constants are inside "
             "the band; HG has none. LANE ACTION: the pinned constants are "
             "implemented as written and the assertion result is reported. "
             "(The §6b census then finds ROUND has no mechanism anyway: lift "
             "0.80-1.08.)\n")

    L.append("## D3 — §6's G3 statistic cannot be per-second\n")
    rows = []
    for r, ln in a.find(assertion="G3_MAD_DEGENERACY"):
        rows.append([r[a.i("asset")], r[a.i("subject")],
                     "%s/%s" % (r[a.i("value_a")], r[a.i("band_lo")]),
                     "%s/%s" % (r[a.i("value_b")], r[a.i("band_lo")]),
                     cite(a, ln)])
    L.append(md_table(["asset", "probe session",
                       "half-hour bins with MAD=0, PER-SECOND",
                       "same, 60s window", "source"], rows))
    L.append("\n§6 says \"per second, trade-count and |signed-flow(60s)| "
             "z-scores vs clock-norm (trailing-60-session same-half-hour "
             "median/MAD)\". A per-second trade count has MAD exactly 0 in "
             "45-48 of 48 half-hour bins, so the z-score is undefined almost "
             "everywhere. LANE ACTION: RATE uses the same 60s window as FLOW "
             "(2-4/48 degenerate); the residual MAD=0 case is floored at half "
             "a trade / one contract. §6 states no MAD=0 rule either.\n")

    L.append("## D4 — §6's G2-RECLAIM has no time bound\n")
    L.append("§6: \"mid BREAKS the level by > tol, stays beyond for >= 60s, "
             "then re-crosses back and holds >= 120s\". No window is given for "
             "\"then\". Implemented as written (searched to session close) and "
             "measured on SI: of 7,142 breaks in a 100-session block, 5,845 "
             "eventually reclaim, with elapsed break->reclaim median 733s, p90 "
             "6,220s, max 55,070s (15.3 hours), and only 55.8% inside the "
             "15-minute window §6 uses for REJECT. A 15-hour \"reclaim\" is not "
             "a level reclaim. LANE ACTION: implemented unbounded, both "
             "`break_sec` and `reclaim_sec` stored per touch so M1.B can pin a "
             "bound without a rebuild.\n")

    L.append("## D5 — §4(c) names four phases; the frozen table has three\n")
    L.append("§4(c) asks for per-phase H/L over \"(overnight-before-open, "
             "TOKYO, LONDON, NY)\", but the FROZEN m0 phase table "
             "(`artifacts/cache/port/m0/phases_{ASSET}.json`) partitions the "
             "session into three phases only, and its TOKYO tag already "
             "absorbs the Globex evening. LANE ACTION: OVERNIGHT is built as "
             "an ADDITIONAL segment (not a fourth partition member) = session "
             "seconds before the committed RTH-open constant "
             "`RTH_LO_SEC = 52200`, i.e. the classic overnight-high/low object. "
             "No new constant was invented.\n")

    L.append("## D6 — §4(f) gives no window for the round-number grid\n")
    L.append("A 1-2-5 grid is infinite; §4(f) never says how far from price to "
             "generate. LANE ACTION: grid points within +-2.0 x sigma_hat "
             "(session) of the prior settle — the same width as §4(a)'s widest "
             "band, so the bound is a spec constant rather than a new one. "
             "Declared in the level receipt params.\n")

    L.append("## D7 — the §6 retirement rule's first clause is saturated\n")
    L.append("Detail and evidence in GEN_CENSUS_REPORT.md: every family "
             "including G1 scores $0.00/day exclusive DP add, because ~600 "
             "candidates/day compete for the 3 seats a one-position DP can "
             "fill. The clause cannot discriminate. Reported, applied as "
             "written.\n")

    L.append("## D8 — DATA DEFECT: weekly stale-book receipts in the m0 "
             "substrate\n")
    L.append("One receipt per week per asset (Sunday-dated) carries thousands "
             "of two-sided seconds at a frozen quote: traded range exactly $0. "
             "231 of 1,417 SI session receipts; 787 of 4,521 across the three "
             "assets. They are not sessions. Left in they emptied the LONDON "
             "and TOKYO HAR models entirely and would have supplied flat "
             "prior-day/N-day levels. LANE ACTION: excluded from the vol "
             "history, the ledger's prior-session lookups and the ledger "
             "build (3,734 session ledgers built). The m0 censuses already "
             "excluded them by other means (SI 1,174 census sessions vs 1,417 "
             "receipts), so this is an undocumented m0 property, not a "
             "divergence.\n")

    L.append("## D9 — DATA GAP: NKD's named context series does not cover the "
             "FIT era\n")
    rows = []
    for r, ln in zip(ctx.rows, ctx.lines):
        rows.append([r[ctx.i("asset")], r[ctx.i("context_series")],
                     num(r, ctx, "coverage", "%.3f"),
                     r[ctx.i("series_first_date")],
                     num(r, ctx, "corr_log_ctx_vs_log_range", "%.3f"),
                     r[ctx.i("used_in_model")], cite(ctx, ln)])
    L.append(md_table(["asset", "series", "coverage", "first date",
                       "corr(log,log)", "used", "source"], rows))
    L.append("\n§3 names the Nikkei VI close as NKD's context regressor; the "
             "owned history starts 2023-01-04 (60% coverage). LANE ACTION: "
             "dropped from the NKD model and reported. Worth buying: it is the "
             "stronger of the two context series where it exists (0.57 vs "
             "GVZ's 0.45).\n")

    L.append("## D10 — §1.3/§7-A's session count (already adjudicated)\n")
    L.append("Both say the C++ differential runs over \"3,942\" m0 session "
             "receipts; the true count is **4,521** (SI 1,417 + HG 1,551 + NKD "
             "1,553). Track B found this independently while sizing its scan; "
             "CC-M1-2(2) had already corrected the record from Lane A "
             "(JOURNAL 2026-08-13 09:35Z). Listed only so the two lanes' "
             "findings are on the same page. Track B built 3,734 session "
             "ledgers from those 4,521 receipts — the difference is D8.\n")

    L.append("## D11 — §2's MAE is not named\n")
    L.append("\"value/MAE certificates\" admits both the m0 §8 "
             "MAE-before-peak and the realised hold MAE. LANE ACTION: both "
             "computed, the pin rule evaluated on both, and both emitted "
             "(`mae_peak_inflation`, `mae_hold_inflation`). They agree: tau* = "
             "120s either way.\n")

    L.append("## D12 — the task brief cites §4 sources (a)-(g); §4 lists "
             "(a)-(f)\n")
    L.append("All six §4 sources are built, plus the CC-M1-1(A) ladders. No "
             "seventh source exists in the frozen spec.\n")
    return "\n".join(L)


def main():
    M.verify_spec()
    out = [(M.out_path("SPEC_DEFECTS.md"), defects_report()),
           (M.out_path("decay", "DECAY_REPORT.md"), decay_report()),
           (M.out_path("fvol", "FVOL_REPORT.md"), fvol_report()),
           (M.out_path("levels", "LEDGER_PROFILE_REPORT.md"), build_report()),
           (M.out_path("generation", "GEN_CENSUS_REPORT.md"), gen_report()),
           (M.out_path("generation", "LEVEL_RELEVANCE_REPORT.md"),
            relevance_report())]
    for path, text in out:
        with open(path, "w") as fh:
            fh.write(text + "\n")
        print("wrote %s (%d bytes)" % (path, len(text)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
