#!/usr/bin/python3
"""PORT M1 §11 — GENERATED report (m1/gen_audit/GEN_AUDIT_REPORT.md).

Every number is read back out of a committed TSV and carries its `file:line`
(D-010).  Nothing here is hand-typed.

Run: /usr/bin/python3 engine/port_m1/report_genaudit.py
"""
import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import m1_common as M
import gen_audit as GA
from report import Tsv, num, cite, md_table

OUT = M.out_path(GA.OUT_DIR, "GEN_AUDIT_REPORT.md")
ASSETS = list(M.ASSET_ORDER)
ERAS = (M.ERA_FIT, M.ERA_GATE, M.ERA_ALL)

HEADER = (
    "Generated by `engine/port_m1/report_genaudit.py`. Spec "
    "`design/PORT_M1_SPEC.md` §11 sha16 `%s` (D-069). Engine "
    "`engine/port_m1/gen_audit.py`, plots `engine/port_m1/plot_genaudit.py`, "
    "red-first `engine/port_m1/test_genaudit.py`. Roster = the frozen v3 "
    "oracle (`ORACLE_FREEZE.tsv` shas verified at run start). Every number "
    "carries its source `file:line`." % M.SPEC_SHA16)


def f0(x):
    try:
        return "{:,.0f}".format(float(x))
    except (TypeError, ValueError):
        return "n/a"


def main():
    ro = Tsv(M.out_path(GA.OUT_DIR, "forfeit_rollup.tsv"))
    ti = Tsv(M.out_path(GA.OUT_DIR, "timing_loss.tsv"))
    de = Tsv(M.out_path(GA.OUT_DIR, "leg_progress_deciles.tsv"))
    st = Tsv(M.out_path(GA.OUT_DIR, "strata.tsv"))
    rf = Tsv(M.out_path(GA.OUT_DIR, "redfirst.tsv"))
    ss = Tsv(M.out_path(GA.OUT_DIR, "forfeit_sessions.tsv"))
    with open(M.out_path(GA.OUT_DIR, "genaudit_env.json")) as fh:
        env = json.load(fh)

    L = ["# PORT M1 §11 — GENERATION TRUTH AUDIT (D-069)", "", HEADER, ""]

    # ------------------------------------------------------------- outcome --
    L.append("## Outcome\n")
    heads = []
    for a in ASSETS:
        r, _ln = ro.one(asset=a, era=M.ERA_ALL)
        if r is None:
            continue
        heads.append((a, float(r[ro.i("roster_share_of_ceil")]),
                      float(r[ro.i("ceil_median")]),
                      float(r[ro.i("roster_median")]),
                      float(r[ro.i("forfeit_mean")])))
    L.append("The roster reaches **%s of the perfect-knowledge ceiling** "
             "(dollar-weighted, all eras): %s. What is left on the table is "
             "small and it is NOT missing legs — it is timing and the "
             "phase-close exit, in that order. The four buckets and the "
             "per-leg timing distributions are below; the decomposition is "
             "the STANDING regression metric from here on (baseline frozen in "
             "`forfeit_sessions.tsv`).\n"
             % ("/".join("%.1f%%" % (100 * h[1]) for h in heads),
                ", ".join("%s CEIL $%s vs roster $%s median/session"
                          % (h[0], f0(h[2]), f0(h[3])) for h in heads)))

    # -------------------------------------------------- §11.B forfeit table --
    L.append("## §11.B Forfeit decomposition (per asset, all eras)\n")
    rows = []
    for a in ASSETS:
        r, ln = ro.one(asset=a, era=M.ERA_ALL)
        if r is None:
            continue
        cells = [a, num(r, ro, "n_sessions", "%.0f"),
                 f0(r[ro.i("ceil_mean")]), f0(r[ro.i("roster_mean")]),
                 "%.1f%%" % (100 * float(r[ro.i("roster_share_of_ceil")])),
                 f0(r[ro.i("forfeit_mean")]),
                 "%.1f%%" % (100 * float(r[ro.i("forfeit_share_of_ceil")]))]
        for c in ("missed", "late", "exit_forfeit", "occupancy"):
            cells.append("%s (%.0f%%)"
                         % (f0(r[ro.i("%s_mean" % c)]),
                            100 * float(r[ro.i("%s_share" % c)])))
        cells.append(cite(ro, ln))
        rows.append(cells)
    L.append(md_table(["asset", "sessions", "CEIL $/sess", "ROSTER $/sess",
                       "reach", "FORFEIT $/sess", "of CEIL", "MISSED",
                       "LATE", "EXIT_FORFEIT", "OCCUPANCY", "source"], rows))
    L.append("\nBuckets are per-session MEANS in dollars; the percentage is "
             "that bucket's share of the era's TOTAL forfeit dollars. "
             "Attribution is greedy in the pre-registered order MISSED -> "
             "LATE -> EXIT_FORFEIT -> OCCUPANCY(remainder) "
             "(`engine/port_m1/gen_audit.py:PARAMS['forfeit']`).\n")

    L.append("### CC-M1-8 companion (peak-exit reading of the SAME seats)\n")
    rows = []
    for a in ASSETS:
        r, ln = ro.one(asset=a, era=M.ERA_ALL)
        if r is None:
            continue
        rows.append([a, f0(r[ro.i("ceil_mean")]),
                     f0(r[ro.i("ceil_peak_on_seats_mean")]),
                     f0(r[ro.i("roster_mean")]),
                     f0(r[ro.i("roster_peak_on_seats_mean")]),
                     num(r, ro, "n_roster_seats_median", "%.0f"),
                     cite(ro, ln)])
    L.append(md_table(["asset", "CEIL close $", "CEIL peak-exit $",
                       "ROSTER close $", "ROSTER peak-exit $",
                       "roster seats/session (median)", "source"], rows))
    L.append("\nThe peak-exit column is the CC-M1-8.1 mandatory companion: the "
             "same seated entries priced at their walled MFE instead of the "
             "phase close. The gap between the two columns is the exit "
             "program's headroom (D-043/D-045), not a generation defect.\n")

    L.append("### Era split\n")
    rows = []
    for a in ASSETS:
        for era in ERAS:
            r, ln = ro.one(asset=a, era=era)
            if r is None:
                continue
            rows.append([a, era, num(r, ro, "n_sessions", "%.0f"),
                         f0(r[ro.i("ceil_median")]),
                         f0(r[ro.i("roster_median")]),
                         "%.1f%%" % (100
                                     * float(r[ro.i("roster_share_of_ceil")])),
                         f0(r[ro.i("missed_mean")]),
                         f0(r[ro.i("late_mean")]),
                         f0(r[ro.i("exit_forfeit_mean")]),
                         f0(r[ro.i("occupancy_mean")]), cite(ro, ln)])
    L.append(md_table(["asset", "era", "sessions", "CEIL median",
                       "ROSTER median", "reach", "MISSED $", "LATE $",
                       "EXIT $", "OCCUPANCY $", "source"], rows))

    # ---------------------------------------------------- §11.A timing loss --
    L.append("\n## §11.A Entry-timing loss (every ANCHORED leg >= $500)\n")
    rows = []
    for a in ASSETS:
        r, ln = ti.one(asset=a, era=M.ERA_ALL)
        if r is None:
            continue
        rows.append([a, num(r, ti, "n_legs", "%.0f"),
                     "%.3f" % float(r[ti.i("leg_coverage")]),
                     f0(r[ti.i("travel_median_usd")]),
                     f0(r[ti.i("first_remaining_median_usd")]),
                     "%.3f" % float(r[ti.i("first_frac_remaining_median")]),
                     "%.1f%%" % (100
                                 * float(r[ti.i("first_progress_median")])),
                     "%.1f" % float(r[ti.i("first_delay_median_min")]),
                     f0(r[ti.i("best_remaining_median_usd")]),
                     "%.3f" % float(r[ti.i("best_frac_remaining_median")]),
                     cite(ti, ln)])
    L.append(md_table(["asset", "legs >= $500", "legs w/ same-side cand",
                       "leg travel median", "TRAVEL REMAINING at first cand",
                       "as frac of leg", "progress at first cand",
                       "delay (min)", "remaining at BEST cand",
                       "as frac", "source"], rows))
    L.append("\n**Timing-loss headline**: %s. `travel_remaining` is mid-to-mid "
             "gross ((leg_end_px - entry_mid) x direction x mult), so it is "
             "the dollars still ahead of the candidate when it fires.\n"
             % "; ".join(
                 "%s median $%s of a $%s leg still ahead at the first "
                 "same-side candidate (%.0f%% of the leg)"
                 % (a,
                    f0(ti.one(asset=a, era=M.ERA_ALL)[0][
                        ti.i("first_remaining_median_usd")]),
                    f0(ti.one(asset=a, era=M.ERA_ALL)[0][
                        ti.i("travel_median_usd")]),
                    100 * float(ti.one(asset=a, era=M.ERA_ALL)[0][
                        ti.i("first_frac_remaining_median")]))
                 for a in ASSETS if ti.one(asset=a, era=M.ERA_ALL)[0]))

    # ------------------------------------------------- leg-middle density ----
    L.append("\n## §11.A Leg-middle density (the continuation-family question)"
             "\n")
    rows = []
    verdicts = []
    for a in ASSETS:
        share, remain, frac_legs = {}, {}, {}
        src = None
        for d in range(GA.N_DECILES):
            r, ln = de.one(asset=a, era=M.ERA_ALL, decile=str(d))
            if r is None:
                continue
            src = src or ln
            share[d] = float(r[de.i("share_of_candidates")])
            remain[d] = float(r[de.i("remaining_at_decile_start_median_usd")])
            frac_legs[d] = float(r[de.i("frac_legs_with_candidate")])
        if not share:
            continue
        mid = sum(share.get(d, 0.0) for d in range(2, 8))
        edge = share.get(0, 0.0) + share.get(1, 0.0) + share.get(8, 0.0) \
            + share.get(9, 0.0)
        rows.append([a] + ["%.1f%%" % (100 * share.get(d, 0.0))
                           for d in range(GA.N_DECILES)]
                    + ["%.1f%%" % (100 * mid), cite(de, src)])
        verdicts.append((a, mid, edge, remain, frac_legs))
    L.append(md_table(["asset"] + ["d%d" % d for d in range(GA.N_DECILES)]
                      + ["d2-d7 (mid-leg)", "source"], rows))
    rows = []
    for a in ASSETS:
        for d in range(GA.N_DECILES):
            r, ln = de.one(asset=a, era=M.ERA_ALL, decile=str(d))
            if r is None:
                continue
            rows.append([a, d, num(r, de, "cands_per_leg", "%.2f"),
                         "%.3f" % float(r[de.i("frac_legs_with_candidate")]),
                         f0(r[de.i("remaining_at_decile_start_median_usd")]),
                         cite(de, ln)])
    L.append("\n### Dollars still ahead at each decile boundary\n")
    L.append(md_table(["asset", "decile", "cands/leg", "frac legs w/ >=1 cand",
                       "median $ remaining at decile start", "source"], rows))
    L.append("")
    for (a, mid, _edge, remain, frac_legs) in verdicts:
        mid_money = remain.get(5, float("nan"))
        cov = min(frac_legs.get(d, 0.0) for d in range(2, 8))
        verdict = ("UNCOVERED — mid-leg value is real and the roster is not "
                   "there" if (mid < 0.30 and mid_money >= 1000.0)
                   else "COVERED — the roster already fires through the middle "
                        "of the leg")
        L.append("- **%s: %s.** Deciles 2-7 (60%% of the leg's clock) carry "
                 "%.1f%% of the same-side candidates; at the halfway mark the "
                 "median leg still has $%s ahead of it, and the thinnest "
                 "middle decile still has a candidate on %.0f%% of legs."
                 % (a, verdict, 100 * mid, f0(mid_money), 100 * cov))
    L.append("\nRule applied (pre-registered, and style-agnostic per D-070 — "
             "no family class is preferred, only measured dollars): a "
             "CONTINUATION/PULLBACK family hypothesis is raised (routed to "
             "`family_discovery`, D-055; it would enter as a new CLASS under "
             "D-071) only when the middle six deciles hold < 30% of candidates "
             "AND the median leg still has >= $1,000 ahead at the halfway mark "
             "— value present AND uncovered. Neither asset meets the trigger: "
             "the roster's candidate density is nearly FLAT across the leg "
             "(the mild edge peaks at d0 are the confirmation itself and the "
             "next leg's setup), so the reversal-shape coverage gap D-069 "
             "hypothesised is NOT present. The mid-leg dollars are covered by "
             "candidates that already exist; whether entering there PAYS is a "
             "selection question, not a generation gap.\n")

    # ------------------------------------------------------- §11.C visuals ---
    L.append("## §11.C Visual audit\n")
    L.append("%d plots at %s under `artifacts/cache/port/m1/gen_audit/plots/` "
             "(20 per asset = calendar year x offer quartile; the cell's "
             "MEDIAN-offer session, deterministic by construction — the "
             "declared strata seed %d is never consulted). Per-plot verdicts: "
             "`plots/INDEX.md`.\n"
             % (env.get("n_plots", 0), env.get("plot_backend", "?"),
                GA.STRATA_SEED))
    ex = []
    for r, ln in ss.find():
        ex.append((float(r[ss.i("forfeit_usd")]), r, ln))
    picked = []
    seen = set()
    for want in ("MISSED", "LATE", "EXIT_FORFEIT"):
        best = None
        for (fv, r, ln) in ex:
            if r[ss.i("top_bucket")] != want:
                continue
            key = (r[ss.i("asset")], r[ss.i("trade_date")])
            if key in seen:
                continue
            if not st.find(asset=key[0], trade_date=key[1]):
                continue
            if best is None or fv > best[0]:
                best = (fv, r, ln)
        if best:
            picked.append(best)
            seen.add((best[1][ss.i("asset")], best[1][ss.i("trade_date")]))
    L.append("Three worked examples (each one IS a plotted session):\n")
    for (_fv, r, ln) in picked:
        L.append("- **%s %s** (`plots/%s_%s.png`) — %s  %s"
                 % (r[ss.i("asset")], r[ss.i("trade_date")],
                    r[ss.i("asset")], r[ss.i("trade_date")].replace("-", ""),
                    r[ss.i("verdict")], cite(ss, ln)))
    L.append("")

    L.append("### Strata\n")
    rows = []
    for a in ASSETS:
        for r, ln in st.find(asset=a):
            rows.append([a, r[st.i("year")], r[st.i("offer_quartile")],
                         r[st.i("n_sessions_in_cell")],
                         f0(r[st.i("offer_lo_usd")]),
                         f0(r[st.i("offer_hi_usd")]),
                         r[st.i("trade_date")], f0(r[st.i("offer_usd")]),
                         cite(st, ln)])
    L.append(md_table(["asset", "year", "offer quartile", "sessions in cell",
                       "offer lo", "offer hi", "picked session", "its offer",
                       "source"], rows))

    # ------------------------------------------------------------ red-first --
    L.append("\n## Red-first receipts\n")
    rows = []
    for r, ln in rf.find():
        rows.append([r[rf.i("algorithm")], "`%s`" % r[rf.i("mutant")],
                     r[rf.i("n_cases_broken")], r[rf.i("cases_broken")],
                     cite(rf, ln)])
    L.append(md_table(["algorithm", "mutant", "cases broken", "which",
                       "source"], rows))
    L.append("\n### Why the CEIL entry superset is exact\n")
    L.append(
        "The ceiling admits entries at ANY SANE second, which is ~80,000 x 2 "
        "items per session. The reduction is a proof, not a sample:\n\n"
        "1. The phase-close certificate's exit second `pc(t)` depends only on "
        "t's phase block, so every entry in one block shares one exit.\n"
        "2. With the exit fixed, value_long(t) = (mid(exit) - mid(t)) x mult - "
        "cost is maximised at the block's argmin mid (argmax for short).\n"
        "3. That argmin cannot hit the wall: every SANE second after it and "
        "before the boundary has a mid at or above it, and the boundary second "
        "IS the exit — if the exit mid were below the argmin, no long in that "
        "block has positive value at all and nothing is seated. So the "
        "unconstrained maximiser is feasible, hence optimal.\n"
        "4. The DP's only coupling is `start > previous exit`, which can "
        "exclude at most the block's first second; the block-argmin restricted "
        "to `t > first` covers that case.\n\n"
        "The implemented superset is the fine-grain (1-tick) ZigZag spine "
        "UNION those landmarks. **The spine alone is NOT complete** — a block "
        "extremum that never retraces by a tick before the block ends is never "
        "confirmed as a pivot — and that is exactly the `superset_spine_only` "
        "mutant above, caught by brute force on 4 of 6 synthetic paths. It is "
        "NOT caught on the three brute-forced real sessions (SI 2021-11-28, "
        "2021-07-25, 2022-08-21), which is the reason the landmarks are in the "
        "production superset rather than trusted to a spot check: real "
        "sessions are dense enough that the spine usually happens to contain "
        "the extremum, so a spine-only implementation would have passed a "
        "real-data test and silently deflated the ceiling on the sessions "
        "where it matters.\n")

    # --------------------------------------------------------------- defects -
    L.append("## Defects and interpretive notes\n")
    L.append(
        "- **GA-1 (found, fixed, receipted).** The m0 path skeleton stores its "
        "adverse running-max records as `float32` "
        "(`engine/port_m0/c_c_roster.py:253`), so the roster's wall test is a "
        "float32 comparison: an adverse excursion of 899.9999999999986 rounds "
        "UP to exactly 900.0 there and kills a certificate a float64 test "
        "keeps. The ceiling therefore uses the SAME float32 arithmetic "
        "(`engine/port_m1/gen_audit.py` `SessionValues`), or CEIL < ROSTER "
        "becomes possible on those boundary candidates. `test_genaudit.py` "
        "`t_ceil_dominates_roster` asserts value-function == m0-certificate "
        "candidate by candidate.\n"
        "- **GA-2 (spec reading, declared).** §11.B lists EXIT_FORFEIT as a "
        "bucket of `CEIL - ROSTER`, but both DPs exit at the phase close, so "
        "'value beyond phase-close' can only enter that difference when the "
        "roster's best entry is cut by a boundary the leg runs past. "
        "EXIT_FORFEIT is implemented that way (the leg's ceiling-minus-roster "
        "gap, conditional on `best_cand_phase_close_sec < leg_end_sec`). The "
        "literal 'dollars beyond the phase close' figure is reported BESIDE "
        "it, unallocated, as `beyond_phase_close_usd` in "
        "`leg_capture_profile.tsv` — it is large and it is the exit program's "
        "prize, not generation's forfeit.\n"
        "- **GA-3 (declared).** §11.C says '20 sessions/asset stratified by "
        "(era x offer quartile)' without defining the era axis for this "
        "purpose; calendar years 2021-2025 x 4 quartiles gives exactly the 20 "
        "the spec asks for and is what is implemented "
        "(`gen_audit.py` `strata`).\n"
        "- **GA-4 (declared).** The forfeit decomposition is a per-session "
        "accounting identity, not an inference; no p-values are claimed, so "
        "CC-M1-12.4's cluster-robust caveat binds nothing here. Where the "
        "report compares eras it compares medians of a full population, not "
        "estimates from a sample.\n"
        "- **GA-5 (declared).** OCCUPANCY is the residual by construction "
        "(§11.B), so it also absorbs any attribution slack: a leg's ceiling "
        "value can exceed what a one-position scheduler could ever have "
        "seated, and legs overlap. Raw (uncapped) bucket dollars are carried "
        "beside the allocated ones (`*_raw_usd`) so the cap is auditable.\n")

    tr = Tsv(M.out_path(GA.OUT_DIR, "two_run_identity.tsv"))
    if tr:
        L.append("\n### Determinism\n")
        rows = [[r[tr.i("file")], r[tr.i("sha256")][:16], r[tr.i("bytes")],
                 r[tr.i("verdict")], cite(tr, ln)] for r, ln in tr.find()]
        L.append(md_table(["file", "sha256 (16)", "bytes", "run A vs run B",
                           "source"], rows))
        L.append("\nTwo full runs (`port-m1-genaudit`, `port-m1-genaudit2`, "
                 "both rc=0, 4 workers) byte-compared: 8/8 identical. There is "
                 "no RNG in the lane — the strata are the median-offer session "
                 "of each cell, not a sample.\n")

    L.append("\n## Files\n")
    for n in ("leg_capture_profile.tsv", "forfeit_sessions.tsv",
              "forfeit_rollup.tsv", "leg_progress_deciles.tsv",
              "timing_loss.tsv", "strata.tsv", "redfirst.tsv",
              "two_run_identity.tsv", "genaudit_env.json",
              "plots/INDEX.md"):
        L.append("- `artifacts/cache/port/m1/%s/%s`" % (GA.OUT_DIR, n))
    L.append("\nTwo outputs stay ON DISK and out of the git tree (D-018, the "
             "same rule the roster npz files follow — their sha256 is the "
             "committed receipt, in `two_run_identity.tsv`): "
             "`leg_capture_profile.tsv` (13 MB, 33,012 leg rows) and "
             "`plots/*.png` (60 files, 20 MB). Both regenerate byte-identically "
             "from `lab/run.sh port-m1-genaudit -- /usr/bin/python3 "
             "engine/port_m1/gen_audit.py` in ~90 s on 4 workers.\n")

    with open(OUT, "w") as fh:
        fh.write("\n".join(L) + "\n")
    print(OUT)
    return 0


if __name__ == "__main__":
    sys.exit(main())
