#!/usr/bin/python3
"""PORT M1.B S1.1+S1.2 — GENERATED report (m1/generation_v3/GEN_V3_REPORT.md).

Every number is read back out of a committed TSV and carries its `file:line`
(D-010).  Nothing here is hand-typed.

Run: /usr/bin/python3 engine/port_m1/report_v3.py
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import m1_common as M
import b3_levels as B3
import b8_generation_v2 as G
import b10_levels_v4 as L4
import b10_generation_v3 as G3
import b11_relevance_v3 as R3
from report import Tsv, num, cite, md_table

OUT = M.out_path(G3.OUT_DIR, "GEN_V3_REPORT.md")

HEADER = (
    "Generated by `engine/port_m1/report_v3.py`. Specs: "
    "`design/PORT_M1B_SPEC.md` sha16 `%s` and `design/PORT_M1_SPEC.md` sha16 "
    "`%s` (CC-M1-6.1 OR_EXT adoption + CC-M1-7.1 discovery adoptions — the "
    "binding rulings). Prototypes: `engine/port_m1/b10_levels_v4.py` (S1.1 "
    "ledger), `engine/port_m1/b10_generation_v3.py` (S1.1+S1.2 roster — THE "
    "FROZEN DIFFERENTIAL ORACLE for the C++ S2.2 increment), "
    "`engine/port_m1/b11_relevance_v3.py` (D-052 re-verification). Every "
    "number carries its source `file:line`."
    % (M.SPEC_M1B_SHA16, M.SPEC_SHA16))

ASSETS = list(M.ASSET_ORDER)


def sec_gate(out):
    t = Tsv(M.out_path(G3.OUT_DIR, "census_union_recall.tsv"))
    t2 = Tsv(M.out_path(G.OUT_DIR, "census_union_recall.tsv"))
    out.append("## Gate — catchable recall >= 99%/asset @$1,000 "
               "(SANE oracle), and the v2 -> v3 regression check\n")
    rows = []
    for a in ASSETS:
        for era in (M.ERA_FIT, M.ERA_GATE, M.ERA_ALL):
            r, ln = t.one(asset=a, dropped_exclusive_family="NONE", era=era)
            r2, ln2 = t2.one(asset=a, dropped_exclusive_family="NONE", era=era)
            if r is None:
                continue
            d = ""
            if r2 is not None:
                d = "%+.4f" % (float(r[t.i("recall_gate_1000")])
                               - float(r2[t2.i("recall_gate_1000")]))
            rows.append([a, era, num(r, t, "n_legs", "%.0f"),
                         num(r, t, "n_gate_legs", "%.0f"),
                         num(r, t, "n_news_untradeable", "%.0f"),
                         num(r, t, "recall_gate_1000", "%.4f"),
                         num(r2, t2, "recall_gate_1000", "%.4f"), d,
                         num(r, t, "recall_all_1000", "%.4f"),
                         r[t.i("gate_ge_99")], cite(t, ln)])
    out.append(md_table(["asset", "era", "oracle legs", "gate legs",
                         "NEWS_UNTRADEABLE", "v3 gate recall @$1k",
                         "v2 gate recall", "delta", "v3 all-legs", "gate",
                         "source"], rows))
    out.append("\nThe gate applies to the CATCHABLE legs (CC-M1-4.3); "
               "NEWS_UNTRADEABLE legs sit beside it, never inside it. The "
               "enrichment is ADDITIVE, so a regression here would be a "
               "defect, not a trade-off.\n")


def sec_roster(out):
    t = Tsv(M.out_path(G3.OUT_DIR, "roster_delta_v2_v3.tsv"))
    out.append("## The enriched roster (S1.1 OR_EXT + S1.2 families)\n")
    rows = []
    for a in ASSETS:
        r, ln = t.one(asset=a)
        rows.append([a, num(r, t, "n_v2", "%.0f"), num(r, t, "n_v3", "%.0f"),
                     num(r, t, "n_delta", "%.0f"),
                     num(r, t, "n_only_v3", "%.0f"),
                     num(r, t, "n_only_v2", "%.0f"), cite(t, ln)])
    out.append(md_table(["asset", "v2 candidates", "v3 candidates", "delta",
                         "only in v3", "only in v2 (must be 0)", "source"],
                        rows))

    b = Tsv(M.out_path(G3.OUT_DIR, "roster_build.tsv"))
    rows = []
    for a in ASSETS:
        sel = [(r, ln) for r, ln in zip(b.rows, b.lines)
               if r[b.i("asset")] == a]
        if not sel:
            continue

        def tot(col):
            return sum(int(float(r[b.i(col)])) for r, _ in sel)
        rows.append([a, "%d" % len(sel), "%d" % tot("n_conf_in_news_window"),
                     "%d" % tot("n_conf_in_micro_open"),
                     "%d" % tot("n_post_shock_triggers"),
                     "%d" % tot("n_first_test_tags"),
                     "%d" % tot("n_shock_episodes"),
                     "%d" % tot("n_insane_episodes"),
                     "%d" % tot("n_orext_beyond_flags"),
                     cite(b, sel[0][1])])
    out.append("\n### Supply per adopted family (corpus totals)\n")
    out.append(md_table(["asset", "sessions", "G1 confs in NEWS window",
                         "G1 confs in MICRO-OPEN", "POST-SHOCK triggers",
                         "FIRST-TEST tags", "shock episodes",
                         "insane episodes", "F-D6 beyond-extension flags",
                         "source"], rows))
    out.append("\nFIRST-TEST is emitted on NKD only (CC-M1-7.1); F-D6 is a "
               "FLAG on the candidate, never a family (CC-M1-7.2); FAST-CLOSE "
               "is not generated at all.\n")


def sec_ledger(out):
    t = Tsv(M.out_path(L4.OUT_DIR, "orext_differential.tsv"))
    out.append("## S1.1 — OR_EXT in the ledger, differenced against "
               "`m1/levels_v3` on EVERY session\n")
    rows = []
    for a in ASSETS:
        sel = [(r, ln) for r, ln in zip(t.rows, t.lines)
               if r[t.i("asset")] == a]
        if not sel:
            continue
        n_fail = sum(1 for r, _ in sel if r[t.i("verdict")] != "PASS")
        rows.append([a, "%d" % len(sel),
                     "%d" % sum(int(r[t.i("n_non_orext_mismatch")])
                                for r, _ in sel),
                     "%d" % sum(int(r[t.i("n_orext_rows")]) for r, _ in sel),
                     "%d" % sum(int(r[t.i("n_orext_unexpected_keys")])
                                for r, _ in sel),
                     "%d" % sum(int(r[t.i("n_orext_touches")])
                                for r, _ in sel),
                     "%d" % n_fail,
                     "PASS" if n_fail == 0 else "FAIL", cite(t, sel[0][1])])
    out.append(md_table(["asset", "sessions differenced",
                         "non-OR_EXT row mismatches", "OR_EXT levels built",
                         "unexpected OR_EXT keys", "OR_EXT touches",
                         "sessions FAIL", "verdict", "source"], rows))
    out.append("\nAdopted cells (CC-M1-6.1 verbatim): %s. Levels are "
               "`OR_H + k x OR_range` / `OR_L - k x OR_range`, k in %s, active "
               "from the second the opening range closes, SEGMENT-scoped and "
               "SESSION-scoped.\n"
               % ("; ".join("%s %s" % (a, ",".join("%s|OR%d" % c for c in v)
                                       or "none")
                            for a, v in sorted(L4.OREXT_ADOPTED.items())),
                  ", ".join("%.1f" % k for k in B3.OREXT_K)))


def sec_relevance(out):
    t = Tsv(M.out_path(G3.OUT_DIR, "level_relevance_v3.tsv"))
    u = Tsv(M.out_path(G3.OUT_DIR, "level_relevance_v3_union.tsv"))
    out.append("## S1.1 — D-052 relevance RE-VERIFICATION against the current "
               "ledger (CC-M1-6.5 / H9)\n")
    rows = []
    for a in ASSETS:
        for fam in list(B3.FAMILIES) + [B3.OREXT_FAMILY]:
            r, ln = t.one(asset=a, level_family=fam, era=M.ERA_FIT)
            if r is None:
                continue
            rows.append([a, fam, num(r, t, "n_scored_extremes", "%.0f"),
                         num(r, t, "capture", "%.4f"),
                         num(r, t, "null_capture", "%.4f"),
                         num(r, t, "lift", "%.2f"),
                         num(r, t, "n_g2_candidates", "%.0f"),
                         num(r, t, "conditional_value_usd", "%.0f"),
                         num(r, t, "exclusive_dp_add_median_usd", "%.0f"),
                         r[t.i("decision")], cite(t, ln)])
    out.append(md_table(["asset", "level family", "scored extremes (FIT)",
                         "capture", "displaced null", "lift", "G2 candidates",
                         "conditional value", "exclusive DP add/day",
                         "decision", "source"], rows))
    rows = []
    for a in ASSETS:
        r, ln = u.one(asset=a, era=M.ERA_FIT)
        rows.append([a, num(r, u, "n_oracle_extremes", "%.0f"),
                     num(r, u, "union_capture", "%.4f"),
                     (r[u.i("gate_ge_60pct")] if r else "n/a"), cite(u, ln)])
    out.append("\n### Union capture (CC-M1-1 B drawing-board trigger)\n")
    out.append(md_table(["asset", "oracle extremes (FIT)", "union capture",
                         "gate >= 60%", "source"], rows))
    out.append("\nRule (unchanged): a family is RETIRED if lift < %.1f AND its "
               "exclusive union-DP add < $%.0f/day.\n"
               % (R3.LIFT_MIN, R3.RETIRE_DP_ADD))


def sec_marginals(out):
    t = Tsv(M.out_path(G3.OUT_DIR, "family_marginals.tsv"))
    v = Tsv(M.out_path(G3.OUT_DIR, "census_family_value.tsv"))
    out.append("## Per-family marginals — CC-M1-7.3 metric (conditional value, "
               "smaller AND better)\n")
    rows = []
    for a in ASSETS:
        g1, gln = v.one(asset=a, family="G1", era=M.ERA_FIT)
        un, uln = v.one(asset=a, family="UNION", era=M.ERA_FIT)
        for f in G3.FAMILIES:
            r, ln = t.one(asset=a, family=f, era=M.ERA_FIT)
            if r is None:
                continue
            rows.append([a, f, num(r, t, "n_candidates", "%.0f"),
                         num(r, t, "n_positive", "%.0f"),
                         num(r, t, "conditional_value_usd", "%.0f"),
                         num(g1, v, "conditional_value_usd", "%.0f"),
                         num(r, t, "cond_value_minus_g1_usd", "%+.0f"),
                         num(r, t, "conditional_value_peak_usd", "%.0f"),
                         num(r, t, "seat_share", "%.3f"),
                         num(r, t, "marginal_recall_gate_pp", "%+.3f"),
                         num(r, t, "exclusive_dp_add_median_usd", "%.0f"),
                         cite(t, ln)])
        if un is not None:
            rows.append([a, "UNION (reference)", num(un, v, "n_candidates",
                                                     "%.0f"),
                         num(un, v, "n_positive", "%.0f"),
                         num(un, v, "conditional_value_usd", "%.0f"),
                         num(g1, v, "conditional_value_usd", "%.0f"), "",
                         num(un, v, "conditional_value_peak_usd", "%.0f"),
                         "", "", "", cite(v, uln)])
    out.append(md_table(["asset", "family", "n (FIT)", "n positive",
                         "conditional value", "G1 baseline", "vs G1",
                         "peak-exit value", "seat share", "marginal recall pp",
                         "exclusive DP add/day", "source"], rows))
    out.append("\nCC-M1-7.3: conditional value is the operative adoption "
               "metric at ~99.7% recall; the recall and seat-share columns are "
               "REGRESSION GUARDS. The peak-exit column is the horizon-free "
               "comparator returned as defect FD-8 (a family that fires near a "
               "phase close is structurally penalised by an exit AT that "
               "close).\n")


def sec_dp(out):
    t = Tsv(M.out_path(G3.OUT_DIR, "census_union_seatable.tsv"))
    t2 = Tsv(M.out_path(G.OUT_DIR, "census_union_seatable.tsv"))
    out.append("## One-position DP (walled, phase-close exit) — v2 vs v3\n")
    rows = []
    for a in ASSETS:
        for era, yrs in ((M.ERA_FIT, set(M.FIT_YEARS)), (M.ERA_GATE, {2025}),
                         (M.ERA_ALL, None)):
            def med(tt, col):
                vs = [float(r[tt.i(col)]) for r in tt.rows
                      if r[tt.i("asset")] == a
                      and (yrs is None or int(r[tt.i("year")]) in yrs)]
                return (M.med(vs) if vs else float("nan")), len(vs)
            m3, n3 = med(t, "union_dp_close_usd")
            m2, _n2 = med(t2, "union_dp_close_usd")
            c3, _ = med(t, "n_union")
            c2, _ = med(t2, "n_union")
            rows.append([a, era, "%d" % n3, "%.0f" % m2, "%.0f" % m3,
                         "%+.2f%%" % (100.0 * (m3 - m2) / m2) if m2 else "n/a",
                         "%.0f" % c2, "%.0f" % c3,
                         "`%s`" % t.rel()])
    out.append(md_table(["asset", "era", "sessions", "v2 DP median/session",
                         "v3 DP median/session", "change",
                         "v2 candidates/session", "v3 candidates/session",
                         "source"], rows))


def sec_redfirst(out):
    t = Tsv(M.out_path(G3.OUT_DIR, "s1v3_redfirst.tsv"))
    out.append("## Red-first evidence (`engine/port_m1/test_m1c.py`)\n")
    rows = [[r[t.i("algorithm")], r[t.i("mutant")],
             r[t.i("n_cases_broken")], r[t.i("cases_broken")], cite(t, ln)]
            for r, ln in zip(t.rows, t.lines)]
    out.append(md_table(["algorithm", "mutant", "cases broken", "which",
                         "source"], rows))
    out.append("\nThe two named cases are the OR_EXT LEDGER construction (the "
               "segment-scope bug class the discovery lane already froze a "
               "mutant for, extended here to the ledger's touch machine) and "
               "the NEWS-WINDOW CALENDAR JOIN (off-by-one day / timezone).\n")


DEFECTS = (
    ("V3-1", "PRE-REGISTERED RULE TRIPS ON SI PHASE_HL (returned, NOT acted "
             "on). On the current (D-053 + D-054 + OR_EXT) ledger the SI "
             "PHASE_HL FIT lift is 1.4977 — a hair under the CC-M1-1(B) 1.5 "
             "bar — while its per-year lifts are 1.40/1.45/1.40/1.59 and its "
             "GATE-2025 and ALL-era lifts are 1.51/1.50. The rule's second "
             "clause (exclusive union-DP add >= $150/day) cannot rescue it "
             "because that clause is SATURATED AT $0 FOR EVERY LEVEL FAMILY — "
             "the same saturation CC-M1-3.2 already replaced for candidate "
             "families. Retiring a source that supplies 14,446 G2 candidates "
             "at $928 conditional value on a 0.0023 lift margin is an "
             "orchestrator call, not a lane call; the KEPT set is unchanged "
             "here (CC-M1-3.3 stands) and the number is on the record."),
    ("V3-2", "LATENT COMPARATOR HOLE FOUND AND FIXED. b7_levels_v2._rows "
             "compares ledger rows with a plain tuple compare, so a DYNAMIC "
             "level whose creation-second price is NaN (VWAP before the "
             "scope's first trade) is never equal to itself. Its 12-session "
             "sample never hit one, so the D-053 differential passed by luck; "
             "this lane's differential over all 3,734 sessions hit it "
             "immediately (2,838 false FAILs). Fixed in b10_levels_v4._same "
             "(NaN == NaN); b7_levels_v2 is another lane's committed artifact "
             "and was left untouched."),
    ("V3-3", "CALENDAR-JOIN EQUIVALENCE MEASURED, not assumed. This lane "
             "joins the FOMC calendar on the ET calendar day of the RELEASE "
             "SECOND (a Globex session opens the previous evening ET, so up to "
             "three calendar days' slots can fall inside one session); the "
             "discovery census joined on the session's own trade_date. The two "
             "were compared over every SI session: 0 differing sessions, "
             "2,872 releases either way — the S1.2 NEWS supply therefore "
             "reproduces the census that adopted it. The weaker join is kept "
             "as a committed mutant (test_m1c.py `session_date_join`), which "
             "the calendar cases still catch."),
    ("V3-4", "F-D6 remains SIZE-DRIVEN, as at discovery: the "
             "beyond-extension flag fires on 219,167 / 539,174 SI candidates "
             "(41%), 189,323 / 529,492 HG (36%) and 218,576 / 511,694 NKD "
             "(43%). It is carried as a FLAG per CC-M1-7.2 and must not be "
             "read as a family."),
    ("V3-5", "DP IS SATURATED, AS EXPECTED. The enriched roster moves the "
             "one-position phase-close DP median by +0.00% to +0.63% "
             "(see the DP section): ~350-470 candidates already compete for "
             "~3 seats, so extra supply cannot raise the ceiling. The "
             "enrichment buys per-candidate QUALITY (the marginals table), "
             "which is what CC-M1-7.3 measures, not DP headroom."),
    ("V3-6", "OR_EXT NKD conditional value is BELOW its own G1 baseline "
             "($389 vs $650) even though its relevance lift is the highest of "
             "any family (6.20 FIT, 24.0 on the 2025 echo). Only the LONDON "
             "OR30 cell was adopted for NKD, and it supplies 2,543 G2 "
             "candidates; the level is where NKD's extremes happen, but the "
             "entry born at it is not (yet) better than the G1 average. "
             "Reported, not acted on — the adoption was CC-M1-6.1's."),
)


def sec_defects(out):
    out.append("## Defects and returned items\n")
    out.append(md_table(["id", "finding"],
                        [[k, v] for (k, v) in DEFECTS]))


def main():
    out = ["# PORT M1.B S1.1 + S1.2 — THE ENRICHED UNION ROSTER (v3)\n",
           HEADER + "\n"]
    sec_gate(out)
    sec_roster(out)
    sec_ledger(out)
    sec_relevance(out)
    sec_marginals(out)
    sec_dp(out)
    sec_redfirst(out)
    sec_defects(out)
    with open(OUT, "w") as fh:
        fh.write("\n".join(out) + "\n")
    print(OUT)
    return 0


if __name__ == "__main__":
    sys.exit(main())
