#!/usr/bin/env python3
"""Generate the committed numpy-parity literals for the WP11 PCG64 port.

SPEC: FINAL_PLAN.md section 11 null battery via the WP11 brief —
  "seeded coin sides via PCG64 SeedSequence(20260810, sid, side_index) —
   implement a deterministic PCG64+SeedSequence port matching numpy semantics
   with a literal cross-check fixture generated by python numpy, committed."

The C++ port in qr_replay/src/pcg64.cpp must reproduce every number this script
writes.  Nothing in the test suite may derive these literals from the port
itself: they come from numpy, once, and are committed as data.

Run:  python3 engine/cpp/tests/fixtures/make_pcg64_parity.py
Out:  engine/cpp/tests/fixtures/replay/pcg64_numpy_parity.tsv  (byte identical
      across runs; the script sorts nothing because it emits in a fixed order)
"""

import pathlib
import sys

import numpy as np
from numpy.random import Generator, PCG64, SeedSequence

# The frozen program seed (FINAL_PLAN.md: torch seed 20260810 / APPENDIX C7).
PROGRAM_SEED = 20260810

# (sid, side_index) pairs the fixture pins.  The first block is the real coin
# domain (scoped session ordinals 125..749 and small draw indices); the last two
# rows are port-coverage entropy shapes: a side_index above 2**32 (two entropy
# words, so the assembled entropy is four words) and one above 2**64 (three
# words, so the assembled entropy is FIVE words and numpy's "remaining entropy"
# loop past the pool size runs).
CASES = [
    (125, 0),
    (125, 1),
    (125, 2),
    (125, 7),
    (500, 3),
    (749, 41),
    (0, 0),
    # A ZERO FOLLOWED BY A NON-ZERO: the only shape in which numpy's rule that a
    # zero integer still contributes one uint32 word is observable at all (a
    # trailing zero is indistinguishable from absence once the pool is padded).
    (0, 7),
    (749, 4294967296),
    (749, 18446744073709551617),
]

RAW_DRAWS = 8
COIN_DRAWS = 8


def main() -> int:
    out_dir = pathlib.Path(__file__).resolve().parent / "replay"
    out_dir.mkdir(parents=True, exist_ok=True)
    out_path = out_dir / "pcg64_numpy_parity.tsv"

    lines = [
        "# numpy-parity literals for the WP11 PCG64 + SeedSequence port.",
        "# GENERATED by engine/cpp/tests/fixtures/make_pcg64_parity.py — do not hand-edit.",
        f"# numpy={np.__version__} python={sys.version.split()[0]}",
        "# entropy is always SeedSequence([20260810, sid, side_index]) (a list: numpy's",
        "# SeedSequence takes ONE positional entropy argument, so the three-part seed is",
        "# a sequence, not three positionals).",
        "#",
        "# kind\tsid\tside_index\tindex\tvalue",
        "#   pool32          : the four uint32 pool words after mix_entropy",
        "#   state32         : generate_state(4, uint32)",
        "#   state64         : generate_state(4, uint64) — the words PCG64 seeds from",
        "#   raw64           : bit_generator.random_raw() draw i (pcg64_next64)",
        "#   raw32           : bit_generator.random_raw() split — next_uint32 draw i",
        "#   coin            : Generator(PCG64(ss)).integers(0, 2) draw i",
        "kind\tsid\tside_index\tindex\tvalue",
    ]

    def emit(kind, sid, side_index, index, value):
        lines.append(f"{kind}\t{sid}\t{side_index}\t{index}\t{value}")

    for sid, side_index in CASES:
        entropy = [PROGRAM_SEED, sid, side_index]

        ss = SeedSequence(entropy)
        for i, word in enumerate(np.asarray(ss.pool, dtype=np.uint32)):
            emit("pool32", sid, side_index, i, int(word))
        for i, word in enumerate(SeedSequence(entropy).generate_state(4, np.uint32)):
            emit("state32", sid, side_index, i, int(word))
        for i, word in enumerate(SeedSequence(entropy).generate_state(4, np.uint64)):
            emit("state64", sid, side_index, i, int(word))

        bg = PCG64(SeedSequence(entropy))
        for i, word in enumerate(bg.random_raw(RAW_DRAWS)):
            emit("raw64", sid, side_index, i, int(word))

        # next_uint32 semantics: pcg64_next32 returns the LOW half of a fresh
        # next64 first and caches the HIGH half for the following call.  Derived
        # here from the raw 64-bit stream so the file records what the C++ port
        # must reproduce without the port being consulted.
        raw = PCG64(SeedSequence(entropy)).random_raw(RAW_DRAWS)
        halves = []
        for word in raw:
            halves.append(int(word) & 0xFFFFFFFF)
            halves.append(int(word) >> 32)
        for i, half in enumerate(halves[: 2 * RAW_DRAWS]):
            emit("raw32", sid, side_index, i, half)

        gen = Generator(PCG64(SeedSequence(entropy)))
        draws = gen.integers(0, 2, size=COIN_DRAWS)
        for i, bit in enumerate(draws):
            emit("coin", sid, side_index, i, int(bit))

    out_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {out_path} ({len(lines)} lines)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
