#!/usr/bin/env python3
"""WP6 fixture generator — every qr_candidates test fixture, from scratch.

LAW (FINAL_PLAN.md section 6, and the rule WP3 already follows): "fixture files
live under engine/cpp/tests/fixtures/, generated by a committed script, never by
hand-editing binaries".  A corrupt fixture is built by ASKING this writer for the
corruption; nothing here pokes bytes into a good file afterwards.

INDEPENDENCE.  The event-signal sequence-root formula is implemented here a
SECOND time, in a second language, from the same primary source as the C++ port
(the frozen feasibility witness, source sha256
12cf894248a371cbc98d7b6d0a65ab0fc1fc359cbe1e36a8b7c927eb8c1f6d3b, whose framing
and kernel constants are published in side_prefix_feasibility_v1/probe_s125_v3/
receipt.json).  The roots this script writes into the fixture `t14_bounds.tsv`
are therefore an INDEPENDENT expectation: if the C++ reproduces them, two
separate implementations of the same primary source agree.  Nothing here reads
the C++ output, and the C++ never computes these numbers any other way.

Usage:
    python3 make_candidate_fixtures.py [--out-dir DIR] [--literals-path PATH]

Default out-dir is ``<this file>/candidates``.  Output is deterministic: two
runs are byte-identical.
"""

from __future__ import annotations

import argparse
import hashlib
import os
import struct
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from make_parquet_fixtures import (  # noqa: E402
    CODEC_SNAPPY,
    CODEC_ZSTD,
    CONVERTED_UTF8,
    ENC_PLAIN,
    ENC_RLE,
    MAGIC,
    REP_OPTIONAL,
    REP_REQUIRED,
    TYPE_BYTE_ARRAY,
    TYPE_INT64,
    Compact,
    hybrid,
    page_header_v1,
    plain_byte_array,
    zstd_compress,
)

# ---------------------------------------------------------------------------
# the frozen root formula, implemented independently from the primary source
# ---------------------------------------------------------------------------

FRAMING_SEMANTIC = "a65d17669c77c27559f091d69b03b52d4cb303fbb6c961e59c7c99d1216f243a"
FRAMING_CODE = "991fadb2d273890d5c0f472ba36869e0af62d3872ef2c1aee6a570fd17ddd167"
KERNEL_SEMANTIC = "3332cc2e53ae1e2f53d63b8bf8c56b2840169682f27ca7bff055000b90b55cc8"
KERNEL_CODE = "4aba65b4297d62d45873595ab44db403c9c6cc2cce1e5c497d99f975f78abd79"
SIGNAL_DOMAIN = "iwm-atlas-v2-causal-intrabar-signal-sequence-v1"


def _text_term(value: str) -> bytes:
    """A length-prefixed text term: be64(len) || bytes."""
    raw = value.encode("ascii")
    return struct.pack(">Q", len(raw)) + raw


def _digest_term(value: str) -> bytes:
    """A digest term: the 32 RAW bytes, with no length prefix."""
    if len(value) != 64 or any(c not in "0123456789abcdef" for c in value):
        raise ValueError(f"noncanonical digest {value}")
    return bytes.fromhex(value)


def signal_image(fields: list[str]) -> bytes:
    """The 24-term hash image of one event-signal row."""
    if len(fields) != 40:
        raise ValueError("event rows carry exactly 40 cells")
    out = bytearray()
    out += _digest_term(fields[2])   # signal_id
    out += _digest_term(fields[3])   # physical_event_id
    out += _digest_term(fields[4])   # policy_id
    out += _digest_term(fields[7])   # causal_run_prefix_root
    out += struct.pack(">I", int(fields[8]))          # continuity_ordinal
    out += bytes([{"LOW": 0, "HIGH": 1}[fields[9]]])  # extreme_side
    out += struct.pack(">q", int(fields[10]))         # pivot_price_u6
    out += _digest_term(fields[11])                   # pivot_evidence_root
    out += struct.pack(">Q", int(fields[17]))         # confirmation_state_position
    out += struct.pack(">Q", int(fields[18]))         # confirmation_group_ordinal
    out += struct.pack(">q", int(fields[19]))         # confirmation_ts_ns
    out += struct.pack(">q", int(fields[20]))         # causal_visible_ts_ns
    out += bytes([1 if fields[23] == "true" else 0])  # pivot_retouch_order_uncertain
    for cell in (fields[24], fields[25]):             # the two optional delays
        if cell == "NA":
            out += bytes([0])
        else:
            out += bytes([1]) + struct.pack(">I", int(cell))
    out += struct.pack(">q", int(fields[26]))         # latency_from_pivot_ns_min
    out += struct.pack(">q", int(fields[27]))         # latency_from_pivot_ns_max
    out += struct.pack(">Q", int(fields[28]))         # latency_from_pivot_groups_min
    out += struct.pack(">Q", int(fields[29]))         # latency_from_pivot_groups_max
    out += struct.pack(">q", int(fields[31]))         # confirmation_price_low_u6
    out += struct.pack(">q", int(fields[32]))         # confirmation_price_high_u6
    out += struct.pack(">I", int(fields[33]))         # confirmation_crossing_count
    out += _digest_term(fields[34])                   # confirmation_crossing_set_root
    out += _digest_term(fields[35])                   # confirmation_group_root
    return bytes(out)


def session_root(rows: list[list[str]]) -> str:
    """The session's signal_sequence_root over its rows, in file order."""
    hasher = hashlib.sha256()
    hasher.update(_text_term(FRAMING_SEMANTIC))
    hasher.update(_text_term(FRAMING_CODE))
    hasher.update(_text_term(SIGNAL_DOMAIN))
    hasher.update(_text_term(KERNEL_SEMANTIC))
    hasher.update(_text_term(KERNEL_CODE))
    hasher.update(struct.pack(">Q", len(rows)))
    for row in rows:
        hasher.update(signal_image(row))
    return hasher.hexdigest()


# ---------------------------------------------------------------------------
# the pinned headers (byte-for-byte the sealed publications' own headers)
# ---------------------------------------------------------------------------

EVENT_COLUMNS = [
    "ordinal", "day", "signal_id", "physical_event_id", "policy_id", "policy_name",
    "reversal_bps", "causal_run_prefix_root", "continuity_ordinal", "extreme_side",
    "pivot_price_u6", "pivot_evidence_root", "pivot_fragment_count", "pivot_fragments",
    "pivot_first_ts_ns", "pivot_last_ts_ns", "pivot_last_bar_ordinal",
    "confirmation_state_position", "confirmation_group_ordinal", "confirmation_ts_ns",
    "causal_visible_ts_ns", "confirmation_bar_ordinal", "causal_visible_bar_ordinal",
    "pivot_retouch_order_uncertain", "origin_to_visible_delay_bars_min",
    "origin_to_visible_delay_bars_max", "latency_from_pivot_ns_min",
    "latency_from_pivot_ns_max", "latency_from_pivot_groups_min",
    "latency_from_pivot_groups_max", "threshold_level_u6", "confirmation_price_low_u6",
    "confirmation_price_high_u6", "confirmation_crossing_count",
    "confirmation_crossing_set_root", "confirmation_group_root", "overshoot_low_u6",
    "overshoot_high_u6", "confirmation_kind", "confirmation_quality_mask",
]

T14_COLUMNS = [
    "ordinal", "day", "source_authority_root", "event_input_root", "adapter_receipt_id",
    "source_retained_bytes", "scientific_group_count", "run_count", "breaker_count",
    "bar_count", "causal_session_id", "scientific_path_book_id", "wide_breaker_root",
    "episode_book_id", "episode_sequence_root", "scale_link_sequence_root", "episode_count",
    "confirmed_episode_count", "scale_link_count", "plateau_fragment_count",
    "unresolved_fragment_count", "episode_retained_bytes", "truth_20_count",
    "truth_20_fragment_count", "truth_20_retained_bytes", "truth_40_count",
    "truth_40_fragment_count", "truth_40_retained_bytes", "event_book_id",
    "signal_sequence_root", "ambiguity_sequence_root", "summary_sequence_root",
    "signal_count", "ambiguity_count", "summary_count", "pivot_fragment_count",
    "event_retained_bytes", "scoring_signal_views_retained_bytes",
    "scoring_ambiguity_views_retained_bytes", "max_stream_signal_count",
    "max_stream_ambiguity_count", "max_stream_truth_count", "max_stream_workspace_bytes",
    "episode_transient_bytes", "event_transient_bytes", "episode_phase_bytes",
    "event_phase_bytes", "scoring_phase_bytes", "charge_bytes", "admission_class",
]

PROJECTION_COLUMNS = [
    "day", "row_kind", "episode_id", "plateau_last_group_ordinal", "plateau_bar_ordinal",
    "plateau_end_ts_ns", "signal_id", "related_episode_ids", "relation_count",
    "stream_policy_name", "stream_reversal_bps", "candidate_id", "member_signal_ids",
    "registration_ordinal", "confirmation_group_ordinal", "visible_ts_ns",
    "visible_bar_ordinal", "session_end_ns", "event_scorable", "side", "price_u6",
    "continuity_ordinal", "coincident_ambiguities", "physical_event_id",
]

REGISTRY_COLUMNS = [
    "day", "session_ordinal", "row_kind", "candidate_id", "stream_policy_name",
    "stream_reversal_bps", "member_signal_ids", "member_count", "registration_ordinal",
    "confirmation_group_ordinal", "visible_ts_ns", "visible_bar_ordinal", "session_end_ns",
    "event_scorable", "physical_cluster_id", "cluster_disposition", "cluster_size",
    "d1_reachable", "d1_legal_actions", "d2_reachable", "d2_legal_actions", "d3_reachable",
    "d3_legal_actions", "cost_cell_id", "d2_predecessor", "d3_predecessor",
]


def digest(label: str) -> str:
    """A stable canonical 64-hex id for a fixture entity."""
    return hashlib.sha256(("qr_candidates_fixture:" + label).encode("ascii")).hexdigest()


# ---------------------------------------------------------------------------
# a parameterised BYTE_ARRAY parquet writer (multi row group, real statistics)
# ---------------------------------------------------------------------------


def write_parquet(path: str, names: list[str], values: dict[str, list], group_sizes: list[int],
                  stats_for: set[str], stats_override: dict | None = None,
                  repetition: int = REP_REQUIRED, codec: int = CODEC_ZSTD,
                  physical_override: tuple | None = None,
                  converted_override: tuple | None = None) -> None:
    """Writes one BYTE_ARRAY/UTF8 column per name, ZSTD, DataPage v1.

    REPETITION IS REQUIRED BY DEFAULT, because that is what the bound
    publications measurably are (tests/fixtures/publication_repetition_census.tsv:
    24/24 and 26/26 leaves REQUIRED). A REQUIRED leaf carries no definition
    levels and no nulls, so ``values[name][row]`` must be a ``str``; the
    OPTIONAL variant exists only so the PUBLICATION profile has something
    lawful-elsewhere to refuse.

    ``stats_override`` maps (name, group) -> (min_bytes, max_bytes) so a fixture
    can carry statistics that DISAGREE with its own values. ``physical_override``
    and ``converted_override`` are (name, value) pairs that mis-declare ONE
    leaf, so a profile gate can be exercised without a second writer.
    """
    total = sum(group_sizes)
    for name in names:
        if len(values[name]) != total:
            raise ValueError(f"column {name} has {len(values[name])} values, expected {total}")
        if repetition == REP_REQUIRED and any(v is None for v in values[name]):
            raise ValueError(f"column {name} carries a null in a REQUIRED leaf")
    stats_override = stats_override or {}

    body = bytearray(MAGIC)
    row_group_structs: list[Compact] = []
    lo = 0
    for group, size in enumerate(group_sizes):
        hi = lo + size
        chunk_structs: list[Compact] = []
        group_bytes = 0
        for name in names:
            chunk_start = len(body)
            window = values[name][lo:hi]
            present = [v for v in window if v is not None]
            value_bytes = plain_byte_array([v.encode("utf-8") for v in present])
            if repetition == REP_REQUIRED:
                # max definition level 0: the page carries values and nothing else.
                raw = value_bytes
            else:
                levels = [0 if v is None else 1 for v in window]
                level_bytes = hybrid(levels, 1, "rle")
                raw = struct.pack("<I", len(level_bytes)) + level_bytes + value_bytes
            packed = zstd_compress(raw)
            header = page_header_v1(len(raw), len(packed), size, ENC_PLAIN)
            data_offset = len(body)
            body += header
            body += packed
            chunk_uncompressed = len(header) + len(raw)
            total_compressed = len(body) - chunk_start
            meta = (
                Compact()
                .i32(1, physical_override[1]
                     if physical_override and physical_override[0] == name else TYPE_BYTE_ARRAY)
                .i32_list(2, [ENC_RLE, ENC_PLAIN])
                .text_list(3, [name])
                .i32(4, codec)
                .i64(5, size)
                .i64(6, chunk_uncompressed)
                .i64(7, total_compressed)
                .i64(9, data_offset)
            )
            if name in stats_for:
                key = (name, group)
                if key in stats_override:
                    min_bytes, max_bytes = stats_override[key]
                elif present:
                    encoded = sorted(v.encode("utf-8") for v in present)
                    min_bytes, max_bytes = encoded[0], encoded[-1]
                else:
                    min_bytes = max_bytes = b""
                stats = (
                    Compact()
                    .i64(3, len(window) - len(present))
                    .binary(5, max_bytes)
                    .binary(6, min_bytes)
                )
                meta.struct(12, stats)
            chunk_structs.append(Compact().i64(2, chunk_start).struct(3, meta))
            group_bytes += total_compressed
        row_group_structs.append(
            Compact().struct_list(1, chunk_structs).i64(2, group_bytes).i64(3, size)
        )
        lo = hi

    schema_structs = [Compact().text(4, "arrow_schema").i32(5, len(names))]
    for name in names:
        element = Compact()
        physical = (physical_override[1]
                    if physical_override and physical_override[0] == name else TYPE_BYTE_ARRAY)
        element.i32(1, physical).i32(3, repetition).text(4, name)
        converted = (converted_override[1]
                     if converted_override and converted_override[0] == name else CONVERTED_UTF8)
        if converted is not None:
            element.i32(6, converted)
        schema_structs.append(element)
    footer = (
        Compact()
        .i32(1, 2)
        .struct_list(2, schema_structs)
        .i64(3, total)
        .struct_list(4, row_group_structs)
        .text(6, "qr_candidates_fixture_generator")
        .done()
    )
    with open(path, "wb") as handle:
        handle.write(bytes(body) + footer + struct.pack("<I", len(footer)) + MAGIC)


# ---------------------------------------------------------------------------
# the fixture world
# ---------------------------------------------------------------------------

DAYS = ["2022-01-03", "2022-01-04", "2022-01-05", "2022-01-06", "2022-01-07", "2022-01-10"]
N_SESSIONS = len(DAYS)
#: The prefix stop used by the tests. Sessions 4 and 5 exist BEYOND it, so a
#: reader that oversteps by one byte is observable.
STOP_ORDINAL = 3


def event_row(ordinal: int, day: str, label: str, physical: str, policy: str, reversal: int,
              side: str, visible: int, absent_delays: bool = False) -> list[str]:
    """One event_signals row: 40 cells, every hashed cell a real value."""
    return [
        str(ordinal),                       # 0 ordinal
        day,                                # 1 day
        digest(label),                      # 2 signal_id
        physical,                           # 3 physical_event_id
        digest("policy:" + policy),         # 4 policy_id
        policy,                             # 5 policy_name
        str(reversal),                      # 6 reversal_bps
        digest("run:" + label),             # 7 causal_run_prefix_root
        "0",                                # 8 continuity_ordinal
        side,                               # 9 extreme_side
        "223695000",                        # 10 pivot_price_u6
        digest("pivot:" + label),           # 11 pivot_evidence_root
        "1",                                # 12 pivot_fragment_count
        "0:1:0:0:1:1",                      # 13 pivot_fragments
        "1000",                             # 14 pivot_first_ts_ns
        "1001",                             # 15 pivot_last_ts_ns
        "0",                                # 16 pivot_last_bar_ordinal
        "53",                               # 17 confirmation_state_position
        "36",                               # 18 confirmation_group_ordinal
        str(visible - 1),                   # 19 confirmation_ts_ns
        str(visible),                       # 20 causal_visible_ts_ns
        "0",                                # 21 confirmation_bar_ordinal
        "0",                                # 22 causal_visible_bar_ordinal
        "false",                            # 23 pivot_retouch_order_uncertain
        "NA" if absent_delays else "0",     # 24 origin_to_visible_delay_bars_min
        "NA" if absent_delays else "1",     # 25 origin_to_visible_delay_bars_max
        "55000000",                         # 26 latency_from_pivot_ns_min
        "55000001",                         # 27 latency_from_pivot_ns_max
        "36",                               # 28 latency_from_pivot_groups_min
        "37",                               # 29 latency_from_pivot_groups_max
        "223717370",                        # 30 threshold_level_u6
        "223725000",                        # 31 confirmation_price_low_u6
        "223725001",                        # 32 confirmation_price_high_u6
        "1",                                # 33 confirmation_crossing_count
        digest("cross:" + label),           # 34 confirmation_crossing_set_root
        digest("group:" + label),           # 35 confirmation_group_root
        "7630",                             # 36 overshoot_low_u6
        "7631",                             # 37 overshoot_high_u6
        "HETEROGENEOUS_CROSSING_ENVELOPE",  # 38 confirmation_kind
        "0",                                # 39 confirmation_quality_mask
    ]


P = {name: digest("physical:" + name) for name in ("P1", "P2", "P3", "P4", "P5", "P6", "P7")}

#: (label, physical, policy, reversal, side, visible, absent_delays)
SESSION2_SIGNALS = [
    ("A1", "P1", "dc001", 1, "LOW", 1000, False),
    ("B1", "P2", "dc002", 2, "HIGH", 1000, False),
    ("B2", "P2", "dc002", 2, "HIGH", 1500, True),
    ("C1", "P3", "dc003", 3, "LOW", 1000, False),
    ("C2", "P3", "dc003", 3, "HIGH", 1000, False),
    ("D1", "P4", "dc004", 4, "LOW", 3000, False),
    ("E1", "P5", "dc005", 9, "LOW", 1000, False),
    ("F1", "P6", "dc006", 6, "LOW", 1000, False),
    ("F2", "P6", "dc006", 6, "LOW", 1200, False),
]


def build_signals(split_member: bool = False) -> dict[int, list[list[str]]]:
    """Ordinal -> its event rows. `split_member` moves F2 onto a second physical
    event, which is the card's multi-member fail-first mutation."""
    out: dict[int, list[list[str]]] = {}
    for ordinal in range(N_SESSIONS):
        day = DAYS[ordinal]
        if ordinal == 2:
            rows = []
            for label, physical, policy, reversal, side, visible, absent in SESSION2_SIGNALS:
                key = "P7" if (split_member and label == "F2") else physical
                rows.append(event_row(ordinal, day, label, P[key], policy, reversal, side,
                                      visible, absent))
            out[ordinal] = rows
        else:
            out[ordinal] = [
                event_row(ordinal, day, f"s{ordinal}_{i}", P["P1"], "dc001", 1,
                          "LOW" if i % 2 == 0 else "HIGH", 1000 + i)
                for i in range(2 + ordinal)
            ]
    return out


def render_event_signals(signals: dict[int, list[list[str]]], order: list[int]) -> str:
    lines = ["\t".join(EVENT_COLUMNS)]
    for ordinal in order:
        for row in signals[ordinal]:
            lines.append("\t".join(row))
    return "\n".join(lines) + "\n"


def render_t14(signals: dict[int, list[list[str]]], order: list[int],
               count_delta: dict[int, int] | None = None,
               root_override: dict[int, str] | None = None) -> str:
    count_delta = count_delta or {}
    root_override = root_override or {}
    lines = ["\t".join(T14_COLUMNS)]
    for position, ordinal in enumerate(order):
        rows = signals[ordinal]
        cells = ["0"] * len(T14_COLUMNS)
        cells[0] = str(position if order != sorted(order) else ordinal)
        cells[1] = DAYS[ordinal]
        cells[29] = root_override.get(ordinal, session_root(rows))
        cells[32] = str(len(rows) + count_delta.get(ordinal, 0))
        cells[49] = "three_wide"
        # every non-numeric metadata cell keeps a plausible shape; nothing but
        # ordinal/day/root/count is ever parsed.
        for index in (2, 3, 4, 10, 11, 12, 13, 14, 15, 28, 30, 31):
            cells[index] = digest(f"t14:{ordinal}:{index}")
        lines.append("\t".join(cells))
    return "\n".join(lines) + "\n"


# --- the candidate world of session 2 ---------------------------------------

#: (candidate, policy, reversal, visible, members, scorable)
SESSION2_CANDIDATES = [
    ("cand_A", "dc001", 1, 2000, ["A1"], "true"),
    ("cand_B", "dc002", 2, 2000, ["B1", "B2"], "true"),
    ("cand_C", "dc003", 3, 2000, ["C1", "C2"], "true"),
    ("cand_D", "dc004", 4, 2000, ["D1"], "true"),
    ("cand_E", "dc005", 5, 2000, ["E1"], "true"),
    ("cand_G", "dc007", 7, 2000, ["G1"], "true"),
    ("cand_N", "dc008", 8, None, ["A1"], "true"),
    ("cand_S", "dc010", 10, 2000, ["A1"], "false"),
    ("cand_U", "UNION", 0, 2000, ["A1"], "true"),
    ("cand_X", "dc009", 9, 2000, ["A1"], "true"),
    # The LATE sibling: strictly later visibility than every other candidate.
    ("cand_F", "dc006", 6, 2500, ["F1", "F2"], "true"),
]

#: candidate -> its physical key in the RAW projection (the member set's own
#: physical event, which is what authentication must prove).
CANDIDATE_PHYSICAL = {
    "cand_A": "P1", "cand_B": "P2", "cand_C": "P3", "cand_D": "P4", "cand_E": "P5",
    "cand_G": "P1", "cand_N": "P1", "cand_S": "P1", "cand_U": "P1", "cand_X": "P1",
    "cand_F": "P6",
}


def member_cell(labels: list[str], form: str = "canonical") -> str:
    ids = sorted(digest(label) for label in labels)
    if form == "canonical":
        return ",".join(ids)
    if form == "unsorted":
        return ",".join(reversed(ids)) if len(ids) > 1 else ",".join([ids[0], ids[0]])
    if form == "duplicate":
        return ",".join(ids + [ids[-1]])
    if form == "uppercase":
        return ",".join([ids[0].upper()] + ids[1:])
    if form == "empty_token":
        return ",".join(ids) + ","
    if form == "whitespace":
        return ", ".join(ids) if len(ids) > 1 else " " + ids[0]
    raise ValueError(form)


def build_session2_rows(member_forms: dict[str, str] | None = None,
                        drop: set[str] | None = None,
                        registry_overrides: dict | None = None,
                        projection_overrides: dict | None = None):
    """Returns (registry_rows, projection_rows) for session ordinal 2."""
    member_forms = member_forms or {}
    drop = drop or set()
    registry_overrides = registry_overrides or {}
    projection_overrides = projection_overrides or {}
    registry_rows = []
    projection_rows = []
    for candidate, policy, reversal, visible, members, scorable in SESSION2_CANDIDATES:
        if candidate in drop:
            continue
        cell = member_cell(members, member_forms.get(candidate, "canonical"))
        reg = {
            "day": DAYS[2], "session_ordinal": "2", "row_kind": "CANDIDATE",
            "candidate_id": digest(candidate), "stream_policy_name": policy,
            "stream_reversal_bps": str(reversal), "member_signal_ids": cell,
            "member_count": str(len(members)),
            "visible_ts_ns": "NA" if visible is None else str(visible),
            "event_scorable": scorable, "physical_cluster_id": digest("cluster:" + candidate),
            "cluster_disposition": "FINAL", "cluster_size": "1",
        }
        reg.update(registry_overrides.get(candidate, {}))
        registry_rows.append(reg)
        raw = {
            "day": DAYS[2], "row_kind": "CANDIDATE", "candidate_id": digest(candidate),
            "stream_policy_name": policy, "stream_reversal_bps": str(reversal),
            "member_signal_ids": cell,
            "visible_ts_ns": "NA" if visible is None else str(visible),
            "physical_event_id": P[CANDIDATE_PHYSICAL[candidate]],
            "event_scorable": scorable, "side": "LEAK_IF_READ",
        }
        raw.update(projection_overrides.get(candidate, {}))
        projection_rows.append(raw)
    # A non-CANDIDATE row: the raw projection carries TRUTH rows too, and they
    # must never enter the join.
    projection_rows.append({
        "day": DAYS[2], "row_kind": "TRUTH", "candidate_id": digest("truth_row"),
        "stream_policy_name": "dc001", "stream_reversal_bps": "1",
        "member_signal_ids": digest("A1"), "visible_ts_ns": "2000",
        "physical_event_id": P["P1"], "side": "LEAK_IF_READ",
    })
    return registry_rows, projection_rows


def filler_rows(ordinal: int, count: int):
    """Small, self-consistent candidate rows for the sessions that are not the
    roster fixture, so every row group has real content."""
    registry_rows, projection_rows = [], []
    for i in range(count):
        candidate = f"s{ordinal}_c{i}"
        members = [f"s{ordinal}_{i}"]
        cell = member_cell(members)
        registry_rows.append({
            "day": DAYS[ordinal], "session_ordinal": str(ordinal), "row_kind": "CANDIDATE",
            "candidate_id": digest(candidate), "stream_policy_name": "dc001",
            "stream_reversal_bps": "1", "member_signal_ids": cell, "member_count": "1",
            "visible_ts_ns": str(5000 + i), "event_scorable": "true",
            "physical_cluster_id": digest("cluster:" + candidate),
        })
        projection_rows.append({
            "day": DAYS[ordinal], "row_kind": "CANDIDATE", "candidate_id": digest(candidate),
            "stream_policy_name": "dc001", "stream_reversal_bps": "1",
            "member_signal_ids": cell, "visible_ts_ns": str(5000 + i),
            "physical_event_id": P["P1"], "side": "LEAK_IF_READ",
        })
    return registry_rows, projection_rows


def materialise(rows_by_session: dict[int, list[dict]], names: list[str]):
    """Flattens per-session dict rows into column arrays plus group sizes."""
    values = {name: [] for name in names}
    sizes = []
    for ordinal in range(N_SESSIONS):
        rows = rows_by_session[ordinal]
        sizes.append(len(rows))
        for row in rows:
            for name in names:
                # A REQUIRED leaf has no null state at all, so an unset field is
                # the empty string, never a null.
                values[name].append(row.get(name, ""))
    return values, sizes


def build_tables(session2_registry, session2_projection):
    registry_by_session, projection_by_session = {}, {}
    for ordinal in range(N_SESSIONS):
        if ordinal == 2:
            registry_by_session[ordinal] = session2_registry
            projection_by_session[ordinal] = session2_projection
        else:
            reg, raw = filler_rows(ordinal, 2 + ordinal)
            registry_by_session[ordinal] = reg
            projection_by_session[ordinal] = raw
    return registry_by_session, projection_by_session


def write_session_index(path: str, sizes: list[int], row_override: dict[int, int] | None = None,
                        ordinal_override: dict[int, str] | None = None) -> None:
    row_override = row_override or {}
    ordinal_override = ordinal_override or {}
    lines = ["ordinal\tday\trows"]
    for ordinal in range(N_SESSIONS):
        lines.append("\t".join([
            ordinal_override.get(ordinal, str(ordinal)),
            DAYS[ordinal],
            str(row_override.get(ordinal, sizes[ordinal])),
        ]))
    with open(path, "w", encoding="ascii") as handle:
        handle.write("\n".join(lines) + "\n")


def write_text(path: str, body: str) -> None:
    with open(path, "w", encoding="ascii") as handle:
        handle.write(body)


def main(argv: list[str] | None = None) -> int:
    here = os.path.dirname(os.path.abspath(__file__))
    parser = argparse.ArgumentParser()
    parser.add_argument("--out-dir", default=os.path.join(here, "candidates"))
    parser.add_argument("--literals-path", default=None)
    args = parser.parse_args(argv)
    out = args.out_dir
    os.makedirs(out, exist_ok=True)
    literals_path = args.literals_path or os.path.join(out, "expected_literals.tsv")

    order = list(range(N_SESSIONS))

    # --- the TSV prefix fixtures ---------------------------------------------
    good = build_signals()
    write_text(os.path.join(out, "event_signals_good.tsv"), render_event_signals(good, order))
    write_text(os.path.join(out, "t14_bounds_good.tsv"), render_t14(good, order))
    write_text(os.path.join(out, "t14_bounds_bad_count.tsv"),
               render_t14(good, order, count_delta={2: 1}))
    bad_root = session_root(good[2])
    bad_root = bad_root[:-1] + ("0" if bad_root[-1] != "0" else "1")
    write_text(os.path.join(out, "t14_bounds_bad_root.tsv"),
               render_t14(good, order, root_override={2: bad_root}))

    # Non-monotone: the FILE goes 0,1,0,... and the census is permuted the same
    # way, so only the monotonicity law can catch it.
    permuted = [0, 1, 0, 2, 3, 4, 5]
    lines = ["\t".join(EVENT_COLUMNS)]
    census_lines = ["\t".join(T14_COLUMNS)]
    for position, ordinal in enumerate(permuted):
        for row in good[ordinal]:
            lines.append("\t".join(row))
        cells = ["0"] * len(T14_COLUMNS)
        cells[0] = str(ordinal)
        cells[1] = DAYS[ordinal]
        cells[29] = session_root(good[ordinal])
        cells[32] = str(len(good[ordinal]))
        cells[49] = "three_wide"
        census_lines.append("\t".join(cells))
    write_text(os.path.join(out, "event_signals_nonmonotone.tsv"), "\n".join(lines) + "\n")
    write_text(os.path.join(out, "t14_bounds_nonmonotone.tsv"), "\n".join(census_lines) + "\n")

    # Duplicate signal id inside one session.
    dup = build_signals()
    dup[2] = dup[2] + [dup[2][0]]
    write_text(os.path.join(out, "event_signals_duplicate_id.tsv"),
               render_event_signals(dup, order))
    write_text(os.path.join(out, "t14_bounds_duplicate_id.tsv"), render_t14(dup, order))

    # A carriage return inside an admitted row.
    cr = render_event_signals(good, order).replace("HETEROGENEOUS_CROSSING_ENVELOPE",
                                                   "HETEROGENEOUS\rENVELOPE", 1)
    write_text(os.path.join(out, "event_signals_carriage_return.tsv"), cr)

    # THE MULTI-MEMBER FAIL-FIRST: one member's physical id is moved to a second
    # physical event, and the census root is RECOMPUTED so the prefix seal still
    # passes. Only the member-physical-key check can catch this.
    split = build_signals(split_member=True)
    write_text(os.path.join(out, "event_signals_member_split.tsv"),
               render_event_signals(split, order))
    write_text(os.path.join(out, "t14_bounds_member_split.tsv"), render_t14(split, order))

    # --- the parquet fixtures --------------------------------------------------
    session2_registry, session2_projection = build_session2_rows()
    registry_by_session, projection_by_session = build_tables(session2_registry,
                                                             session2_projection)
    reg_values, reg_sizes = materialise(registry_by_session, REGISTRY_COLUMNS)
    raw_values, raw_sizes = materialise(projection_by_session, PROJECTION_COLUMNS)
    write_parquet(os.path.join(out, "registry_good.parquet"), REGISTRY_COLUMNS, reg_values,
                  reg_sizes, {"day", "candidate_id"})
    write_parquet(os.path.join(out, "projection_good.parquet"), PROJECTION_COLUMNS, raw_values,
                  raw_sizes, {"day", "candidate_id"})
    write_session_index(os.path.join(out, "registry_index.tsv"), reg_sizes)
    write_session_index(os.path.join(out, "projection_index.tsv"), raw_sizes)
    write_session_index(os.path.join(out, "projection_index_bad_rows.tsv"), raw_sizes,
                        row_override={2: raw_sizes[2] + 1})
    write_session_index(os.path.join(out, "projection_index_bad_ordinal.tsv"), raw_sizes,
                        ordinal_override={2: "7"})

    # THE SINGLETON FAIL-FIRST: only the candidate ROW's physical key moves.
    flipped_registry, flipped_projection = build_session2_rows(
        projection_overrides={"cand_A": {"physical_event_id": P["P7"]}})
    a, b = build_tables(flipped_registry, flipped_projection)
    values, sizes = materialise(b, PROJECTION_COLUMNS)
    write_parquet(os.path.join(out, "projection_singleton_key_flip.parquet"), PROJECTION_COLUMNS,
                  values, sizes, {"day", "candidate_id"})

    # A rowgroup whose `day` statistics claim a span rather than a single day.
    write_parquet(os.path.join(out, "projection_bad_day_stats.parquet"), PROJECTION_COLUMNS,
                  raw_values, raw_sizes, {"day", "candidate_id"},
                  stats_override={("day", 2): (b"2022-01-05", b"2022-01-06")})
    # A rowgroup whose statistics name a different day than the index does.
    write_parquet(os.path.join(out, "projection_wrong_day_stats.parquet"), PROJECTION_COLUMNS,
                  raw_values, raw_sizes, {"day", "candidate_id"},
                  stats_override={("day", 2): (b"2022-01-06", b"2022-01-06")})
    # A rowgroup with no `day` statistics at all.
    write_parquet(os.path.join(out, "projection_no_day_stats.parquet"), PROJECTION_COLUMNS,
                  raw_values, raw_sizes, {"candidate_id"})
    # One decoded row carrying a neighbour's day, with statistics that still
    # claim the indexed day: only the per-row check can catch it.
    smuggled_registry, smuggled_projection = build_session2_rows(
        projection_overrides={"cand_B": {"day": "2022-01-06"}})
    _, smuggled = build_tables(smuggled_registry, smuggled_projection)
    values, sizes = materialise(smuggled, PROJECTION_COLUMNS)
    write_parquet(os.path.join(out, "projection_smuggled_day.parquet"), PROJECTION_COLUMNS,
                  values, sizes, {"day", "candidate_id"},
                  stats_override={("day", 2): (b"2022-01-05", b"2022-01-05")})

    # THE PER-PROFILE REFUSAL FAMILY (ruling CC-003). Each of these is a lawful
    # parquet that the PUBLICATION profile must refuse by name: an OPTIONAL leaf
    # (lawful in the token corpus), a SNAPPY chunk, an INT64 leaf, and a leaf
    # with no converted type. None of them may be silently admitted.
    write_parquet(os.path.join(out, "projection_optional_leaves.parquet"), PROJECTION_COLUMNS,
                  raw_values, raw_sizes, {"day", "candidate_id"}, repetition=REP_OPTIONAL)
    write_parquet(os.path.join(out, "projection_snappy_codec.parquet"), PROJECTION_COLUMNS,
                  raw_values, raw_sizes, {"day", "candidate_id"}, codec=CODEC_SNAPPY)
    write_parquet(os.path.join(out, "projection_int64_leaf.parquet"), PROJECTION_COLUMNS,
                  raw_values, raw_sizes, {"day", "candidate_id"},
                  physical_override=("relation_count", TYPE_INT64))
    write_parquet(os.path.join(out, "projection_no_converted.parquet"), PROJECTION_COLUMNS,
                  raw_values, raw_sizes, {"day", "candidate_id"},
                  converted_override=("relation_count", None))

    # The join-disagreement family: the raw row contradicts the registry row.
    for name, override in (
        ("policy", {"stream_policy_name": "dc020"}),
        ("reversal", {"stream_reversal_bps": "99"}),
        ("visible", {"visible_ts_ns": "2001"}),
        ("members", {"member_signal_ids": member_cell(["C1"])}),
        ("physical_empty", {"physical_event_id": ""}),
    ):
        reg, raw = build_session2_rows(projection_overrides={"cand_A": override})
        _, tables = build_tables(reg, raw)
        values, sizes = materialise(tables, PROJECTION_COLUMNS)
        write_parquet(os.path.join(out, f"projection_join_{name}.parquet"), PROJECTION_COLUMNS,
                      values, sizes, {"day", "candidate_id"})

    # The malformed member-cell family, one registry per shape.
    for form in ("empty_token", "uppercase", "unsorted", "duplicate", "whitespace"):
        reg, raw = build_session2_rows(member_forms={"cand_B": form})
        tables, _ = build_tables(reg, raw)
        values, sizes = materialise(tables, REGISTRY_COLUMNS)
        write_parquet(os.path.join(out, f"registry_member_{form}.parquet"), REGISTRY_COLUMNS,
                      values, sizes, {"day", "candidate_id"})

    # THE STRICT event_scorable PARSE (consolidated review L2-F1): one registry
    # per unlawful spelling. `TRUE` and `1` are the two spellings a publication
    # drifts into; `yes` stands for everything else. Under `cell == "true"` all
    # three read as NOT SCORABLE and the candidate silently leaves the
    # population; under parse_bool they refuse the session.
    for form, cell in (("upper", "TRUE"), ("one", "1"), ("garbage", "yes")):
        reg, raw = build_session2_rows(
            registry_overrides={"cand_A": {"event_scorable": cell}})
        tables, _ = build_tables(reg, raw)
        values, sizes = materialise(tables, REGISTRY_COLUMNS)
        write_parquet(os.path.join(out, f"registry_scorable_{form}.parquet"), REGISTRY_COLUMNS,
                      values, sizes, {"day", "candidate_id"})

    # A registry whose stored member_count contradicts the derived count.
    reg, raw = build_session2_rows(registry_overrides={"cand_B": {"member_count": "3"}})
    tables, _ = build_tables(reg, raw)
    values, sizes = materialise(tables, REGISTRY_COLUMNS)
    write_parquet(os.path.join(out, "registry_member_count_mismatch.parquet"), REGISTRY_COLUMNS,
                  values, sizes, {"day", "candidate_id"})

    # A registry that repeats one candidate_id inside a session.
    reg, raw = build_session2_rows()
    reg = reg + [dict(reg[0])]
    tables, _ = build_tables(reg, raw)
    values, sizes = materialise(tables, REGISTRY_COLUMNS)
    write_parquet(os.path.join(out, "registry_duplicate_candidate.parquet"), REGISTRY_COLUMNS,
                  values, sizes, {"day", "candidate_id"})
    write_session_index(os.path.join(out, "registry_index_duplicate_candidate.tsv"), sizes)

    # THE LATE-SIBLING DELETION PAIR: cand_F is the strictly-latest-visible
    # candidate; deleting it must leave every earlier record bit-unchanged.
    reg, raw = build_session2_rows(drop={"cand_F"})
    reg_tables, raw_tables = build_tables(reg, raw)
    values, sizes = materialise(reg_tables, REGISTRY_COLUMNS)
    write_parquet(os.path.join(out, "registry_late_sibling_deleted.parquet"), REGISTRY_COLUMNS,
                  values, sizes, {"day", "candidate_id"})
    write_session_index(os.path.join(out, "registry_index_late_sibling_deleted.tsv"), sizes)
    values, sizes = materialise(raw_tables, PROJECTION_COLUMNS)
    write_parquet(os.path.join(out, "projection_late_sibling_deleted.parquet"), PROJECTION_COLUMNS,
                  values, sizes, {"day", "candidate_id"})
    write_session_index(os.path.join(out, "projection_index_late_sibling_deleted.tsv"), sizes)

    # --- the independently derived literals ------------------------------------
    literals = [
        "kind\tkey\tvalue",
        f"prefix\tstop_ordinal\t{STOP_ORDINAL}",
        f"prefix\tsession_count\t{N_SESSIONS}",
    ]
    text = render_event_signals(good, order)
    header_bytes = len(text.split("\n")[0]) + 1
    admitted = sum(len(good[o]) for o in range(STOP_ORDINAL + 1))
    stop_byte = header_bytes + sum(
        len("\t".join(row)) + 1 for o in range(STOP_ORDINAL + 1) for row in good[o])
    final_row_bytes = len("\t".join(good[STOP_ORDINAL][-1])) + 1
    literals += [
        f"prefix\theader_bytes\t{header_bytes}",
        f"prefix\tadmitted_rows\t{admitted}",
        f"prefix\tstop_byte_exclusive\t{stop_byte}",
        f"prefix\tfinal_row_bytes\t{final_row_bytes}",
        f"prefix\tfile_bytes\t{len(text)}",
    ]
    for ordinal in range(N_SESSIONS):
        literals.append(f"root\t{ordinal}\t{session_root(good[ordinal])}")
        literals.append(f"count\t{ordinal}\t{len(good[ordinal])}")
    literals.append("image\tsession2_row0\t" + signal_image(good[2][0]).hex())
    literals.append("image\tsession2_row2_absent_delays\t" + signal_image(good[2][2]).hex())
    literals.append("digest\tempty\t" + hashlib.sha256(b"").hexdigest())
    literals.append("digest\tabc\t" + hashlib.sha256(b"abc").hexdigest())
    for label in ("A1", "B1", "B2", "C1", "C2", "D1", "E1", "F1", "F2", "G1"):
        literals.append(f"signal_id\t{label}\t{digest(label)}")
    for candidate, *_ in SESSION2_CANDIDATES:
        literals.append(f"candidate_id\t{candidate}\t{digest(candidate)}")
    for name, value in sorted(P.items()):
        literals.append(f"physical\t{name}\t{value}")
    for ordinal, day in enumerate(DAYS):
        literals.append(f"day\t{ordinal}\t{day}")
    with open(literals_path, "w", encoding="ascii") as handle:
        handle.write("\n".join(literals) + "\n")

    print(f"wrote candidate fixtures to {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
