// qr_replay/pcg64.hpp — a deterministic numpy-semantics PCG64 + SeedSequence
// port, for the seeded-coin null control.
//
// SPEC (WP11 brief, FINAL_PLAN.md section 11 null battery + section 8 item 2):
//   "the kernel must support: forced-side override streams, seeded coin sides
//    via PCG64 SeedSequence(20260810, sid, side_index) — implement a
//    deterministic PCG64+SeedSequence port matching numpy semantics with a
//    literal cross-check fixture generated by python numpy, committed."
//   FINAL_PLAN section 11: "N1 side-coin at identical times"; section 8:
//   "forced-LONG, forced-SHORT, seeded coin".
//
// WHY A PORT AND NOT A HAND-ROLLED RNG. The controls are read against Python
// analysis code and against the project's own frozen seed (20260810). A coin
// whose draws cannot be reproduced by `numpy.random.Generator(PCG64(
// SeedSequence([20260810, sid, side_index]))).integers(0, 2)` is a different
// control, and no amount of "it is random anyway" makes two different coins the
// same evidence. Every number this port produces is pinned by
// tests/fixtures/replay/pcg64_numpy_parity.tsv, which was generated ONCE by
// numpy 2.1.2 (tests/fixtures/make_pcg64_parity.py) and committed as data.
//
// The parity fixture is also the reason the coin is bit 31 and not bit 0: numpy
// Generator.integers(0, 2) does NOT mask the low bit. It calls Lemire's bounded
// path on the 32-bit generator — m = next_uint32() * 2, result = m >> 32 — so
// the draw is the TOP bit of a 32-bit word. The literals refuted the low-bit
// guess (42/72 agreement, i.e. chance) and confirmed the top bit (72/72).
//
// 128-bit arithmetic is written out over two uint64 halves on purpose:
// `unsigned __int128` is a GNU extension and this tree compiles with
// -Wpedantic -Werror, so the extension is not available to us.
#ifndef QR_REPLAY_PCG64_HPP
#define QR_REPLAY_PCG64_HPP

#include <array>
#include <cstddef>
#include <cstdint>
#include <span>
#include <vector>

#include "qr_replay/action.hpp"

namespace qr::replay {

/// 128-bit unsigned value as an explicit high/low pair (no compiler extension).
struct U128 {
  std::uint64_t hi = 0;
  std::uint64_t lo = 0;

  friend bool operator==(const U128& a, const U128& b) noexcept { return a.hi == b.hi && a.lo == b.lo; }
};

/// Exact 128-bit primitives (only what PCG64 needs).
U128 u128_add(U128 a, U128 b) noexcept;
U128 u128_mul(U128 a, U128 b) noexcept;  // low 128 bits of the product
U128 u128_shl1(U128 a) noexcept;         // a << 1

/// numpy's `SeedSequence` (pool_size 4, empty spawn_key), reproduced exactly:
/// `mix_entropy` over the assembled entropy words, then `generate_state`.
///
/// Non-default pool sizes and spawn keys are deliberately NOT implemented: the
/// seed law names exactly one shape, `SeedSequence([20260810, sid,
/// side_index])`, and an unexercised code path is not evidence of anything.
class SeedSequence {
 public:
  static constexpr std::size_t kPoolSize = 4;

  /// Entropy given as numpy's assembled uint32 word array.
  static SeedSequence from_entropy_words(std::span<const std::uint32_t> words) noexcept;

  /// Entropy given as integers, decomposed the way numpy decomposes a Python
  /// int: little-endian uint32 words, and a zero contributes exactly one zero
  /// word (`_coerce_to_uint32_array`).
  static SeedSequence from_entropy(std::span<const std::uint64_t> values);

  [[nodiscard]] const std::array<std::uint32_t, kPoolSize>& pool() const noexcept { return pool_; }

  /// `generate_state(n, uint32)`.
  void generate_state_u32(std::span<std::uint32_t> out) const noexcept;

  /// `generate_state(n, uint64)` — the uint32 stream viewed as little-endian
  /// pairs, which is what `PCG64._seed_from_seq` consumes.
  void generate_state_u64(std::span<std::uint64_t> out) const noexcept;

 private:
  std::array<std::uint32_t, kPoolSize> pool_{};
};

/// numpy's `PCG64` bit generator (XSL-RR 128/64, DEFAULT multiplier), including
/// the `has_uint32` half-word cache that `next_uint32` uses.
class Pcg64 {
 public:
  explicit Pcg64(const SeedSequence& seed) noexcept;

  /// `pcg64_next64`: step, then XSL-RR output.
  std::uint64_t next_uint64() noexcept;

  /// `pcg64_next32`: the LOW half of a fresh 64-bit draw first, the HIGH half
  /// from the cache on the following call.
  std::uint32_t next_uint32() noexcept;

  /// numpy `Generator.integers(0, rng_inclusive + 1)` for a range that fits in
  /// 32 bits, i.e. Lemire's bounded method on the 32-bit generator.
  std::uint32_t bounded_uint32(std::uint32_t rng_inclusive) noexcept;

 private:
  void step() noexcept;

  U128 state_{};
  U128 inc_{};
  std::uint32_t cached_uint32_ = 0;
  bool has_uint32_ = false;
};

/// The frozen program seed (FINAL_PLAN.md APPENDIX C7 "seed 20260810").
inline constexpr std::uint64_t kProgramSeed = 20260810;

/// One seeded coin side: `SeedSequence([20260810, sid, side_index])` ->
/// `Generator(PCG64(ss)).integers(0, 2)` -> 0 = LONG, 1 = SHORT.
///
/// OPEN QUESTION returned to the orchestrator (see the lane report): the specs
/// fix the seed tuple but not (a) which index `side_index` is, nor (b) the
/// bit -> side map. This implementation takes `side_index` to be the 0-based
/// index of the coin draw WITHIN the session and maps 0 -> LONG, 1 -> SHORT
/// (the declaration order of the sigma law, "+1 LONG / -1 SHORT"). Both are
/// one-line changes here and nowhere else.
Side coin_side(std::int64_t session_ordinal, std::int64_t side_index);

}  // namespace qr::replay

#endif  // QR_REPLAY_PCG64_HPP
