#!/usr/bin/python3
"""PORT M1.B S1.1/S1.2 — the ATLAS v3 DELTA report (m1/atlas_v3/).

Question the orchestrator asked, and the only one this file answers: does the
mover-gated retention cell `retg|e30` hold as champion of its class on the
ENRICHED roster?

The v3 screen is the SAME machinery on the SAME grid enumeration; only the
candidate universe (S1.1 OR_EXT + S1.2 adopted families), the skeleton derived
from it and the probe-feature set (four extra family one-hots + the OR_EXT
distance) differ, and only the CHAMPION CLASS is fitted (families ratio /
certificate / mae_budget / path_shape — the retention epsilon ladder with its
transforms and ranking units, the walled certificate, the MAE-budget ladder and
the path shapes).

Every number is read back out of a committed TSV with its `file:line` (D-010).

Run: /usr/bin/python3 engine/port_m1b/s4_report_v3.py
"""
import os
import sys

_HERE = os.path.dirname(os.path.abspath(__file__))
for _p in (_HERE, "/workspace/engine/port_m0", "/workspace/engine/port_m1"):
    if _p not in sys.path:
        sys.path.insert(0, _p)

import m1_common as M                 # noqa: E402
from report import Tsv, num, cite, md_table   # noqa: E402

V3_DIR = "atlas_v3"
V1_DIR = "atlas"
ASSETS = ("SI", "HG", "NKD")
TOP_N = 10
CHAMPION_PREFIX = "retg|e30"


def _f(x):
    try:
        return float(x)
    except (TypeError, ValueError):
        return float("nan")


def _ranked(t, asset):
    """(label, align, row, line) sorted by economic alignment, twins/voids out."""
    out = []
    for r, ln in zip(t.rows, t.lines):
        if r[t.i("asset")] != asset:
            continue
        if r[t.i("shuffled_twin")] == "1" or r[t.i("voided_by_twin")] == "1":
            continue
        a = _f(r[t.i("align_spearman_unit")])
        if a != a:
            continue
        out.append((r[t.i("label")], a, r, ln))
    out.sort(key=lambda x: (-x[1], x[0]))
    return out


def main():
    v3 = Tsv(M.out_path(V3_DIR, "screen_ledger.tsv"))
    v1 = Tsv(M.out_path(V1_DIR, "screen_ledger.tsv"))
    cf = Tsv(M.out_path(V3_DIR, "confirm_fits.tsv"))
    out = ["# PORT M1.B S1.1/S1.2 — ATLAS v3 (champion-class re-screen on the "
           "ENRICHED roster)\n",
           "Generated by `engine/port_m1b/s4_report_v3.py`. Spec: "
           "`design/PORT_M1B_SPEC.md` sha16 `%s` §1 S4. Roster: "
           "`m1/generation_v3` (S1.1 OR_EXT + S1.2 NEWS-WINDOW / MICRO-OPENS / "
           "POST-SHOCK / FIRST-TEST-NKD). Skeleton: `m1/skel_v3` (qr_skel "
           "re-run on the enriched candidate receipt — engine unchanged, "
           "CONV C2). EXPLORATORY_NONCERTIFYING.\n" % M.SPEC_M1B_SHA16]

    out.append("## Champion verdict — is `%s...` still the top-aligned cell?\n"
               % CHAMPION_PREFIX)
    rows = []
    for a in ASSETS:
        r3 = _ranked(v3, a)
        r1 = _ranked(v1, a)
        if not r3:
            continue
        top3 = r3[0]
        rank_v1 = {lab: i + 1 for i, (lab, _al, _r, _l) in enumerate(r1)}
        champ_rank = next((i + 1 for i, (lab, _a, _r, _l) in enumerate(r3)
                           if lab.startswith(CHAMPION_PREFIX)), 0)
        champ3 = r3[champ_rank - 1] if champ_rank else None
        v1_top = r1[0][0] if r1 else "n/a"
        rows.append([a, top3[0], "%.4f" % top3[1],
                     "%d" % rank_v1.get(top3[0], 0),
                     v1_top, "%.4f" % (r1[0][1] if r1 else float("nan")),
                     (champ3[0] if champ3 else "n/a"),
                     "%d" % champ_rank,
                     "%.4f" % (champ3[1] if champ3 else float("nan")),
                     ("YES" if champ_rank == 1 else "NO"),
                     cite(v3, top3[3])])
    out.append(md_table(["asset", "v3 top cell (champion class)", "v3 align",
                         "its rank in the v2 full-grid screen",
                         "v2 full-grid top cell", "v2 align",
                         "best retg|e30 cell", "its v3 rank", "its v3 align",
                         "retg|e30 holds?", "source"], rows))

    out.append("\n## Top %d by economic alignment, v3 vs v2\n" % TOP_N)
    rows = []
    for a in ASSETS:
        r1map = {lab: (al, ln) for (lab, al, _r, ln) in _ranked(v1, a)}
        for i, (lab, al, r, ln) in enumerate(_ranked(v3, a)[:TOP_N], 1):
            a1, _l1 = r1map.get(lab, (float("nan"), None))
            rows.append([a, "%d" % i, lab, r[v3.i("family")],
                         "%.4f" % al, "%.4f" % a1,
                         "%+.4f" % (al - a1) if a1 == a1 else "n/a",
                         num(r, v3, "rho_median_learnability", "%.3f"),
                         num(r, v3, "dollar_recall_at10", "%.3f"),
                         num(r, v3, "era_sign_consistency", "%.2f"),
                         r[v3.i("holm_significant")], cite(v3, ln)])
    out.append(md_table(["asset", "rank", "label", "family", "v3 align",
                         "v2 align", "delta", "learnability rho",
                         "$recall@10", "era sign", "Holm sig", "source"], rows))

    out.append("\n## The reproduced §2.2 finding: learnability is NOT "
               "alignment\n")
    rows = []
    for a in ASSETS:
        r3 = _ranked(v3, a)
        if not r3:
            continue
        xs = [(_f(r[v3.i("rho_median_learnability")]), al)
              for (_lab, al, r, _ln) in r3]
        xs = [(x, y) for (x, y) in xs if x == x and y == y]
        n = len(xs)
        if n < 3:
            continue
        mx = sum(x for x, _ in xs) / n
        my = sum(y for _, y in xs) / n
        sxy = sum((x - mx) * (y - my) for x, y in xs)
        sxx = sum((x - mx) ** 2 for x, _ in xs)
        syy = sum((y - my) ** 2 for _, y in xs)
        corr = sxy / ((sxx * syy) ** 0.5) if sxx > 0 and syy > 0 else \
            float("nan")
        best_learn = max(xs, key=lambda t: t[0])
        rows.append([a, "%d" % n, "%.3f" % corr, "%.3f" % best_learn[0],
                     "%.4f" % best_learn[1], "`%s`" % v3.rel()])
    out.append(md_table(["asset", "labels scored",
                         "corr(learnability, alignment)",
                         "most learnable rho", "its alignment", "source"],
                        rows))

    if cf:
        out.append("\n## Confirm fits (per-fold HP search) on the enriched "
                   "roster\n")
        rows = []
        for a in ASSETS:
            sel = [(r, ln) for r, ln in zip(cf.rows, cf.lines)
                   if r[cf.i("asset")] == a]
            sel.sort(key=lambda x: -_f(x[0][cf.i("confirm_align")]))
            for r, ln in sel[:5]:
                rows.append([a, r[cf.i("label")],
                             num(r, cf, "screen_align", "%.4f"),
                             num(r, cf, "confirm_align", "%.4f"),
                             num(r, cf, "delta_align_vs_screen", "%+.4f"),
                             num(r, cf, "confirm_dollar_recall_at10", "%.3f"),
                             cite(cf, ln)])
        out.append(md_table(["asset", "label", "screen align", "confirm align",
                             "delta", "$recall@10", "source"], rows))

    p = M.out_path(V3_DIR, "ATLAS_V3_REPORT.md")
    with open(p, "w") as fh:
        fh.write("\n".join(out) + "\n")
    print(p)
    return 0


if __name__ == "__main__":
    sys.exit(main())
