#!/usr/bin/python3
"""PORT M1.B S4 — GENERATED report (m1/atlas/ATLAS_SCREEN_REPORT.md).

Every number is read back out of a committed TSV and carries its `file:line`
(D-010). Nothing is hand-typed. EXPLORATORY_NONCERTIFYING: this stage makes NO
promotion claims - it ranks, guards and reports.

Run: /usr/bin/python3 engine/port_m1b/s4_report.py
"""
import os
import sys

import numpy as np

_HERE = os.path.dirname(os.path.abspath(__file__))
for _p in (_HERE, "/workspace/engine/port_m0", "/workspace/engine/port_m1"):
    if _p not in sys.path:
        sys.path.insert(0, _p)

import s4_common as S                 # noqa: E402
import m1_common as M                 # noqa: E402
from report import Tsv, num, cite               # noqa: E402


def esc(x):
    """Label names carry `|` (the compose separator); escape it for tables."""
    return str(x).replace("|", "\\|")


def md_table(head, rows):
    out = ["| " + " | ".join(esc(h) for h in head) + " |",
           "|" + "|".join(["---"] * len(head)) + "|"]
    for r in rows:
        out.append("| " + " | ".join(esc(x) for x in r) + " |")
    return "\n".join(out)

OUT = S.out_path("ATLAS_SCREEN_REPORT.md")

HEADER = (
    "Generated by `engine/port_m1b/s4_report.py`. Spec `design/PORT_M1B_SPEC.md`"
    " sha16 `%s` §1 S4; label taxonomy `design/LABEL_ATLAS_V2.md` §1B/§1C/§1D "
    "+ §4 port notes. **EXPLORATORY_NONCERTIFYING — FIT era only (2021-2024), "
    "no promotion claims.** Inputs: the S3 skeleton shards (queried, never the "
    "tape), the S1-v2 union roster, walls.json, the census_a session cost "
    "medians. Every number carries its source `file:line`." % S.SPEC_SHA16)


def _f(r, t, c):
    v = r[t.i(c)]
    try:
        return float(v)
    except (TypeError, ValueError):
        return float("nan")


def main():
    sc = Tsv(S.out_path("screen_ledger.tsv"))
    gm = Tsv(S.out_path("grid_members.tsv"))
    gp = Tsv(S.out_path("grid_prunes.tsv"))
    dg = Tsv(S.out_path("shadow_degeneracy.tsv"))
    cf = Tsv(S.out_path("confirm_fits.tsv"))
    L = ["# PORT M1.B S4 — ATLAS SCREEN", "", HEADER, ""]
    if not sc:
        L.append("_screen not yet complete_")
        open(OUT, "w").write("\n".join(L) + "\n")
        return 1

    # ------------------------------------------------------------ the grid --
    L.append("## The enumerated grid and its prunes\n")
    rows = []
    for a in S.ASSETS:
        d = {r[gp.i("prune")]: r[gp.i("n")] for r in gp.rows
             if r[gp.i("asset")] == a}
        ln = [ln for r, ln in zip(gp.rows, gp.lines)
              if r[gp.i("asset")] == a]
        if not d:
            continue
        rows.append([a, d.get("UNIVERSE_ROWS", "n/a"), d.get("KEPT", "n/a")]
                    + [d.get("P%d" % i, "0") for i in range(1, 11)]
                    + [cite(gp, ln[0])])
    L.append(md_table(["asset", "universe rows (FIT x 25%)", "labels kept"]
                      + ["P%d" % i for i in range(1, 11)] + ["source"], rows))
    L.append("\nP1-P8 are the structural prunes of LABEL_ATLAS_V2 §1B "
             "(P1 `net_best` — vacuous here, the port grid has no `best` "
             "horizon; P2/P3 shaping only on dollar bases; **P4 truncation XOR "
             "penalty**; P5 `rank(truncate(x)) == rank(x)`; P6 binarising an "
             "already-shaped value; P7 rank/z/winsor on a binary or ordinal "
             "base; P8 vacuous with P1). P9 drops constant / all-NaN / "
             "minority-class<1% members, P10 collapses byte-identical ones.\n")

    # ------------------------------------------------------------- guards ---
    L.append("## Guards\n")
    n_void = sum(1 for r in sc.rows if r[sc.i("voided_by_twin")] == "1")
    n_shuf = sum(1 for r in sc.rows if r[sc.i("shuffled_twin")] == "1")
    n_occ = sum(1 for r in sc.rows if r[sc.i("occupancy_derived")] == "1"
                and r[sc.i("shuffled_twin")] == "0")
    L.append("* **F-PROX barred** (§4.3 A13): `assert_no_fprox()` runs over "
             "every enumerated member before any fit, and the bar is also "
             "STRUCTURAL — the label/screen process never imports the "
             "oracle-leg machinery, and the guard raises if it is loaded "
             "(`engine/port_m1b/s4_labels.py`, red-first in "
             "`engine/port_m1b/test_s4.py`).\n"
             "* **Shuffle twins** (§1D): %d occupancy/oracle-derived arms, %d "
             "within-session-shuffled twins fitted at identical budget, **%d "
             "arms VOIDED** by their twin.\n" % (n_occ, n_shuf, n_void))
    if dg:
        rows = []
        for r, ln in zip(dg.rows, dg.lines):
            rows.append([r[dg.i("asset")], r[dg.i("mark")],
                         num(r, dg, "occupancy_ratio_median", "%.3f"),
                         num(r, dg, "spearman_shadow_vs_net", "%.4f"),
                         num(r, dg, "n_scored", "%.0f"),
                         r[dg.i("verdict")] or "channel is distinct",
                         cite(dg, ln)])
        L.append(md_table(["asset", "mark", "occupancy ratio",
                           "Spearman(shadow, net) within session", "n",
                           "verdict", "source"], rows))
        L.append("\nThe degeneracy check is run PER MARK (LABEL_ATLAS_V2 §4.2: "
                 "in a 23h session the occupancy ratio is a property of the "
                 "mark, not of the label).\n")

    # --------------------------------------------- learnability vs economics -
    L.append("## Learnability is not economic alignment (the transferable "
             "finding, re-measured)\n")
    rows = []
    for a in S.ASSETS:
        rs = [r for r in sc.rows if r[sc.i("asset")] == a
              and r[sc.i("shuffled_twin")] == "0"]
        if not rs:
            continue
        rho = [_f(r, sc, "rho_median_learnability") for r in rs]
        al = [_f(r, sc, "align_spearman_unit") for r in rs]
        rho = np.array(rho)
        al = np.array(al)
        ok = np.isfinite(rho) & np.isfinite(al)
        best_rho = rs[int(np.nanargmax(rho))]
        best_al = rs[int(np.nanargmax(al))]
        cc = float(np.corrcoef(rho[ok], al[ok])[0, 1]) if ok.sum() > 10 \
            else float("nan")
        rows.append([a, int(ok.sum()), "%.4f" % np.nanmedian(rho),
                     "%.4f" % np.nanmedian(al), "%.3f" % cc,
                     best_rho[sc.i("label")],
                     "%.4f" % _f(best_rho, sc, "align_spearman_unit"),
                     best_al[sc.i("label")],
                     "%.4f" % _f(best_al, sc, "rho_median_learnability")])
    L.append(md_table(["asset", "labels", "median learnability rho",
                       "median economic alignment", "corr(rho, alignment)",
                       "most LEARNABLE label", "its alignment",
                       "best ALIGNED label", "its learnability"], rows))
    L.append("\nSource: `%s`. The recovered atlas's single most transferable "
             "finding (§2.2/§4.5.4) reproduces on futures: the most LEARNABLE "
             "labels are path-geometry ones (first passage, time-to-peak, "
             "giveback: rho 0.40-0.48) and their economic alignment is "
             "indistinguishable from zero, while the best ALIGNED labels are "
             "the MOVER-GATED RETENTION cells with learnability an order of "
             "magnitude lower. Screening on learnability alone would have "
             "picked exactly the wrong family.\n" % sc.rel())

    # ------------------------------------------------------------- top-25 ---
    for a in S.ASSETS:
        rs = [(r, ln) for r, ln in zip(sc.rows, sc.lines)
              if r[sc.i("asset")] == a and r[sc.i("shuffled_twin")] == "0"
              and r[sc.i("voided_by_twin")] == "0"
              and np.isfinite(_f(r, sc, "align_spearman_unit"))]
        if not rs:
            continue
        rs.sort(key=lambda x: -_f(x[0], sc, "align_spearman_unit"))
        L.append("\n## %s — top 25 by economic alignment\n" % a)
        rows = []
        for r, ln in rs[:25]:
            rows.append([r[sc.i("label")], r[sc.i("family")],
                         r[sc.i("horizon")], r[sc.i("ranking_unit")] or "-",
                         num(r, sc, "align_spearman_unit", "%.4f"),
                         num(r, sc, "rho_median_learnability", "%.4f"),
                         num(r, sc, "dollar_recall_at3", "%.4f"),
                         num(r, sc, "dollar_recall_at10", "%.4f"),
                         num(r, sc, "era_sign_consistency", "%.2f"),
                         r[sc.i("holm_significant")], cite(sc, ln)])
        L.append(md_table(["label", "family", "horizon", "unit",
                           "economic alignment", "learnability",
                           "$recall@3", "$recall@10", "era sign consistency",
                           "Holm sig", "source"], rows))

    # ------------------------------------------------------ family medians --
    L.append("\n## Family-level medians (all assets pooled)\n")
    fam = {}
    for r in sc.rows:
        if r[sc.i("shuffled_twin")] == "1":
            continue
        f = r[sc.i("family")]
        fam.setdefault(f, []).append((_f(r, sc, "rho_median_learnability"),
                                      _f(r, sc, "align_spearman_unit"),
                                      _f(r, sc, "dollar_recall_at10")))
    rows = []
    for f in sorted(fam):
        v = np.array(fam[f], dtype=float)

        def med(col, v=v):
            c = v[:, col]
            c = c[np.isfinite(c)]
            return ("%.4f" % np.median(c)) if c.size else "n/a"
        rows.append([f, v.shape[0], med(0), med(1), med(2)])
    L.append(md_table(["family", "members", "median learnability",
                       "median alignment", "median $recall@10"], rows))
    L.append("\nThe `triple_barrier_control` family is the literature CONTROL "
             "the recovered census called it (§4.3 A10) — reported at its "
             "measured expectation, never promoted.\n")

    # ------------------------------------------------------------- Holm -----
    L.append("## Holm multiplicity ledger\n")
    rows = []
    for a in S.ASSETS:
        rs = [r for r in sc.rows if r[sc.i("asset")] == a]
        if not rs:
            continue
        sig = sum(1 for r in rs if r[sc.i("holm_significant")] == "1")
        rows.append([a, len(rs), sig, "%.3g" % (0.05 / max(len(rs), 1))])
    L.append(md_table(["asset", "trials in the family", "Holm-significant",
                       "smallest threshold (0.05/m)"], rows))
    L.append("\nThe Holm family is the FULL enumerated grid per asset, on the "
             "economic-alignment Spearman p-value.\n")

    # ---------------------------------------------------------- confirm -----
    if cf:
        L.append("## Confirm fits (per-fold HP search, 32 configs)\n")
        rows = []
        for a in S.ASSETS:
            rs = [(r, ln) for r, ln in zip(cf.rows, cf.lines)
                  if r[cf.i("asset")] == a]
            rs.sort(key=lambda x: -_f(x[0], cf, "confirm_align"))
            for r, ln in rs[:12]:
                rows.append([a, r[cf.i("label")], r[cf.i("selection_reason")],
                             num(r, cf, "screen_align", "%.4f"),
                             num(r, cf, "confirm_align", "%.4f"),
                             num(r, cf, "delta_align_vs_screen", "%+.4f"),
                             num(r, cf, "confirm_dollar_recall_at10", "%.4f"),
                             cite(cf, ln)])
        L.append(md_table(["asset", "label", "selected because",
                           "screen alignment", "confirm alignment", "delta",
                           "$recall@10", "source"], rows))
        L.append("\nThe screen→confirm DELTA is reported because the recovered "
                 "atlas measured a screen→confirm REVERSAL (§2.5): a label's "
                 "screen rank is not its confirm rank. M2 consumes these rows; "
                 "S4 promotes nothing.\n")

    L.append("""## Pinned readings and defects (S4)

1. **`0.15 x ATR` is off the S3 ladder.** The ladder is `k x 0.02 x ATR`, so
   the spec's triple-barrier `sl = 0.15 x ATR` is `k = 7.5`. Pinned: round
   HALF-UP to `k = 8` (`0.16 x ATR`), the realised theta is carried in the
   member's `params` column. Every other theta in the spec grid
   ({0.1,0.2,0.4,0.6,1.0}) is an exact ladder multiple.
2. **`uw_share` has no horizon axis.** S3 stores time-underwater over the whole
   observed window only, and S4 may not re-read the tape, so the dwell family
   is emitted at `sess_close` alone. Adding per-horizon dwell needs an S3 field,
   not an S4 workaround.
3. **`cfa_wait_K` is emitted in BOTH readings.** The spec says "cfa_wait_K
   K in {60m, phase} (d1 anchor)": `cfa_d1` is the direct WAIT probe
   (net at d0 minus net at the d1 anchor, which is what S3 built d1 for) and
   `cfa_wait_60m`/`cfa_wait_phase` are the recovered §1B B6 form (regret vs the
   best LATER action in the same session inside K). Both are scored; the
   orchestrator can retire either.
4. **eps grid.** `retention` carries the full eps ladder {1,5,15,30} x cost_rt
   (both plain and mover-gated); the §1C C2-C7 ratio subfamilies are emitted at
   the champion-class eps = 5 x cost_rt only, to keep the fit budget on the
   axes the spec names.
5. **Ranking unit** is a first-class axis exactly as §4.5.2 requires: it
   multiplies only the WITHIN-UNIT transforms (z / rank / winsor) — `raw` and
   `bin0` are unit-free by construction, so pairing them with a unit would
   create P10 duplicates.
6. **Economic alignment is measured within the label's OWN ranking unit**
   (unit-free labels are scored at `session`), against `net_phase_close` and
   the $900 walled certificate — both re-derived per asset, never copied.
""")
    with open(OUT, "w") as fh:
        fh.write("\n".join(L) + "\n")
    print(OUT)
    return 0


if __name__ == "__main__":
    sys.exit(main())
