#!/usr/bin/python3
"""PORT M0 s5_report — spec §10.  Generates m0/M0_REPORT.md; never hand-written.

Reads only census outputs (no payload, no receipts) and renders:
gate table per asset (cost verdict on the phases carrying >=80% of phase-close
DP seated value, offer floor, seatable floor, recall), era breakdowns, NKD
ex-roll splits, the UTC-day <-> session comparability delta, the s1 repro
receipt echo, correlations, throughput, wall stability, and the per-trade vs
per-day bind note.

The orchestrator (not this lane) writes PORT_M0_VERDICT.md from this report.
"""
import json
import os
import sys

import numpy as np

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import common as C
import census_common as X

SECTION = "§10 s5_report"
VERDICT_RANK = {"GREEN": 0, "CAUTION": 1, "RED": 2, "INSUFFICIENT_BOOK": 3,
                "NO_DATA": 4, "": 5}


def read_tsv(path):
    if not os.path.exists(path):
        return []
    cols, out = None, []
    with open(path) as fh:
        for line in fh:
            if line.startswith("#"):
                continue
            f = line.rstrip("\n").split("\t")
            if cols is None:
                cols = f
                continue
            out.append(dict(zip(cols, f)))
    return out


def fnum(v, fmt="%.2f"):
    if v is None or v == "":
        return "-"
    try:
        x = float(v)
    except (TypeError, ValueError):
        return str(v)
    if not np.isfinite(x):
        return "-"
    return fmt % x


def _f(v):
    try:
        x = float(v)
        return x if np.isfinite(x) else float("nan")
    except (TypeError, ValueError):
        return float("nan")


def table(cols, rows):
    out = ["| " + " | ".join(cols) + " |",
           "|" + "|".join(["---"] * len(cols)) + "|"]
    for r in rows:
        out.append("| " + " | ".join(str(c) for c in r) + " |")
    return out


# ------------------------------------------------------------- gate logic ---
def dominant_phases(phase_value, asset, era=X.ERA_ALL, need=0.80):
    """Smallest phase set whose cumulative share of phase-close DP seated value
    reaches `need` (§10)."""
    rows = [r for r in phase_value if r["asset"] == asset and r["era"] == era]
    rows.sort(key=lambda r: (-_f(r["share"]), r["phase"]))
    got, out = 0.0, []
    for r in rows:
        s = _f(r["share"])
        if not np.isfinite(s):
            continue
        out.append(r["phase"])
        got += s
        if got >= need:
            break
    return out, got


def asset_cost_verdict(cost_rollup, asset, phases):
    """Worst §1 verdict among the phases that carry the seated value (§10)."""
    worst, detail = None, []
    for r in cost_rollup:
        if r["asset"] != asset or r["era"] != X.ERA_ALL or r["split"] != "all":
            continue
        if r["phase"] not in phases:
            continue
        v = r["verdict"]
        detail.append("%s=%s($%s)" % (r["phase"], v or "-",
                                      fnum(r["cost_rt_pooled"])))
        if worst is None or VERDICT_RANK.get(v, 5) > VERDICT_RANK.get(worst, 5):
            worst = v
    return (worst or "NO_DATA"), "; ".join(sorted(detail))


def pick(rows, **kw):
    for r in rows:
        if all(r.get(k) == v for k, v in kw.items()):
            return r
    return {}


# ------------------------------------------------------------------ render --
def build(out_root=None):
    out_root = out_root or C.OUT_ROOT
    a_roll = read_tsv(os.path.join(out_root, "census_a_cost_rollup.tsv"))
    b_roll = read_tsv(os.path.join(out_root, "census_b_rollup.tsv"))
    b_corr = read_tsv(os.path.join(out_root, "census_b_correlations.tsv"))
    c_roll = read_tsv(os.path.join(out_root, "census_c_rollup.tsv"))
    c_phase = read_tsv(os.path.join(out_root, "census_c_phase_value.tsv"))
    c_wall = read_tsv(os.path.join(out_root, "census_c_wall_stability.tsv"))
    c_seat = read_tsv(os.path.join(out_root, "census_c_seatable.tsv"))
    d_rec = read_tsv(os.path.join(out_root, "census_d_recall.tsv"))
    assets = [a for a in C.ASSET_ORDER
              if any(r["asset"] == a for r in a_roll)]

    walls = {}
    wp = os.path.join(out_root, "walls.json")
    if os.path.exists(wp):
        with open(wp) as fh:
            walls = json.load(fh).get("walls", {})

    L = []
    L.append("# PORT M0 — census report (generated by engine/port_m0/s5_report.py)")
    L.append("")
    L.append("Spec: `design/PORT_M0_CENSUS_SPEC.md` sha16 `%s` (§6-§10 + CC-M0-1). "
             "git `%s`." % (X.SPEC_SHA16, C.git_sha()[:12]))
    L.append("")
    L.append("All numbers below are generated. Gates are the §1 pre-registered "
             "constants — never tuned after the numbers were seen. "
             "`cost_rt = 1 x median two-sided spread ($) + $%.2f`." % C.FEES_RT)
    L.append("")

    # ---------------------------------------------------------- gate table --
    L.append("## 1. Gate table per asset (§1 / §10)")
    L.append("")
    rows = []
    for a in assets:
        phases, share = dominant_phases(c_phase, a)
        cv, cdetail = asset_cost_verdict(a_roll, a, phases)
        bo = pick(b_roll, asset=a, convention="SESSION", window="FULL",
                  era=X.ERA_ALL, split="all", measure="best_leg")
        cs = pick(c_roll, asset=a, era=X.ERA_ALL, split="all")
        dr = pick(d_rec, asset=a, era=X.ERA_ALL, variant="PIVOT_TO_PIVOT")
        da = pick(d_rec, asset=a, era=X.ERA_ALL, variant="ANCHORED")
        recall_cell = "%s / %s (n=%s)" % (fnum(dr.get("recall_1000"), "%.3f"),
                                          dr.get("gate_recall_ge_0.95", "-"),
                                          dr.get("n_legs", "0"))
        if not dr or int(dr.get("n_legs", 0) or 0) == 0:
            recall_cell = ("NO STRICT LEGS — anchored diag %s (n=%s)"
                           % (fnum(da.get("recall_1000"), "%.3f"),
                              da.get("n_legs", "0")))
        w = walls.get(a, {})
        rows.append([
            a, cv,
            "%s (%.0f%% of seated value)" % ("+".join(phases) if phases else "-",
                                             100 * share),
            "$%s / %s" % (fnum(bo.get("median")), bo.get("gate_median_ge_2500", "-")),
            "$%s / %s" % (fnum(cs.get("seatable_close_median")),
                          cs.get("gate_seatable_close_median_ge_2500", "-")),
            recall_cell,
            "$%s" % fnum(w.get("wall_usd"), "%.0f")])
    L += table(["asset", "cost verdict", "phases carrying >=80% seated value",
                "offer floor (median full-session best_leg, >=$2,500)",
                "seatable floor (median phase-close DP, >=$2,500)",
                "recall @$1,000 (>=0.95)", "wall"], rows)
    L.append("")
    L.append("Cost verdict detail (era ALL, split all): " +
             " · ".join("%s: %s" % (a, asset_cost_verdict(
                 a_roll, a, dominant_phases(c_phase, a)[0])[1]) for a in assets))
    L.append("")

    # ------------------------------------------------------------ cost (§6) --
    L.append("## 2. Cost census (§6)")
    L.append("")
    rows = []
    for r in a_roll:
        if r["split"] != "all" or r["era"] != X.ERA_ALL:
            continue
        rows.append([r["asset"], r["phase"], r["n_sessions"],
                     fnum(r["spread_med_usd_pooled"]),
                     fnum(r["spread_med_ticks_pooled"], "%.2f"),
                     fnum(r["spread_p90_usd_pooled"]),
                     fnum(r["cost_rt_pooled"]),
                     fnum(r["cost_share"], "%.4f"),
                     fnum(r["excluded_frac_pooled"], "%.4f"),
                     fnum(r["top_size_p10_med"], "%.1f"),
                     r["verdict"] or "-"])
    L += table(["asset", "phase", "sessions", "median spread $",
                "median spread ticks", "p90 spread $", "cost_rt $",
                "cost share of $1,000", "excluded frac", "top_size p10",
                "verdict"], rows)
    L.append("")
    L.append("### 2b. Cost by era (phase ALL = session-scoped)")
    L.append("")
    rows = [[r["asset"], r["era"], r["split"], r["n_sessions"],
             fnum(r["spread_med_usd_pooled"]), fnum(r["cost_rt_pooled"]),
             fnum(r["cost_share"], "%.4f")]
            for r in a_roll if r["phase"] == "ALL"]
    L += table(["asset", "era", "split", "sessions", "median spread $",
                "cost_rt $", "cost share"], rows)
    L.append("")

    # ----------------------------------------------------------- offer (§7) --
    L.append("## 3. Offer census (§7)")
    L.append("")
    rows = []
    for r in b_roll:
        if r["convention"] != "SESSION" or r["split"] != "all":
            continue
        if r["measure"] not in ("best_leg", "range"):
            continue
        if r["window"] != "FULL":
            continue
        rows.append([r["asset"], r["era"], r["measure"], r["n_sessions"],
                     fnum(r["mean"]), fnum(r["median"]), fnum(r["p25"]),
                     fnum(r["p75"]), r["gate_median_ge_2500"] or "-"])
    L += table(["asset", "era", "measure", "sessions", "mean $", "median $",
                "p25 $", "p75 $", "gate (median>=$2,500)"], rows)
    L.append("")
    L.append("### 3b. Era thinness (year x median full-session best_leg)")
    L.append("")
    years = sorted({r["era"] for r in b_roll if r["era"].isdigit()})
    rows = []
    for a in assets:
        row = [a]
        for y in years:
            r = pick(b_roll, asset=a, convention="SESSION", window="FULL",
                     era=y, split="all", measure="best_leg")
            row.append(fnum(r.get("median")))
        rows.append(row)
    L += table(["asset"] + years, rows)
    L.append("")
    L.append("### 3c. Windows (era ALL, split all, median $)")
    L.append("")
    rows = []
    for a in assets:
        for m in ("range", "best_leg", "legs_1k"):
            row = [a, m]
            for w in X.WINDOWS:
                r = pick(b_roll, asset=a, convention="SESSION", window=w,
                         era=X.ERA_ALL, split="all", measure=m)
                row.append(fnum(r.get("median"), "%.2f"))
            rows.append(row)
    L += table(["asset", "measure"] + list(X.WINDOWS), rows)
    L.append("")

    # ------------------------------------------- UTC-day comparability delta --
    L.append("## 4. UTC-day <-> session comparability delta (§7/§10)")
    L.append("")
    rows = []
    for a in assets:
        for w in ("FULL", "RTH"):
            for m in ("range", "best_leg"):
                s = pick(b_roll, asset=a, convention="SESSION", window=w,
                         era=X.ERA_ALL, split="all", measure=m)
                u = pick(b_roll, asset=a, convention="UTC_DAY", window=w,
                         era=X.ERA_ALL, split="all", measure=m)
                sm, um = _f(s.get("median")), _f(u.get("median"))
                d = sm - um
                rows.append([a, w, m, fnum(sm), fnum(um), fnum(d),
                             fnum(100 * d / um if um else float("nan"), "%.2f")])
    L += table(["asset", "window", "measure", "session median $",
                "UTC-day median $", "delta $", "delta %"], rows)
    L.append("")

    # -------------------------------------------------------- seatable (§8) --
    L.append("## 5. Seatable / occupancy DP (§8) and throughput")
    L.append("")
    rows = []
    for r in c_roll:
        if r["split"] != "all":
            continue
        rows.append([r["asset"], r["era"], r["n_sessions"],
                     fnum(r["seatable_close_median"]),
                     fnum(r["seatable_close_mean"]),
                     fnum(r["seatable_peak_median"]),
                     fnum(r["n_seated_per_day_median_close"], "%.1f"),
                     fnum(r["seated_per_trade_mean_close"]),
                     fnum(r["candidates_per_day_median"], "%.1f"),
                     fnum(r["one_k_class_per_day_median"], "%.1f"),
                     r["gate_seatable_close_median_ge_2500"] or "-"])
    L += table(["asset", "era", "sessions", "phase-close DP median $",
                "phase-close DP mean $", "peak-exit DP median $",
                "seated/day (median)", "seated $/trade (mean)",
                "candidates/day (median)", "$1k-class/day (median)",
                "gate"], rows)
    L.append("")
    L.append("### 5b. Seated value by phase (phase-close DP, era ALL)")
    L.append("")
    rows = [[r["asset"], r["phase"], fnum(r["seated_close_usd"], "%.0f"),
             fnum(r["share"], "%.3f")]
            for r in c_phase if r["era"] == X.ERA_ALL]
    L += table(["asset", "phase", "seated $", "share"], rows)
    L.append("")

    # ------------------------------------------------------------ wall (§8) --
    L.append("## 6. Wall stability (§1 / §8 sub-pass 2)")
    L.append("")
    rows = [[r["asset"], r["year"], r["n_winners"],
             fnum(r["mae_before_peak_p95"]), fnum(r["mae_before_peak_p99"]),
             r["note"] or "-"] for r in c_wall]
    L += table(["asset", "year", "winners (MFE>=$1,000)", "MAE-before-peak p95",
                "p99", "note"], rows)
    L.append("")
    L.append("Wall = min(round_$25(pooled p99 over %s), $%.0f); 2025 is excluded "
             "from the fit (§8 sub-pass 2) and evaluated under the same wall."
             % ("-".join(str(y) for y in (X.WALL_FIT_YEARS[0],
                                          X.WALL_FIT_YEARS[-1])), X.WALL_CAP))
    L.append("")

    # ---------------------------------------------------------- recall (§9) --
    L.append("## 7. Recall census (§9)")
    L.append("")
    rows = []
    for r in d_rec:
        rows.append([r["asset"], r["era"], r["variant"], r["n_legs"],
                     fnum(r["recall_900"], "%.3f"), fnum(r["recall_1000"], "%.3f"),
                     fnum(r["recall_1100"], "%.3f"),
                     fnum(r["recall_1000_screened"], "%.3f"),
                     r["gate_recall_ge_0.95"] or "-",
                     r["miss_NO_CANDIDATE_IN_LEG"], r["miss_WRONG_SIDE"],
                     r["miss_TOO_LATE"], r["miss_STALE_BOOK"],
                     r["miss_UNTRADEABLE_SPREAD_screened"]])
    L += table(["asset", "era", "variant", "legs", "recall $900", "recall $1,000",
                "recall $1,100", "recall $1,000 screened", "gate",
                "miss: no candidate", "miss: wrong side", "miss: too late",
                "miss: stale book", "miss: untradeable spread"], rows)
    L.append("")
    L.append("PIVOT_TO_PIVOT is the spec-primary variant (§9 'legs = consecutive "
             "pivot-to-pivot moves'); ANCHORED is a diagnostic that adds the "
             "session-open anchor and the final unconfirmed extreme, because a "
             "1.0 x ATR14 confirmation threshold rarely completes two confirmed "
             "pivots inside one session.")
    L.append("")

    # ------------------------------------------------------- NKD ex-roll ----
    L.append("## 8. NKD roll-week splits (§6/§7/§8)")
    L.append("")
    rows = []
    for era in (X.ERA_ALL, X.ERA_FIT, X.ERA_GATE):
        for split in ("all", "ex_roll_week"):
            a = pick(a_roll, asset="NKD", phase="ALL", era=era, split=split)
            b = pick(b_roll, asset="NKD", convention="SESSION", window="FULL",
                     era=era, split=split, measure="best_leg")
            c = pick(c_roll, asset="NKD", era=era, split=split)
            rows.append([era, split, a.get("n_sessions", "-"),
                         fnum(a.get("cost_rt_pooled")), fnum(b.get("median")),
                         fnum(c.get("seatable_close_median"))])
    L += table(["era", "split", "sessions", "cost_rt $",
                "median best_leg $", "median phase-close DP $"], rows)
    L.append("")

    # ------------------------------------------------------ correlations ----
    L.append("## 9. Cross-asset correlations (§7)")
    L.append("")
    rows = [[r["pair"], r["series"], r["n"], fnum(r["pearson"], "%.4f"),
             fnum(r["spearman"], "%.4f")] for r in b_corr]
    L += table(["pair", "series", "n", "Pearson", "Spearman"], rows)
    L.append("")

    # -------------------------------------------------- per-trade/day bind --
    L.append("## 10. Per-trade vs per-day bind (D-021 + D-048, §10)")
    L.append("")
    rows = []
    for a in assets:
        c = pick(c_roll, asset=a, era=X.ERA_ALL, split="all")
        pt = _f(c.get("seated_per_trade_mean_close"))
        nd = _f(c.get("n_seated_per_day_median_close"))
        rows.append([a, fnum(pt), fnum(nd, "%.1f"),
                     fnum(c.get("seatable_close_median")),
                     "OK" if (np.isfinite(pt) and pt >= 1050.0) else "BIND"])
    L += table(["asset", "seated $/trade (mean, phase-close DP)",
                "seated trades/day (median)", "seatable/day median $",
                "co-hold (>= ~$1,050/trade)"], rows)
    L.append("")
    L.append("D-021 needs >=$600/trade (target >$1,000) and D-048 needs "
             ">$2,000/session on ONE mini with one position at a time (D-046). "
             "Seated certificates must average roughly >=$1,050 gross for both "
             "to co-hold; a BIND row means the per-day number is being made of "
             "trades too small to satisfy the per-trade law.")
    L.append("")

    # --------------------------------------------------- receipts / checks --
    L.append("## 11. Receipt echo and acceptance checks (§11)")
    L.append("")
    rp = os.path.join(C.OUT_ROOT, "repro_si2024.receipt.json")
    if os.path.exists(rp):
        with open(rp) as fh:
            rr = json.load(fh)
        L.append("**s1 SI-2024 fingerprint (§3, THE acceptance gate):** verdict "
                 "`%s`, winning rule `%s`." % (rr.get("verdict"),
                                               rr.get("winning_rule")))
        st = rr.get("stats") or {}
        if st:
            L.append("")
            L.append("```")
            L.append(json.dumps(st, sort_keys=True, indent=1))
            L.append("```")
    else:
        L.append("**s1 repro receipt missing.**")
    L.append("")
    for name, label in (("byte_identity_A.tsv", "Byte-identity A (§4, s2 re-decode)"),
                        ("byte_identity_B.tsv", "Byte-identity B (§10, census re-run on 2024-06)"),
                        ("yahoo_spotcheck.tsv", "Yahoo spot-check (§11.3)"),
                        ("integrity_flags.tsv", "Integrity flags (§4)")):
        rows = read_tsv(os.path.join(C.OUT_ROOT, name))
        if not rows:
            L.append("- %s: file absent or empty." % label)
            continue
        bad = [r for r in rows
               if (r.get("verdict") not in (None, "MATCH", "OK"))]
        L.append("- %s: %d rows, %d not MATCH/OK.%s"
                 % (label, len(rows), len(bad),
                    ("" if not bad else " Flags: "
                     + ", ".join(sorted({r.get("flag", r.get("verdict", "?"))
                                         for r in bad}))[:400])))
    L.append("")
    L.append("Sessions certified: " + ", ".join(
        "%s=%d" % (a, sum(1 for r in c_seat if r["asset"] == a)) for a in assets))
    L.append("")
    return "\n".join(L) + "\n"


def run(out_root=None):
    out_root = out_root or C.OUT_ROOT
    txt = build(out_root)
    p = X.out_path(out_root, "M0_REPORT.md")
    tmp = p + ".tmp"
    with open(tmp, "w") as fh:
        fh.write(txt)
    os.replace(tmp, p)
    C.hb("s5: wrote %s (%d bytes)" % (p, len(txt)))
    return p


def main():
    X.verify_spec()
    run()
    return 0


if __name__ == "__main__":
    sys.exit(main())
