"""Hand-built refusal fixtures for the disc native differential gate.

A native rebuild has to reproduce the oracle's REFUSALS as exactly as its
numbers: the callers upstream branch on them (confirmation.py:1144-1146 and
:1268-1270 both wrap a DiscretionaryFeatureRefusal into a ConfirmationRefusal
whose text embeds the original message), so a drifted message is a drifted
control-flow contract, not cosmetics.

Every expected (type, message) pair below is written out BY HAND from the
frozen source, with its file:line, and never read from the module under test.
A fixture whose expectation is generated by the producer is a mirror
assertion — green whether the contract holds or not.

The inputs are real: the fixtures perturb one captured session's recorded
construction/query so the refusal is reached through the same public surface
confirmation.py uses, not through a synthetic stand-in that might miss it.
"""

from __future__ import annotations

import copy
from dataclasses import dataclass
from typing import Mapping, Sequence

import numpy as np

from engine.entry_v2.disc_native_builders import DiscSessionCapture, StoreSession
from engine.entry_v2.disc_native_differential import (
    RefusalObservation, observe_disc_native_refusal)
from engine.entry_v2.discretionary_features import (
    CausalDiscretionaryPlane, PriorSessionContext)

NANOS_PER_SECOND = 1_000_000_000
PRIOR_FIXTURE_ROW_COUNT = 4096
NON_FINITE_MULTIPLIER = 10 ** 308


@dataclass(frozen=True, slots=True)
class DiscRefusalFixture:
    """One refusal site: the input that reaches it and what it must say."""

    name: str
    site: str
    kind: str
    construction: Mapping[str, object]
    query: Mapping[str, object] | None
    prior_rows: np.ndarray | None
    prior_kwargs: Mapping[str, object] | None
    expected: RefusalObservation


def run_oracle_refusal(fixture: DiscRefusalFixture) -> RefusalObservation:
    """Drive the frozen Python path at the fixture's refusal site."""

    if fixture.kind == "PRIOR":
        return observe_disc_native_refusal(
            PriorSessionContext, rows=fixture.prior_rows,
            **dict(fixture.prior_kwargs or {}))
    if fixture.kind == "CONSTRUCTION":
        return observe_disc_native_refusal(
            CausalDiscretionaryPlane, **dict(fixture.construction))

    def _query() -> None:
        plane = CausalDiscretionaryPlane(**dict(fixture.construction))
        plane.feature_map(**dict(fixture.query or {}))

    return observe_disc_native_refusal(_query)


def build_disc_refusal_fixtures(
    capture: DiscSessionCapture, session: StoreSession,
) -> tuple[DiscRefusalFixture, ...]:
    """The six documented refusal sites, driven from one real session."""

    construction = dict(capture.construction)
    query = dict(capture.queries[0])
    rows = np.asarray(construction["rows"])
    spec = session.spec
    if construction.get("prior_session") is None:
        raise ValueError(
            "refusal fixtures need a prior-present session; "
            f"{session.label} carries prior_session=None")
    prior_kwargs = {
        "asset": spec.asset,
        "trading_day": int(spec.previous_trading_day),
        "event_pack_sha256": spec.expected_previous_event_sha256,
        "raw_tick": int(construction["raw_tick"]),
        "multiplier": int(construction["multiplier"]),
    }
    return (
        _snapshot_outside_session(construction, query),
        _malformed_formation_candidate(construction, query),
        _prior_instrument_mismatch(construction, query, spec.asset),
        _non_finite_feature_map(construction, query),
        _prior_session_empty(rows, prior_kwargs),
        _prior_session_without_trusted_bbo(rows, prior_kwargs),
    )


def _snapshot_outside_session(
    construction: Mapping[str, object], query: Mapping[str, object],
) -> DiscRefusalFixture:
    """discretionary_features.py:2394-2395 — snapshot before the open."""

    outside = dict(query)
    outside["snapshot_ts_ns"] = int(construction["open_ns"]) - NANOS_PER_SECOND
    return DiscRefusalFixture(
        "snapshot-outside-session", "discretionary_features.py:2394-2395",
        "QUERY", construction, outside, None, None,
        RefusalObservation("DiscretionaryFeatureRefusal",
                           "snapshot is outside session"))


def _malformed_formation_candidate(
    construction: Mapping[str, object], query: Mapping[str, object],
) -> DiscRefusalFixture:
    """discretionary_features.py:2401-2403 — a crossed formation book."""

    malformed = dict(query)
    candidate = dict(malformed["formation_candidate"])  # type: ignore[arg-type]
    candidate["entry_ask_px"] = str(candidate["entry_bid_px"])
    malformed["formation_candidate"] = candidate
    return DiscRefusalFixture(
        "malformed-formation-candidate", "discretionary_features.py:2401-2403",
        "QUERY", construction, malformed, None, None,
        RefusalObservation("DiscretionaryFeatureRefusal",
                           "formation state is malformed"))


def _prior_instrument_mismatch(
    construction: Mapping[str, object], query: Mapping[str, object], asset: str,
) -> DiscRefusalFixture:
    """discretionary_features.py:508-513 — yesterday's book, wrong instrument."""

    mismatched = dict(construction)
    prior = copy.copy(construction["prior_session"])
    prior.asset = "SI" if asset != "SI" else "HG"
    mismatched["prior_session"] = prior
    return DiscRefusalFixture(
        "prior-instrument-mismatch", "discretionary_features.py:508-513",
        "CONSTRUCTION", mismatched, None, None, None,
        RefusalObservation("DiscretionaryFeatureRefusal",
                           "prior-session instrument identity differs"))


def _non_finite_feature_map(
    construction: Mapping[str, object], query: Mapping[str, object],
) -> DiscRefusalFixture:
    """discretionary_features.py:2692-2693 — the finite-output backstop.

    Reached by an in-type but absurd contract multiplier: `self.factor` is
    `0.5e-9 * float(multiplier)` (discretionary_features.py:504), so a
    multiplier at the float64 ceiling overflows the first USD-scaled product
    to inf while every other input stays exactly as the session recorded it.
    The value is the smallest power of ten that reaches the guard: 10**307
    leaves every product finite and the map returns normally (probed
    2026-08-21), 10**308 refuses.
    The prior session is dropped because the instrument-identity check at
    :508-513 would otherwise fire first on the changed multiplier.
    """

    overflowing = dict(construction)
    overflowing["multiplier"] = NON_FINITE_MULTIPLIER
    overflowing["prior_session"] = None
    return DiscRefusalFixture(
        "non-finite-feature-map", "discretionary_features.py:2692-2693",
        "QUERY", overflowing, query, None, None,
        RefusalObservation("DiscretionaryFeatureRefusal",
                           "discretionary feature map is non-finite"))


def _prior_session_empty(
    rows: np.ndarray, prior_kwargs: Mapping[str, object],
) -> DiscRefusalFixture:
    """discretionary_features.py:78-79 — a prior pack with no events."""

    return DiscRefusalFixture(
        "prior-session-empty", "discretionary_features.py:78-79",
        "PRIOR", {}, None, rows[:0].copy(), prior_kwargs,
        RefusalObservation("DiscretionaryFeatureRefusal",
                           "prior session is empty"))


def _prior_session_without_trusted_bbo(
    rows: np.ndarray, prior_kwargs: Mapping[str, object],
) -> DiscRefusalFixture:
    """discretionary_features.py:102-103 — events, but never a two-sided book.

    Zeroing both quote sides makes `raw_book` false on every row
    (discretionary_features.py:85-89), which is the physical shape of a
    holiday/reset pack: messages present, no economic BBO ever formed.
    """

    blinded = rows[:PRIOR_FIXTURE_ROW_COUNT].copy()
    blinded["bid_px"] = 0
    blinded["ask_px"] = 0
    return DiscRefusalFixture(
        "prior-session-no-trusted-bbo", "discretionary_features.py:102-103",
        "PRIOR", {}, None, blinded, prior_kwargs,
        RefusalObservation("DiscretionaryFeatureRefusal",
                           "prior session has no trusted BBO"))


def refusal_fixture_report(
    fixtures: Sequence[DiscRefusalFixture],
    observed: Sequence[RefusalObservation],
    parity: Sequence[RefusalObservation],
) -> list[dict[str, object]]:
    """One row per site: hand-written expectation, oracle, candidate."""

    return [{"fixture": fixture.name, "site": fixture.site,
             "kind": fixture.kind,
             "expected": fixture.expected.as_json(),
             "oracle": oracle.as_json(),
             "candidate": candidate.as_json()}
            for fixture, oracle, candidate
            in zip(fixtures, observed, parity)]


__all__ = [
    "DiscRefusalFixture", "build_disc_refusal_fixtures",
    "refusal_fixture_report", "run_oracle_refusal",
]
