#!/usr/bin/env python3
"""WP4 fixture generator — every qr_sources test fixture, written from scratch.

LAW (WP3 brief, inherited): "fixture files live under engine/cpp/tests/fixtures/,
generated by a committed script, never by hand-editing binaries without the
script".  Every parquet file under ``tests/fixtures/sources/`` is produced here,
including the deliberately-wrong ones: a wrong-schema fixture is built by asking
this writer for the wrongness, never by poking bytes into a good file.

INDEPENDENCE: the expected literals in ``source_expected_literals.tsv`` are
computed HERE, from the values this script encodes, by this script's own
arithmetic (cents x 10,000; lots x 100; ISO date -> day ordinal).  Nothing here
reads the C++ readers, and the C++ suite computes none of these numbers a second
way — it asserts these.

The parquet encoders (thrift compact, RLE/bit-packing hybrid, PLAIN,
RLE_DICTIONARY, ZSTD, page v1/v2) are imported from the WP3 generator
``make_parquet_fixtures.py``: one encoder, two fixture sets.

The fixture trees mirror the corpus layout (``<root>/<YYYY>/<day>.parquet`` and
``<root>/<YYYY>/<day>/exp<YYYY-MM-DD>.parquet``) so the readers' own path
forming — which only an admitted DayScope can drive — is exercised too.

Usage:
    python3 make_source_fixtures.py [--out-dir DIR] [--literals-path PATH]
"""

from __future__ import annotations

import argparse
import importlib.util
import os
import struct
import sys

HERE = os.path.dirname(os.path.abspath(__file__))

_spec = importlib.util.spec_from_file_location(
    "make_parquet_fixtures", os.path.join(HERE, "make_parquet_fixtures.py")
)
assert _spec is not None and _spec.loader is not None
wp3 = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(wp3)

Compact = wp3.Compact
MAGIC = wp3.MAGIC
NULL = None

TYPE_INT32, TYPE_INT64, TYPE_DOUBLE, TYPE_BYTE_ARRAY = (
    wp3.TYPE_INT32,
    wp3.TYPE_INT64,
    wp3.TYPE_DOUBLE,
    wp3.TYPE_BYTE_ARRAY,
)
CONVERTED_UTF8, CONVERTED_DATE, CONVERTED_INT_8, CONVERTED_UINT_32 = (
    wp3.CONVERTED_UTF8,
    wp3.CONVERTED_DATE,
    wp3.CONVERTED_INT_8,
    wp3.CONVERTED_UINT_32,
)
REP_OPTIONAL = wp3.REP_OPTIONAL
CODEC_ZSTD = wp3.CODEC_ZSTD
ENC_PLAIN, ENC_RLE, ENC_RLE_DICTIONARY = wp3.ENC_PLAIN, wp3.ENC_RLE, wp3.ENC_RLE_DICTIONARY

# ---------------------------------------------------------------------------
# session 125 — the clock every fixture is written against
# ---------------------------------------------------------------------------
# Registry row (accepted_compact_sessions.tsv line 127): day 2022-07-05,
# 390 bars, source_profile cent_int32.  Frame-B open = 2022-07-05T09:30 local
# = 1657013400000 ms; close = open + 390 * 60_000.
DAY = "2022-07-05"
YEAR = "2022"
OPEN_MS = 1657013400000
CLOSE_MS = OPEN_MS + 390 * 60_000  # 1657036800000

# The SECOND pinned session, and the reason it exists: session 187
# (2022-09-30, registry line 189) is inside the 125..749 scope and its
# `source_profile` is `dollar_float64`.  The dual-profile law is not a
# chronological one, so the only way to exercise the dollar half END TO END is
# a session whose own registry row declares it.  Frame-B open = day ordinal
# 19265 * 86,400,000 + 09:30.
DOLLAR_DAY = "2022-09-30"
DOLLAR_YEAR = "2022"
DOLLAR_OPEN_MS = 19265 * 86_400_000 + 34_200_000  # 1664530200000
DOLLAR_CLOSE_MS = DOLLAR_OPEN_MS + 390 * 60_000


class Leaf:
    def __init__(
        self,
        name: str,
        physical: int,
        values: list,
        converted: int | None = None,
        logical_timestamp: bool = False,
        dictionary: bool = False,
        statistics: bool = False,
    ) -> None:
        self.name = name
        self.physical = physical
        self.values = values
        self.converted = converted
        self.logical_timestamp = logical_timestamp
        self.dictionary = dictionary
        self.statistics = statistics


def timestamp_logical() -> Compact:
    """parquet.thrift LogicalType union, TIMESTAMP branch (field 8), MILLIS,
    isAdjustedToUTC = false — the naive (frame B) stamping every token corpus
    uses."""
    unit = Compact().struct(1, Compact())  # TimeUnit union: 1 = MILLIS
    timestamp = Compact().boolean(1, False).struct(2, unit)
    return Compact().struct(8, timestamp)


def build_file(leaves: list[Leaf], group_sizes: list[int], page_version: int = 1) -> bytes:
    total_rows = sum(group_sizes)
    for leaf in leaves:
        if len(leaf.values) != total_rows:
            raise ValueError(f"leaf {leaf.name} has {len(leaf.values)} values, expected {total_rows}")

    body = bytearray(MAGIC)
    row_group_structs: list[Compact] = []
    offset = 0
    for rows_in_group in group_sizes:
        lo, hi = offset, offset + rows_in_group
        offset = hi
        chunk_structs: list[Compact] = []
        group_bytes = 0

        for leaf in leaves:
            chunk_start = len(body)
            chunk_uncompressed = 0
            window = leaf.values[lo:hi]
            present = [v for v in window if v is not NULL]
            dictionary: list = []
            dict_offset = None
            encodings = [ENC_RLE, ENC_PLAIN]
            if leaf.dictionary:
                encodings = [ENC_PLAIN, ENC_RLE, ENC_RLE_DICTIONARY]
                seen: list = []
                for value in present:
                    if value not in seen:
                        seen.append(value)
                dictionary = seen
                dict_offset = len(body)
                raw = wp3.plain_encode(leaf.physical, dictionary)
                packed = wp3.zstd_compress(raw)
                header = wp3.dictionary_page_header(len(raw), len(packed), len(dictionary))
                body += header
                body += packed
                chunk_uncompressed += len(header) + len(raw)

            data_offset = len(body)
            levels = [0 if v is NULL else 1 for v in window]
            level_bytes = wp3.rle_runs(levels, 1)
            if leaf.dictionary:
                width = wp3.bit_width(max(len(dictionary) - 1, 0))
                indices = [dictionary.index(v) for v in present]
                value_bytes = bytes([width]) + wp3.rle_runs(indices, width)
                encoding = ENC_RLE_DICTIONARY
            else:
                value_bytes = wp3.plain_encode(leaf.physical, present)
                encoding = ENC_PLAIN

            if page_version == 1:
                raw = struct.pack("<I", len(level_bytes)) + level_bytes + value_bytes
                packed = wp3.zstd_compress(raw)
                header = wp3.page_header_v1(len(raw), len(packed), rows_in_group, encoding)
                payload = packed
                chunk_uncompressed += len(header) + len(raw)
            else:
                packed_values = wp3.zstd_compress(value_bytes)
                payload = level_bytes + packed_values
                header = wp3.page_header_v2(
                    len(level_bytes) + len(value_bytes),
                    len(payload),
                    rows_in_group,
                    len(window) - len(present),
                    rows_in_group,
                    encoding,
                    len(level_bytes),
                )
                chunk_uncompressed += len(header) + len(level_bytes) + len(value_bytes)
            body += header
            body += payload

            total_compressed = len(body) - chunk_start
            meta = (
                Compact()
                .i32(1, leaf.physical)
                .i32_list(2, encodings)
                .text_list(3, [leaf.name])
                .i32(4, CODEC_ZSTD)
                .i64(5, rows_in_group)
                .i64(6, chunk_uncompressed)
                .i64(7, total_compressed)
                .i64(9, data_offset)
            )
            if dict_offset is not None:
                meta.i64(11, dict_offset)
            if leaf.statistics and present:
                stats = (
                    Compact()
                    .i64(3, len(window) - len(present))
                    .binary(5, struct.pack("<q", max(present)))
                    .binary(6, struct.pack("<q", min(present)))
                )
                meta.struct(12, stats)
            chunk_structs.append(Compact().i64(2, chunk_start).struct(3, meta))
            group_bytes += total_compressed

        row_group_structs.append(
            Compact().struct_list(1, chunk_structs).i64(2, group_bytes).i64(3, rows_in_group)
        )

    schema_structs = [Compact().text(4, "root").i32(5, len(leaves))]
    for leaf in leaves:
        element = Compact().i32(1, leaf.physical).i32(3, REP_OPTIONAL).text(4, leaf.name)
        if leaf.converted is not None:
            element.i32(6, leaf.converted)
        if leaf.logical_timestamp:
            element.struct(10, timestamp_logical())
        schema_structs.append(element)

    footer = (
        Compact()
        .i32(1, 2)
        .struct_list(2, schema_structs)
        .i64(3, total_rows)
        .struct_list(4, row_group_structs)
        .text(6, "qr_sources_fixture_generator")
        .done()
    )
    return bytes(body) + footer + struct.pack("<I", len(footer)) + MAGIC


# ---------------------------------------------------------------------------
# B1 — stock quotes
# ---------------------------------------------------------------------------
#
# 20 rows in three row groups (8 + 8 + 4).  What each row is FOR:
#   0  the all-null sentinel row the corpus writes once per file
#   1  one millisecond before the open (premarket, excluded)
#   2,3   equal-time group A, two DIFFERENT rows (permutation is observable)
#   4     group B, one row
#   5,6   group C, two IDENTICAL rows (multiplicity is preserved)
#   7|8,9 group D, three rows STRADDLING the row-group boundary
#   10    group E
#   11    group F, with a null bid_exchange (a null field, not a broken row)
#   12    group G, the last millisecond before the close
#   13    the close itself (excluded: the window is half-open)
#   14,15 postmarket (excluded)
#   16-19 a whole row group after the close: PRUNED by its own statistics
QUOTE_TS = [
    NULL,
    OPEN_MS - 1,
    OPEN_MS, OPEN_MS,
    OPEN_MS + 1,
    OPEN_MS + 2, OPEN_MS + 2,
    OPEN_MS + 3,
    OPEN_MS + 3, OPEN_MS + 3,
    OPEN_MS + 10,
    OPEN_MS + 11,
    CLOSE_MS - 1,
    CLOSE_MS,
    CLOSE_MS + 1, CLOSE_MS + 2,
    CLOSE_MS + 3, CLOSE_MS + 4, CLOSE_MS + 5, CLOSE_MS + 6,
]
# lots on the tape (the pre-2025-11-03 era); the readers must emit x100 shares.
QUOTE_BID_SIZE = [NULL, 4, 5, 6, 7, 8, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21]
QUOTE_ASK_SIZE = [NULL, 3, 5, 7, 9, 11, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37]
QUOTE_BID_EXCHANGE = [NULL, 1, 1, 2, 3, 4, 4, 5, 6, 7, 8, NULL, 9, 10, 11, 12, 13, 14, 15, 16]
QUOTE_ASK_EXCHANGE = [NULL, 2, 2, 3, 4, 5, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18]
# integer cents; the readers must emit cents x 10,000.
QUOTE_BID_CENTS = [NULL, 17130, 17139, 17140, 17141, 17142, 17142, 17143, 17144, 17145,
                   17146, 17147, 17148, 17149, 17150, 17151, 17152, 17153, 17154, 17155]
QUOTE_ASK_CENTS = [NULL, 17135, 17149, 17150, 17151, 17152, 17152, 17153, 17154, 17155,
                   17156, 17157, 17158, 17159, 17160, 17161, 17162, 17163, 17164, 17165]
QUOTE_BID_CONDITION = [NULL] + [0] * 19
QUOTE_ASK_CONDITION = [NULL] + [0] * 19

QUOTE_GROUP_SIZES = [8, 8, 4]


def quote_derived_never_read(index: int) -> int:
    """Values for cols 9-15, which are NEVER READ. They are deliberately wrong
    as prices (mid is bid+ask, the changes are nonsense) so that a decoder that
    started reading them would produce different digests."""
    return 900_000 + index


def quote_timestamps(open_ms: int, close_ms: int) -> list:
    """The fixture's row structure, expressed against ANY session's window, so
    the same 20 rows can be written for either price profile's session."""
    return [
        NULL,
        open_ms - 1,
        open_ms, open_ms,
        open_ms + 1,
        open_ms + 2, open_ms + 2,
        open_ms + 3,
        open_ms + 3, open_ms + 3,
        open_ms + 10,
        open_ms + 11,
        close_ms - 1,
        close_ms,
        close_ms + 1, close_ms + 2,
        close_ms + 3, close_ms + 4, close_ms + 5, close_ms + 6,
    ]


def stock_quote_leaves(profile: str, rename: tuple[int, str] | None = None,
                       retype: tuple[int, int] | None = None,
                       timestamps: list | None = None) -> list[Leaf]:
    cents = profile == "cent"

    def price(values: list) -> tuple[int, list]:
        if cents:
            return TYPE_INT32, list(values)
        return TYPE_DOUBLE, [None if v is NULL else round(v / 100.0, 2) for v in values]

    def size(values: list) -> tuple[int, list]:
        return (TYPE_INT32 if cents else TYPE_INT64), list(values)

    derived_i = [quote_derived_never_read(i) for i in range(sum(QUOTE_GROUP_SIZES))]
    derived_f = [float(v) for v in derived_i]
    bid_type, bid_values = price(QUOTE_BID_CENTS)
    ask_type, ask_values = price(QUOTE_ASK_CENTS)
    bid_size_type, bid_size_values = size(QUOTE_BID_SIZE)
    ask_size_type, ask_size_values = size(QUOTE_ASK_SIZE)

    leaves = [
        Leaf("timestamp", TYPE_INT64, timestamps if timestamps is not None else QUOTE_TS,
             logical_timestamp=True, statistics=True),
        Leaf("bid_size", bid_size_type, bid_size_values),
        Leaf("bid_exchange", TYPE_INT64, QUOTE_BID_EXCHANGE),
        Leaf("bid", bid_type, bid_values),
        Leaf("bid_condition", TYPE_INT64, QUOTE_BID_CONDITION),
        Leaf("ask_size", ask_size_type, ask_size_values),
        Leaf("ask_exchange", TYPE_INT64, QUOTE_ASK_EXCHANGE),
        Leaf("ask", ask_type, ask_values),
        Leaf("ask_condition", TYPE_INT64, QUOTE_ASK_CONDITION),
        Leaf("d_bid_size", TYPE_INT32 if cents else TYPE_INT64, derived_i),
        Leaf("d_ask_size", TYPE_INT32 if cents else TYPE_INT64, derived_i),
        Leaf("bid_px_chg", TYPE_INT32 if cents else TYPE_DOUBLE, derived_i if cents else derived_f),
        Leaf("ask_px_chg", TYPE_INT32 if cents else TYPE_DOUBLE, derived_i if cents else derived_f),
        Leaf("dt_prev_ms", TYPE_INT64, derived_i),
        Leaf("mid", TYPE_INT32 if cents else TYPE_DOUBLE, derived_i if cents else derived_f),
        Leaf("spread_bps", TYPE_DOUBLE, derived_f),
    ]
    if rename is not None:
        leaves[rename[0]].name = rename[1]
    if retype is not None:
        index, physical = retype
        leaf = leaves[index]
        leaf.physical = physical
        if physical == TYPE_DOUBLE:
            leaf.values = [None if v is NULL else float(v) for v in leaf.values]
        elif physical in (TYPE_INT32, TYPE_INT64):
            leaf.values = [None if v is NULL else int(v) for v in leaf.values]
    return leaves


def permute_in_group(leaves: list[Leaf], swaps: list[tuple[int, int]]) -> list[Leaf]:
    """Swaps whole ROWS (every column at once) — the in-group permutation the
    byte-identity fixture needs. The rows swapped must share a millisecond."""
    out = []
    for leaf in leaves:
        values = list(leaf.values)
        for left, right in swaps:
            values[left], values[right] = values[right], values[left]
        out.append(
            Leaf(leaf.name, leaf.physical, values, leaf.converted, leaf.logical_timestamp,
                 leaf.dictionary, leaf.statistics)
        )
    return out


# ---------------------------------------------------------------------------
# B2 — stock trades
# ---------------------------------------------------------------------------
#
# 10 rows in two row groups (6 + 4): one premarket row, one equal-time group of
# two, one group of one whose attached quote block is entirely NULL (absence is
# not zero), one group of two straddling the row-group boundary, and two
# postmarket rows.
TRADE_TS = [
    OPEN_MS - 5,
    OPEN_MS, OPEN_MS,
    OPEN_MS + 4,
    OPEN_MS + 7, OPEN_MS + 7,
    OPEN_MS + 9,
    CLOSE_MS - 1,
    CLOSE_MS, CLOSE_MS + 1,
]
TRADE_GROUP_SIZES = [6, 4]
TRADE_ROWS = len(TRADE_TS)


def stock_trade_leaves(retype: tuple[int, int] | None = None) -> list[Leaf]:
    quote_ts = [t - 3 for t in TRADE_TS]
    sequence = [1000 + 7 * i for i in range(TRADE_ROWS)]
    ext = [[255] * TRADE_ROWS for _ in range(4)]
    ext[0][4] = 12  # one print carries a real extended condition
    condition = [0] * TRADE_ROWS
    condition[3] = 40  # a CANCEL code, retained (the rule is downstream)
    size = [100, 200, 300, 400, 500, 500, 600, 700, 800, 900]
    exchange = [7, 7, 1, 65, 7, 7, 11, 12, 13, 14]
    price = [171.30, 171.39, 171.40, 171.41, 171.42, 171.42, 171.43, 171.44, 171.45, 171.46]
    # the attached NBBO block; row 3 has NO attached quote at all.
    bid_size = [10, 5, 15, NULL, 8, 8, 9, 10, 11, 12]
    bid_exchange = [1, 2, 3, NULL, 4, 4, 5, 6, 7, 8]
    bid = [171.29, 171.38, 171.39, NULL, 171.41, 171.41, 171.42, 171.43, 171.44, 171.45]
    bid_condition = [0] * TRADE_ROWS
    bid_condition[3] = NULL
    ask_size = [11, 6, 16, NULL, 9, 9, 10, 11, 12, 13]
    ask_exchange = [2, 3, 4, NULL, 5, 5, 6, 7, 8, 9]
    ask = [171.31, 171.40, 171.41, NULL, 171.43, 171.43, 171.44, 171.45, 171.46, 171.47]
    ask_condition = [0] * TRADE_ROWS
    ask_condition[3] = NULL
    never_read_i = [777_000 + i for i in range(TRADE_ROWS)]
    never_read_f = [float(v) for v in never_read_i]

    leaves = [
        Leaf("trade_timestamp", TYPE_INT64, TRADE_TS, logical_timestamp=True, statistics=True),
        Leaf("quote_timestamp", TYPE_INT64, quote_ts, logical_timestamp=True),
        Leaf("sequence", TYPE_INT64, sequence),
        Leaf("ext_condition1", TYPE_INT64, ext[0]),
        Leaf("ext_condition2", TYPE_INT64, ext[1]),
        Leaf("ext_condition3", TYPE_INT64, ext[2]),
        Leaf("ext_condition4", TYPE_INT64, ext[3]),
        Leaf("condition", TYPE_INT64, condition),
        Leaf("size", TYPE_INT64, size),
        Leaf("exchange", TYPE_INT64, exchange),
        Leaf("price", TYPE_DOUBLE, price),
        Leaf("bid_size", TYPE_INT64, bid_size),
        Leaf("bid_exchange", TYPE_INT64, bid_exchange),
        Leaf("bid", TYPE_DOUBLE, bid),
        Leaf("bid_condition", TYPE_INT64, bid_condition),
        Leaf("ask_size", TYPE_INT64, ask_size),
        Leaf("ask_exchange", TYPE_INT64, ask_exchange),
        Leaf("ask", TYPE_DOUBLE, ask),
        Leaf("ask_condition", TYPE_INT64, ask_condition),
        Leaf("dt_prev_ms", TYPE_INT64, never_read_i),
        Leaf("mid", TYPE_DOUBLE, never_read_f),
        Leaf("price_lag_1", TYPE_DOUBLE, never_read_f),
        # THE FUTURE FIELD. It is written into the fixture precisely so that a
        # decoder which reaches for it has something to find — and the wall has
        # something to refuse.
        Leaf("price_lead_1", TYPE_DOUBLE, [v + 1.0 for v in price]),
        Leaf("spread_bps", TYPE_DOUBLE, never_read_f),
    ]
    if retype is not None:
        index, physical = retype
        leaf = leaves[index]
        leaf.physical = physical
        if physical in (TYPE_INT32, TYPE_INT64):
            leaf.values = [None if v is NULL else int(round(float(v) * 100)) for v in leaf.values]
        else:
            leaf.values = [None if v is NULL else float(v) for v in leaf.values]
    return leaves


# ---------------------------------------------------------------------------
# B3 — option prints
# ---------------------------------------------------------------------------
#
# 8 rows in two row groups (5 + 3): the all-null sentinel, one premarket print,
# an equal-time group of two contracts, a group of one carrying B3's single-leg
# condition 18, a straddling group of two, and one postmarket print.
PRINT_TS = [
    NULL,
    OPEN_MS - 2,
    OPEN_MS, OPEN_MS,
    OPEN_MS + 6,
    OPEN_MS + 8, OPEN_MS + 8,
    CLOSE_MS + 5,
]
PRINT_GROUP_SIZES = [5, 3]
PRINT_ROWS = len(PRINT_TS)

OPTION_PRINT_NAMES = [
    "symbol", "expiration", "strike", "right", "timestamp", "sequence", "ext_condition1",
    "ext_condition2", "ext_condition3", "ext_condition4", "condition", "size", "exchange",
    "price", "delta", "theta", "vega", "rho", "epsilon", "lambda", "gamma", "vanna", "charm",
    "vomma", "veta", "vera", "speed", "zomma", "color", "ultima", "d1", "d2", "dual_delta",
    "dual_gamma", "implied_vol", "iv_error", "underlying_timestamp", "underlying_price", "side",
    "bid", "bid_size", "bid_exchange", "ask", "ask_size", "ask_exchange", "quote_timestamp",
    "dt_prev_contract_ms", "sweep_id", "sweep_n", "sweep_size", "sweep_exchanges",
    "dt_prev_any_ms", "dte", "moneyness", "prem", "delta_flow", "gamma_flow", "vanna_flow",
    "speed_flow", "zomma_flow", "charm_flow", "vomma_flow",
]

# 2022-07-08 and 2022-07-15 as day ordinals (days since 1970-01-01).
EXPIRY_A_DAYS = 19181
EXPIRY_B_DAYS = 19188
EXPIRY_A_TEXT = "2022-07-08"
EXPIRY_B_TEXT = "2022-07-15"


def option_print_leaves(profile: str) -> list[Leaf]:
    """`profile` is "compact" (IWM, the admitted one) or "wide" (the RUTW shape
    B5 defers — same 62 names, Float64 strike/price, Int64 sizes, text
    expiration; this reader must REFUSE it)."""
    compact = profile == "compact"
    n = PRINT_ROWS

    def nullable(values: list) -> list:
        return [NULL] + values

    expiry_days = nullable([EXPIRY_A_DAYS, EXPIRY_A_DAYS, EXPIRY_B_DAYS, EXPIRY_A_DAYS,
                            EXPIRY_B_DAYS, EXPIRY_B_DAYS, EXPIRY_A_DAYS])
    expiry_text = nullable([EXPIRY_A_TEXT, EXPIRY_A_TEXT, EXPIRY_B_TEXT, EXPIRY_A_TEXT,
                            EXPIRY_B_TEXT, EXPIRY_B_TEXT, EXPIRY_A_TEXT])
    strike_mills = nullable([169000, 171000, 156000, 166000, 171000, 171000, 172000])
    right_text = nullable([b"PUT", b"CALL", b"PUT", b"CALL", b"PUT", b"PUT", b"CALL"])
    sequence = nullable([3349778, 3349779, 3349956, 3349957, 3349955, 3349960, 3349961])
    condition = nullable([130, 18, 95, 18, 125, 126, 130])
    size = nullable([1, 2, 3, 4, 5, 5, 6])
    price_cents = nullable([768, 859, 202, 479, 717, 717, 800])
    # THE CC-013 BLOCK IS FIXTURED, NOT FILLED. Before CC-013 these eleven
    # columns fell through to the catch-all `unread_f` ramp, which is fine for a
    # column nobody reads and useless for one that is now projected. Each gets
    # its own value ladder plus, deliberately:
    #   * `vomma` NULL on admitted row 4  -> per-column ABSENCE must set exactly
    #     that slot's mask bit and no other;
    #   * `ultima` NaN and `color` +Inf   -> a NON-FINITE value is RETAINED RAW
    #     and is NOT an absence; the two states must stay distinguishable, which
    #     is the whole point of the mask being per slot.
    greeks = {
        "delta": nullable([-0.25, 0.5, -0.75, 0.25, -0.5, -0.5, 0.125]),
        "vega": nullable([1.01, 1.02, 1.03, 1.04, 1.05, 1.05, 1.06]),
        "gamma": nullable([0.01, 0.02, 0.03, 0.04, 0.05, 0.05, 0.06]),
        "vanna": nullable([0.11, 0.12, 0.13, 0.14, 0.15, 0.15, 0.16]),
        "charm": nullable([0.21, 0.22, 0.23, 0.24, 0.25, 0.25, 0.26]),
        "vomma": nullable([2.01, 2.02, NULL, 2.04, 2.05, 2.05, 2.06]),
        "veta": nullable([-3.01, -3.02, -3.03, -3.04, -3.05, -3.05, -3.06]),
        "vera": nullable([4.01, -4.02, 4.03, -4.04, 4.05, 4.05, -4.06]),
        "speed": nullable([-5.01, 5.02, -5.03, 5.04, -5.05, -5.05, 5.06]),
        "zomma": nullable([6.01, -6.02, 6.03, -6.04, 6.05, 6.05, -6.06]),
        "color": nullable([7.01, 7.02, float("inf"), 7.04, 7.05, 7.05, 7.06]),
        "ultima": nullable([8.01, 8.02, 8.03, float("nan"), 8.05, 8.05, 8.06]),
        "dual_delta": nullable([-0.24, 0.49, -0.74, 0.24, -0.49, -0.49, 0.124]),
        "dual_gamma": nullable([0.011, 0.021, 0.031, 0.041, 0.051, 0.051, 0.061]),
        "implied_vol": nullable([0.31, 0.32, 0.33, 0.34, 0.35, 0.35, 0.36]),
        "iv_error": nullable([0.0001, -0.0002, 0.0003, -0.0004, 0.0005, 0.0005, -0.0006]),
        "underlying_price": nullable([168.59, 168.60, 168.61, 168.62, 168.63, 168.63, 168.64]),
    }
    underlying_ts = nullable([
        b"2022-07-05T09:29:58.000", b"2022-07-05T09:30:00.000", b"2022-07-05T09:30:00.000",
        b"2022-07-05T09:30:05.000", b"2022-07-05T09:30:07.000", b"2022-07-05T09:30:07.000",
        b"2022-07-05T16:00:05.000",
    ])
    bid_cents = nullable([760, 850, 200, 470, 710, 710, 790])
    ask_cents = nullable([770, 860, 210, 480, 720, 720, 800])
    bid_size = nullable([11, 12, 13, 14, 15, 15, 16])
    ask_size = nullable([21, 22, 23, 24, 25, 25, 26])
    quote_ts = nullable([t - 4 for t in PRINT_TS[1:]])
    unread_i = [555_000 + i for i in range(n)]
    unread_f = [float(v) for v in unread_i]

    def leaf_for(name: str) -> Leaf:
        if name == "symbol":
            return Leaf(name, TYPE_BYTE_ARRAY, nullable([b"IWM"] * (n - 1)), CONVERTED_UTF8,
                        dictionary=True)
        if name == "expiration":
            if compact:
                return Leaf(name, TYPE_INT32, expiry_days, CONVERTED_DATE)
            return Leaf(name, TYPE_BYTE_ARRAY, [None if v is NULL else v.encode() for v in
                                                expiry_text], CONVERTED_UTF8, dictionary=True)
        if name == "strike":
            if compact:
                return Leaf(name, TYPE_INT32, strike_mills)
            return Leaf(name, TYPE_DOUBLE,
                        [None if v is NULL else v / 1000.0 for v in strike_mills])
        if name == "right":
            return Leaf(name, TYPE_BYTE_ARRAY, right_text, CONVERTED_UTF8, dictionary=True)
        if name == "timestamp":
            return Leaf(name, TYPE_INT64, PRINT_TS, logical_timestamp=True, statistics=True)
        if name == "quote_timestamp":
            return Leaf(name, TYPE_INT64, quote_ts, logical_timestamp=True)
        if name == "sequence":
            return Leaf(name, TYPE_INT64, sequence)
        if name == "condition":
            return Leaf(name, TYPE_INT64, condition)
        if name == "size":
            return Leaf(name, TYPE_INT32 if compact else TYPE_INT64, size)
        if name == "price":
            if compact:
                return Leaf(name, TYPE_INT32, price_cents)
            return Leaf(name, TYPE_DOUBLE, [None if v is NULL else v / 100.0 for v in price_cents])
        if name in ("bid", "ask"):
            cents = bid_cents if name == "bid" else ask_cents
            if compact:
                return Leaf(name, TYPE_INT32, cents)
            return Leaf(name, TYPE_DOUBLE, [None if v is NULL else v / 100.0 for v in cents])
        if name in ("bid_size", "ask_size"):
            values = bid_size if name == "bid_size" else ask_size
            return Leaf(name, TYPE_INT32 if compact else TYPE_INT64, values)
        if name == "underlying_timestamp":
            return Leaf(name, TYPE_BYTE_ARRAY, underlying_ts, CONVERTED_UTF8, dictionary=True)
        if name in greeks:
            return Leaf(name, TYPE_DOUBLE, greeks[name])
        if name == "side":
            return Leaf(name, TYPE_INT32, [None if i == 0 else (1 if i % 2 else -1)
                                           for i in range(n)], CONVERTED_INT_8)
        if name in ("sweep_id", "sweep_n", "sweep_exchanges"):
            return Leaf(name, TYPE_INT32, unread_i, CONVERTED_UINT_32)
        if name == "sweep_size":
            return Leaf(name, TYPE_INT32, unread_i)
        if name in ("bid_exchange", "ask_exchange", "exchange", "dt_prev_contract_ms",
                    "dt_prev_any_ms", "dte"):
            return Leaf(name, TYPE_INT64, unread_i)
        if name.startswith("ext_condition"):
            return Leaf(name, TYPE_INT64, [NULL] + [255] * (n - 1))
        return Leaf(name, TYPE_DOUBLE, unread_f)

    return [leaf_for(name) for name in OPTION_PRINT_NAMES]


# ---------------------------------------------------------------------------
# B5 — RUTW prints (the same 62 names, the WIDE profile only)
# ---------------------------------------------------------------------------
#
# 11 rows in two row groups (6 + 5).  What each row is FOR:
#   0   the all-null sentinel row the corpus writes once per file
#   1   one print before the open (premarket, excluded)
#   2,3 equal-time group A at the open, two different contracts
#   4   group B: THE WIDE-TYPE EDGE ROW — a RUT-scale strike whose u6 value
#       overflows int32, a sub-cent Float64 price, and Int64 sizes past
#       INT32_MAX.  Every one of those is representable ONLY in the wide
#       profile, which is why B5 pins that profile and nothing else.
#   5,6 group C, STRADDLING the row-group boundary; row 6 carries BOTH
#       attachment clocks NULL (absence is a mask bit, never a sentinel)
#   7   group D: junk price (0.0) and junk size (0) — counted, not dropped
#   8   group E: junk right (an unknown token) and a CROSSED attached quote
#   9   group F: quote_ts EQUAL to the print instant (not STRICTLY prior) and
#       an underlying stamp naming a different day
#   10  one print after the close (excluded)
RUTW_TS = [
    NULL,
    OPEN_MS - 2,
    OPEN_MS, OPEN_MS,
    OPEN_MS + 6,
    OPEN_MS + 8,
    OPEN_MS + 8,
    OPEN_MS + 12,
    OPEN_MS + 13,
    OPEN_MS + 14,
    CLOSE_MS + 5,
]
RUTW_GROUP_SIZES = [6, 5]
RUTW_ROWS = len(RUTW_TS)

# The RUT-scale values, in the units the wide profile stores them in.
# `strike` and every price are Float64 DOLLARS; every size is Int64.
# Row 9 repeats row 7's (expiry, strike) with the OTHER right: a contract
# identity that drops the right would merge the two into one.
RUTW_STRIKE_DOLLARS = [NULL, 1885.5, 1870.25, 1900.0, 2500.5, 1900.0, 1900.0, 1910.0, 1875.0,
                       1910.0, 1920.0]
RUTW_PRICE_DOLLARS = [NULL, 7.685, 8.595, 2.025, 0.005, 7.175, 7.175, 0.0, 8.0, 3.5, 9.0]
RUTW_BID_DOLLARS = [NULL, 7.68, 8.59, 2.02, 0.0025, 7.17, 7.17, 0.0, 8.6, 3.45, 8.95]
RUTW_ASK_DOLLARS = [NULL, 7.69, 8.60, 2.03, 0.0075, 7.18, 7.18, 0.01, 8.5, 3.55, 9.05]
# Row 4's size and bid_size are past INT32_MAX: the compact profile could not
# hold them at all, so decoding them proves the Int64 pin is really in force.
RUTW_SIZE = [NULL, 1, 2, 3, 3_000_000_001, 5, 5, 0, 6, 7, 8]
RUTW_BID_SIZE = [NULL, 11, 12, 13, 2_147_483_648, 15, 15, 16, 17, 18, 19]
RUTW_ASK_SIZE = [NULL, 21, 22, 23, 4_000_000_007, 25, 25, 26, 27, 28, 29]
RUTW_RIGHT = [NULL, b"PUT", b"CALL", b"PUT", b"CALL", b"PUT", b"PUT", b"CALL", b"XYZ", b"PUT",
              b"CALL"]
RUTW_EXPIRY_TEXT = [NULL, EXPIRY_A_TEXT, EXPIRY_A_TEXT, EXPIRY_B_TEXT, EXPIRY_A_TEXT,
                    EXPIRY_B_TEXT, EXPIRY_B_TEXT, EXPIRY_A_TEXT, EXPIRY_B_TEXT, EXPIRY_A_TEXT,
                    EXPIRY_B_TEXT]
RUTW_CONDITION = [NULL, 130, 18, 95, 18, 125, 126, 18, 130, 95, 18]
RUTW_SEQUENCE = [NULL] + [4_400_000 + 3 * i for i in range(RUTW_ROWS - 1)]
# quote_ts(45): strictly prior everywhere except row 6 (NULL) and row 9 (EQUAL
# to the print instant, which is NOT strictly prior).
RUTW_QUOTE_TS = [NULL] + [t - 4 for t in RUTW_TS[1:]]
RUTW_QUOTE_TS[6] = NULL
RUTW_QUOTE_TS[9] = RUTW_TS[9]
# underlying_ts(36): retained TEXT.  Row 6 is absent, row 9 names another day.
RUTW_UNDERLYING_TS = [NULL] + [f"{DAY}T09:30:0{i}.000".encode() for i in range(RUTW_ROWS - 1)]
RUTW_UNDERLYING_TS[6] = NULL
RUTW_UNDERLYING_TS[9] = b"2022-07-06T09:30:09.000"
def _rutw_ramp(base: float, step: float) -> list:
    return [NULL] + [round(base + step * i, 4) for i in range(RUTW_ROWS - 1)]


# B5 is "same laws", so B5's fixture carries the SAME sixteen reals B3's does.
# A CC-013 that landed on one reader and not the other would show up here.
RUTW_GREEKS = {
    "delta": _rutw_ramp(-0.25, 0.05),
    "vega": _rutw_ramp(1.01, 0.01),
    "gamma": _rutw_ramp(0.01, 0.01),
    "vanna": _rutw_ramp(0.11, 0.01),
    "charm": _rutw_ramp(0.21, 0.01),
    "vomma": _rutw_ramp(2.01, 0.01),
    "veta": _rutw_ramp(-3.01, -0.01),
    "vera": _rutw_ramp(4.01, 0.01),
    "speed": _rutw_ramp(-5.01, 0.01),
    "zomma": _rutw_ramp(6.01, -0.01),
    "color": _rutw_ramp(7.01, 0.01),
    "ultima": _rutw_ramp(8.01, 0.01),
    "dual_delta": _rutw_ramp(-0.24, 0.05),
    "dual_gamma": _rutw_ramp(0.011, 0.01),
    "implied_vol": _rutw_ramp(0.31, 0.01),
    "iv_error": _rutw_ramp(0.0001, -0.0001),
    "underlying_price": _rutw_ramp(1890.11, 0.01),
}


def rutw_print_leaves() -> list[Leaf]:
    """The RUTW wide profile of the SAME 62 names B3 pins: `expiration` UTF-8
    ISO text, `strike`/`price`/`bid`/`ask` Float64 dollars, `size`/`bid_size`/
    `ask_size` Int64.  Measured on RUTW/options_prints/2023/2023-08-01.parquet.
    """
    n = RUTW_ROWS
    unread_i = [666_000 + i for i in range(n)]
    unread_f = [float(v) for v in unread_i]

    def leaf_for(name: str) -> Leaf:
        if name == "symbol":
            return Leaf(name, TYPE_BYTE_ARRAY, [NULL] + [b"RUTW"] * (n - 1), CONVERTED_UTF8,
                        dictionary=True)
        if name == "expiration":
            return Leaf(name, TYPE_BYTE_ARRAY,
                        [None if v is NULL else v.encode() for v in RUTW_EXPIRY_TEXT],
                        CONVERTED_UTF8, dictionary=True)
        if name == "strike":
            return Leaf(name, TYPE_DOUBLE, RUTW_STRIKE_DOLLARS)
        if name == "right":
            return Leaf(name, TYPE_BYTE_ARRAY, RUTW_RIGHT, CONVERTED_UTF8, dictionary=True)
        if name == "timestamp":
            return Leaf(name, TYPE_INT64, RUTW_TS, logical_timestamp=True, statistics=True)
        if name == "quote_timestamp":
            return Leaf(name, TYPE_INT64, RUTW_QUOTE_TS, logical_timestamp=True)
        if name == "sequence":
            return Leaf(name, TYPE_INT64, RUTW_SEQUENCE)
        if name == "condition":
            return Leaf(name, TYPE_INT64, RUTW_CONDITION)
        if name == "size":
            return Leaf(name, TYPE_INT64, RUTW_SIZE)
        if name == "price":
            return Leaf(name, TYPE_DOUBLE, RUTW_PRICE_DOLLARS)
        if name == "bid":
            return Leaf(name, TYPE_DOUBLE, RUTW_BID_DOLLARS)
        if name == "ask":
            return Leaf(name, TYPE_DOUBLE, RUTW_ASK_DOLLARS)
        if name == "bid_size":
            return Leaf(name, TYPE_INT64, RUTW_BID_SIZE)
        if name == "ask_size":
            return Leaf(name, TYPE_INT64, RUTW_ASK_SIZE)
        if name == "underlying_timestamp":
            return Leaf(name, TYPE_BYTE_ARRAY, RUTW_UNDERLYING_TS, CONVERTED_UTF8, dictionary=True)
        if name in RUTW_GREEKS:
            return Leaf(name, TYPE_DOUBLE, RUTW_GREEKS[name])
        if name == "side":
            return Leaf(name, TYPE_INT32, [None if i == 0 else (1 if i % 2 else -1)
                                           for i in range(n)], CONVERTED_INT_8)
        if name in ("sweep_id", "sweep_n", "sweep_exchanges"):
            return Leaf(name, TYPE_INT32, unread_i, CONVERTED_UINT_32)
        if name in ("sweep_size", "bid_exchange", "ask_exchange", "exchange",
                    "dt_prev_contract_ms", "dt_prev_any_ms", "dte"):
            return Leaf(name, TYPE_INT64, unread_i)
        if name.startswith("ext_condition"):
            return Leaf(name, TYPE_INT64, [NULL] + [255] * (n - 1))
        return Leaf(name, TYPE_DOUBLE, unread_f)

    return [leaf_for(name) for name in OPTION_PRINT_NAMES]


# ---------------------------------------------------------------------------
# B4 — option quotes
# ---------------------------------------------------------------------------
OPTION_QUOTE_NAMES = [
    "symbol", "expiration", "strike", "right", "timestamp", "bid_size", "bid_exchange", "bid",
    "bid_condition", "ask_size", "ask_exchange", "ask", "ask_condition", "d_bid_size",
    "d_ask_size", "bid_px_chg", "ask_px_chg", "dt_prev_contract_ms", "mid",
]

OQ_TS = [OPEN_MS - 1, OPEN_MS, OPEN_MS, OPEN_MS + 5, CLOSE_MS + 1]
OQ_GROUP_SIZES = [3, 2]
OQ_ROWS = len(OQ_TS)


def option_quote_leaves(profile: str) -> list[Leaf]:
    """`profile` is "compact" (DATE ordinal expiration, mill strike, cent
    prices) or "wide" (ISO text expiration, dollar strike and prices). BOTH are
    admitted: no registry column declares an option-quote profile, so the reader
    detects it from the file's own schema."""
    compact = profile == "compact"
    expiry_days = [EXPIRY_A_DAYS, EXPIRY_A_DAYS, EXPIRY_B_DAYS, EXPIRY_A_DAYS, EXPIRY_B_DAYS]
    expiry_text = [EXPIRY_A_TEXT, EXPIRY_A_TEXT, EXPIRY_B_TEXT, EXPIRY_A_TEXT, EXPIRY_B_TEXT]
    strike_mills = [169000, 171000, 156000, 166000, 171000]
    rights = [b"PUT", b"CALL", b"PUT", b"CALL", b"PUT"]
    bid_size = [11, 12, 13, NULL, 15]
    ask_size = [21, 22, 23, 24, 25]
    bid_cents = [760, 850, 200, 470, 710]
    ask_cents = [770, 860, 210, 480, 720]
    unread_i = [444_000 + i for i in range(OQ_ROWS)]
    unread_f = [float(v) for v in unread_i]

    def price_leaf(name: str, cents: list) -> Leaf:
        if compact:
            return Leaf(name, TYPE_INT32, cents)
        return Leaf(name, TYPE_DOUBLE, [None if v is NULL else v / 100.0 for v in cents])

    return [
        Leaf("symbol", TYPE_BYTE_ARRAY, [b"IWM"] * OQ_ROWS, CONVERTED_UTF8, dictionary=True),
        Leaf("expiration", TYPE_INT32, expiry_days, CONVERTED_DATE) if compact else
        Leaf("expiration", TYPE_BYTE_ARRAY, [v.encode() for v in expiry_text], CONVERTED_UTF8,
             dictionary=True),
        Leaf("strike", TYPE_INT32, strike_mills) if compact else
        Leaf("strike", TYPE_DOUBLE, [v / 1000.0 for v in strike_mills]),
        Leaf("right", TYPE_BYTE_ARRAY, rights, CONVERTED_UTF8, dictionary=True),
        Leaf("timestamp", TYPE_INT64, OQ_TS, logical_timestamp=True, statistics=True),
        Leaf("bid_size", TYPE_INT32 if compact else TYPE_INT64, bid_size),
        Leaf("bid_exchange", TYPE_INT64, unread_i),
        price_leaf("bid", bid_cents),
        Leaf("bid_condition", TYPE_INT64, [0] * OQ_ROWS),
        Leaf("ask_size", TYPE_INT32 if compact else TYPE_INT64, ask_size),
        Leaf("ask_exchange", TYPE_INT64, unread_i),
        price_leaf("ask", ask_cents),
        Leaf("ask_condition", TYPE_INT64, [0] * OQ_ROWS),
        Leaf("d_bid_size", TYPE_INT64, unread_i),
        Leaf("d_ask_size", TYPE_INT64, unread_i),
        Leaf("bid_px_chg", TYPE_DOUBLE, unread_f),
        Leaf("ask_px_chg", TYPE_DOUBLE, unread_f),
        Leaf("dt_prev_contract_ms", TYPE_INT64, unread_i),
        # THE WALLED COLUMN: written as bid+ask (the compact vendor's meaning),
        # so a decoder that ever read it would produce a visibly wrong midpoint.
        Leaf("mid", TYPE_INT32 if compact else TYPE_DOUBLE,
             [b + a for b, a in zip(bid_cents, ask_cents)] if compact else
             [(b + a) / 100.0 for b, a in zip(bid_cents, ask_cents)]),
    ]


# ---------------------------------------------------------------------------
# expected literals (derived HERE, asserted by the C++ suite)
# ---------------------------------------------------------------------------

def cents_to_u6(cents: int) -> int:
    return cents * 10_000


def dollars_to_u6(dollars: float) -> int:
    scaled = dollars * 1_000_000.0
    floor = int(scaled // 1)
    fraction = scaled - floor
    if fraction > 0.5:
        return floor + 1
    if fraction < 0.5:
        return floor
    return floor if floor % 2 == 0 else floor + 1


def lots_to_shares(lots: int) -> int:
    return lots * 100


def quote_literals() -> list[str]:
    rows = []
    admitted = [i for i, ts in enumerate(QUOTE_TS)
                if ts is not NULL and OPEN_MS <= ts < CLOSE_MS]
    groups: list[list[int]] = []
    for index in admitted:
        if groups and QUOTE_TS[groups[-1][-1]] == QUOTE_TS[index]:
            groups[-1].append(index)
        else:
            groups.append([index])
    rows.append(f"stock_quotes\t*\trth_rows\t{len(admitted)}")
    rows.append(f"stock_quotes\t*\tgroup_count\t{len(groups)}")
    rows.append("stock_quotes\t*\tsentinel_rows\t1")
    rows.append(f"stock_quotes\t*\trow_groups_total\t{len(QUOTE_GROUP_SIZES)}")
    rows.append("stock_quotes\t*\trow_groups_kept\t2")
    for number, group in enumerate(groups):
        rows.append(f"stock_quotes\tgroup{number}\tts_ms_b\t{QUOTE_TS[group[0]]}")
        rows.append(f"stock_quotes\tgroup{number}\trows\t{len(group)}")
    for index in admitted:
        rows.append(f"stock_quotes\trow{index}\tbid_u6\t{cents_to_u6(QUOTE_BID_CENTS[index])}")
        rows.append(f"stock_quotes\trow{index}\task_u6\t{cents_to_u6(QUOTE_ASK_CENTS[index])}")
        rows.append(f"stock_quotes\trow{index}\tbid_shares\t{lots_to_shares(QUOTE_BID_SIZE[index])}")
        rows.append(f"stock_quotes\trow{index}\task_shares\t{lots_to_shares(QUOTE_ASK_SIZE[index])}")
        exchange = QUOTE_BID_EXCHANGE[index]
        rows.append(f"stock_quotes\trow{index}\tbid_exchange_null\t"
                    f"{1 if exchange is NULL else 0}")
    return rows


def trade_literals() -> list[str]:
    leaves = {leaf.name: leaf for leaf in stock_trade_leaves()}
    admitted = [i for i, ts in enumerate(TRADE_TS) if OPEN_MS <= ts < CLOSE_MS]
    groups: list[list[int]] = []
    for index in admitted:
        if groups and TRADE_TS[groups[-1][-1]] == TRADE_TS[index]:
            groups[-1].append(index)
        else:
            groups.append([index])
    rows = [
        f"stock_trades\t*\trth_rows\t{len(admitted)}",
        f"stock_trades\t*\tgroup_count\t{len(groups)}",
    ]
    for number, group in enumerate(groups):
        rows.append(f"stock_trades\tgroup{number}\tts_ms_b\t{TRADE_TS[group[0]]}")
        rows.append(f"stock_trades\tgroup{number}\trows\t{len(group)}")
    for index in admitted:
        price = leaves["price"].values[index]
        rows.append(f"stock_trades\trow{index}\tprice_u6\t{dollars_to_u6(price)}")
        bid_size = leaves["bid_size"].values[index]
        rows.append(f"stock_trades\trow{index}\tquote_present\t{0 if bid_size is NULL else 1}")
        if bid_size is not NULL:
            rows.append(f"stock_trades\trow{index}\tbid_shares\t{lots_to_shares(bid_size)}")
            rows.append(f"stock_trades\trow{index}\tbid_u6\t"
                        f"{dollars_to_u6(leaves['bid'].values[index])}")
    return rows


def print_literals() -> list[str]:
    leaves = {leaf.name: leaf for leaf in option_print_leaves("compact")}
    admitted = [i for i, ts in enumerate(PRINT_TS)
                if ts is not NULL and OPEN_MS <= ts < CLOSE_MS]
    groups: list[list[int]] = []
    for index in admitted:
        if groups and PRINT_TS[groups[-1][-1]] == PRINT_TS[index]:
            groups[-1].append(index)
        else:
            groups.append([index])
    rows = [
        f"options_prints\t*\trth_rows\t{len(admitted)}",
        f"options_prints\t*\tgroup_count\t{len(groups)}",
        f"options_prints\t*\tskipped_null_rows\t1",
    ]
    for number, group in enumerate(groups):
        rows.append(f"options_prints\tgroup{number}\tts_ms_b\t{PRINT_TS[group[0]]}")
        rows.append(f"options_prints\tgroup{number}\trows\t{len(group)}")
    for index in admitted:
        rows.append(f"options_prints\trow{index}\tstrike_u6\t"
                    f"{leaves['strike'].values[index] * 1000}")
        rows.append(f"options_prints\trow{index}\tprice_u6\t"
                    f"{cents_to_u6(leaves['price'].values[index])}")
        rows.append(f"options_prints\trow{index}\texpiration_day\t"
                    f"{leaves['expiration'].values[index]}")
        rows.append(f"options_prints\trow{index}\tright\t"
                    f"{leaves['right'].values[index].decode()}")
        rows.append(f"options_prints\trow{index}\tcondition\t{leaves['condition'].values[index]}")
        rows.append(f"options_prints\trow{index}\tunderlying_ts_text\t"
                    f"{leaves['underlying_timestamp'].values[index].decode()}")
        # CC-013: every admitted row's value for each newly projected column,
        # derived HERE so the C++ suite asserts and never recomputes. NULL and
        # the two non-finite cells are emitted as their own tokens.
        for name in ("vega", "vomma", "veta", "vera", "speed", "zomma", "color", "ultima",
                     "dual_delta", "dual_gamma", "iv_error"):
            value = leaves[name].values[index]
            if value is NULL:
                token = "NULL"
            elif value != value:
                token = "NAN"
            elif value == float("inf"):
                token = "INF"
            elif value == float("-inf"):
                token = "-INF"
            else:
                token = repr(float(value))
            rows.append(f"options_prints\trow{index}\t{name}\t{token}")
    return rows


def iso_to_day_ordinal(text: str) -> int:
    """ISO `YYYY-MM-DD` -> days since 1970-01-01, by Howard Hinnant's civil
    algorithm — the same arithmetic `qr::CivilDate::parse_ymd` implements, done
    here independently so the C++ side asserts rather than recomputes."""
    year, month, day = (int(part) for part in text.split("-"))
    year -= month <= 2
    era = (year if year >= 0 else year - 399) // 400
    yoe = year - era * 400
    doy = (153 * (month + (-3 if month > 2 else 9)) + 2) // 5 + day - 1
    doe = yoe * 365 + yoe // 4 - yoe // 100 + doy
    return era * 146097 + doe - 719468


def rutw_literals() -> list[str]:
    """B5's expected literals, derived HERE from the values written above.

    The census columns are recomputed by this script's own arithmetic — the
    same rules `qr::sources::fold_census` states, written a second time in a
    second language.  That is the point: the C++ suite asserts these numbers
    and computes none of them twice."""
    admitted = [i for i, ts in enumerate(RUTW_TS)
                if ts is not NULL and OPEN_MS <= ts < CLOSE_MS]
    groups: list[list[int]] = []
    for index in admitted:
        if groups and RUTW_TS[groups[-1][-1]] == RUTW_TS[index]:
            groups[-1].append(index)
        else:
            groups.append([index])

    rows = [
        f"rutw_prints\t*\trth_rows\t{len(admitted)}",
        f"rutw_prints\t*\tgroup_count\t{len(groups)}",
        "rutw_prints\t*\tskipped_null_rows\t1",
        f"rutw_prints\t*\trow_groups_total\t{len(RUTW_GROUP_SIZES)}",
    ]
    for number, group in enumerate(groups):
        rows.append(f"rutw_prints\tgroup{number}\tts_ms_b\t{RUTW_TS[group[0]]}")
        rows.append(f"rutw_prints\tgroup{number}\trows\t{len(group)}")
    for index in admitted:
        rows.append(f"rutw_prints\trow{index}\tstrike_u6\t"
                    f"{dollars_to_u6(RUTW_STRIKE_DOLLARS[index])}")
        rows.append(f"rutw_prints\trow{index}\tprice_u6\t"
                    f"{dollars_to_u6(RUTW_PRICE_DOLLARS[index])}")
        rows.append(f"rutw_prints\trow{index}\tbid_u6\t{dollars_to_u6(RUTW_BID_DOLLARS[index])}")
        rows.append(f"rutw_prints\trow{index}\task_u6\t{dollars_to_u6(RUTW_ASK_DOLLARS[index])}")
        rows.append(f"rutw_prints\trow{index}\tsize\t{RUTW_SIZE[index]}")
        rows.append(f"rutw_prints\trow{index}\tbid_size\t{RUTW_BID_SIZE[index]}")
        rows.append(f"rutw_prints\trow{index}\task_size\t{RUTW_ASK_SIZE[index]}")
        rows.append(f"rutw_prints\trow{index}\texpiration_day\t"
                    f"{iso_to_day_ordinal(RUTW_EXPIRY_TEXT[index])}")
        rows.append(f"rutw_prints\trow{index}\tright\t{RUTW_RIGHT[index].decode()}")
        rows.append(f"rutw_prints\trow{index}\tcondition\t{RUTW_CONDITION[index]}")

    # --- the census, recomputed here ---------------------------------------
    census = {name: 0 for name in (
        "quote_attachment_prior", "quote_attachment_not_prior", "quote_attachment_absent",
        "underlying_on_day", "underlying_off_day", "underlying_absent",
        "fully_populated_rows", "greek_complete_rows", "junk_price_rows", "junk_size_rows",
        "junk_right_rows", "junk_crossed_quote_rows", "junk_rows")}
    projected = {
        "expiration": RUTW_EXPIRY_TEXT, "strike": RUTW_STRIKE_DOLLARS, "right": RUTW_RIGHT,
        "timestamp": RUTW_TS, "sequence": RUTW_SEQUENCE, "condition": RUTW_CONDITION,
        "size": RUTW_SIZE, "price": RUTW_PRICE_DOLLARS, "delta": RUTW_GREEKS["delta"],
        "gamma": RUTW_GREEKS["gamma"], "vanna": RUTW_GREEKS["vanna"],
        "charm": RUTW_GREEKS["charm"], "implied_vol": RUTW_GREEKS["implied_vol"],
        "underlying_timestamp": RUTW_UNDERLYING_TS,
        "underlying_price": RUTW_GREEKS["underlying_price"], "bid": RUTW_BID_DOLLARS,
        "bid_size": RUTW_BID_SIZE, "ask": RUTW_ASK_DOLLARS, "ask_size": RUTW_ASK_SIZE,
        "quote_timestamp": RUTW_QUOTE_TS,
    }
    for index in admitted:
        quote_ts = RUTW_QUOTE_TS[index]
        if quote_ts is NULL:
            census["quote_attachment_absent"] += 1
        elif quote_ts < RUTW_TS[index]:
            census["quote_attachment_prior"] += 1
        else:
            census["quote_attachment_not_prior"] += 1

        stamp = RUTW_UNDERLYING_TS[index]
        if stamp is NULL:
            census["underlying_absent"] += 1
        elif stamp.decode()[:10] == DAY:
            census["underlying_on_day"] += 1
        else:
            census["underlying_off_day"] += 1

        if all(column[index] is not NULL for column in projected.values()):
            census["fully_populated_rows"] += 1
        if all(RUTW_GREEKS[name][index] is not NULL
               for name in ("delta", "gamma", "vanna", "charm", "implied_vol")):
            census["greek_complete_rows"] += 1

        junk_price = (RUTW_PRICE_DOLLARS[index] is NULL or
                      dollars_to_u6(RUTW_PRICE_DOLLARS[index]) <= 0)
        junk_size = RUTW_SIZE[index] is NULL or RUTW_SIZE[index] <= 0
        junk_right = (RUTW_RIGHT[index] is NULL or
                      RUTW_RIGHT[index].decode().upper() not in ("C", "CALL", "P", "PUT"))
        two_sided = RUTW_BID_DOLLARS[index] is not NULL and RUTW_ASK_DOLLARS[index] is not NULL
        junk_crossed = two_sided and (dollars_to_u6(RUTW_ASK_DOLLARS[index]) <
                                      dollars_to_u6(RUTW_BID_DOLLARS[index]))
        census["junk_price_rows"] += 1 if junk_price else 0
        census["junk_size_rows"] += 1 if junk_size else 0
        census["junk_right_rows"] += 1 if junk_right else 0
        census["junk_crossed_quote_rows"] += 1 if junk_crossed else 0
        census["junk_rows"] += 1 if (junk_price or junk_size or junk_right or junk_crossed) else 0

    for name, value in census.items():
        rows.append(f"rutw_prints\tcensus\t{name}\t{value}")

    # Distinct-contract coverage, over the admitted rows.
    contracts = {(iso_to_day_ordinal(RUTW_EXPIRY_TEXT[i]), dollars_to_u6(RUTW_STRIKE_DOLLARS[i]),
                  RUTW_RIGHT[i]) for i in admitted}
    rows.append(f"rutw_prints\tcoverage\tcontracts\t{len(contracts)}")
    rows.append(f"rutw_prints\tcoverage\texpirations\t"
                f"{len({iso_to_day_ordinal(RUTW_EXPIRY_TEXT[i]) for i in admitted})}")
    rows.append(f"rutw_prints\tcoverage\tstrikes\t"
                f"{len({dollars_to_u6(RUTW_STRIKE_DOLLARS[i]) for i in admitted})}")
    return rows


def option_quote_literals() -> list[str]:
    admitted = [i for i, ts in enumerate(OQ_TS) if OPEN_MS <= ts < CLOSE_MS]
    admitted = [i for i in admitted if option_quote_leaves("compact")[7].values[i] is not NULL]
    rows = [f"option_quotes\t*\trth_rows\t{len(admitted)}"]
    compact = {leaf.name: leaf for leaf in option_quote_leaves("compact")}
    for index in admitted:
        rows.append(f"option_quotes\trow{index}\tbid_u6\t"
                    f"{cents_to_u6(compact['bid'].values[index])}")
        rows.append(f"option_quotes\trow{index}\task_u6\t"
                    f"{cents_to_u6(compact['ask'].values[index])}")
        rows.append(f"option_quotes\trow{index}\tstrike_u6\t"
                    f"{compact['strike'].values[index] * 1000}")
        rows.append(f"option_quotes\trow{index}\texpiration_day\t"
                    f"{compact['expiration'].values[index]}")
    # The era law, proven on both sides of the 2025-11-03 break WITHOUT opening
    # any payload from it (FINAL_PLAN B7: those sessions are past the wall).
    for day, lots, expected in (
        ("2022-07-05", 7, 700),
        ("2025-10-31", 7, 700),
        ("2025-11-03", 7, 7),
        ("2025-12-31", 7, 7),
    ):
        rows.append(f"share_era\t{day}\tlots{lots}\t{expected}")
    return rows


# ---------------------------------------------------------------------------
# driver
# ---------------------------------------------------------------------------

def write(path: str, blob: bytes) -> None:
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "wb") as handle:
        handle.write(blob)
    print(f"wrote {path} ({len(blob)} bytes)")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--out-dir", default=os.path.join(HERE, "sources"))
    parser.add_argument("--literals-path",
                        default=os.path.join(HERE, "source_expected_literals.tsv"))
    args = parser.parse_args(argv)

    def day_path(tree: str) -> str:
        return os.path.join(args.out_dir, tree, YEAR, f"{DAY}.parquet")

    # --- B1 stock quotes ---------------------------------------------------
    write(day_path("sq_cent"), build_file(stock_quote_leaves("cent"), QUOTE_GROUP_SIZES))
    write(day_path("sq_cent_v2"), build_file(stock_quote_leaves("cent"), QUOTE_GROUP_SIZES,
                                             page_version=2))
    write(day_path("sq_dollar"), build_file(stock_quote_leaves("dollar"), QUOTE_GROUP_SIZES))
    # The dollar profile on ITS OWN registered session (187, 2022-09-30), so the
    # dual-profile law is exercised end to end: the same prices and sizes, the
    # other encoding, and the reader must produce identical u6 and share values.
    dollar_session = os.path.join(args.out_dir, "sq_dollar_session187", DOLLAR_YEAR,
                                  f"{DOLLAR_DAY}.parquet")
    write(dollar_session,
          build_file(stock_quote_leaves(
              "dollar", timestamps=quote_timestamps(DOLLAR_OPEN_MS, DOLLAR_CLOSE_MS)),
              QUOTE_GROUP_SIZES))
    # in-group permutations: rows 2<->3 (group A) and 8<->9 (group D).
    write(day_path("sq_permuted"),
          build_file(permute_in_group(stock_quote_leaves("cent"), [(2, 3), (8, 9)]),
                     QUOTE_GROUP_SIZES))
    write(day_path("sq_renamed"),
          build_file(stock_quote_leaves("cent", rename=(3, "bid_price")), QUOTE_GROUP_SIZES))
    write(day_path("sq_wrongtype"),
          build_file(stock_quote_leaves("cent", retype=(1, TYPE_INT64)), QUOTE_GROUP_SIZES))
    # The profile mismatch the dual-profile law is about: the registry row says
    # cent_int32 and the PRICE columns are dollars. Everything else is the cent
    # profile, so the refusal must name `bid` and not some earlier column.
    price_mismatch = stock_quote_leaves("cent")
    for index in (3, 7):
        price_mismatch[index].physical = TYPE_DOUBLE
        price_mismatch[index].values = [None if v is NULL else round(v / 100.0, 2)
                                        for v in price_mismatch[index].values]
    write(day_path("sq_dollar_prices"), build_file(price_mismatch, QUOTE_GROUP_SIZES))
    # a descending timestamp inside the RTH window.
    descending = stock_quote_leaves("cent")
    descending[0].values = list(QUOTE_TS)
    descending[0].values[10] = OPEN_MS + 2
    write(day_path("sq_descending"), build_file(descending, QUOTE_GROUP_SIZES))
    # a row that mixes null and non-null NBBO fields.
    partial = stock_quote_leaves("cent")
    partial[3].values = list(partial[3].values)
    partial[3].values[4] = NULL
    write(day_path("sq_partial_null"), build_file(partial, QUOTE_GROUP_SIZES))

    # --- B2 stock trades ---------------------------------------------------
    write(day_path("st_good"), build_file(stock_trade_leaves(), TRADE_GROUP_SIZES))
    write(day_path("st_wrongtype"),
          build_file(stock_trade_leaves(retype=(10, TYPE_INT64)), TRADE_GROUP_SIZES))

    # --- B3 option prints --------------------------------------------------
    write(day_path("op_compact"), build_file(option_print_leaves("compact"), PRINT_GROUP_SIZES))
    write(day_path("op_wide"), build_file(option_print_leaves("wide"), PRINT_GROUP_SIZES))

    # --- B5 RUTW prints ----------------------------------------------------
    # THE TWO-WAY WALL NEEDS THREE TREES, and every one of them is a REAL
    # payload: a wall proven against an empty directory proves nothing.
    #   RUTW/rp_wide        the lawful RUTW corpus — and, to the IWM reader, a
    #                       modality it must refuse even though it would admit
    #                       these bytes' profile;
    #   RUTW/rp_compact     IWM-COMPACT bytes sitting under a RUTW root: the
    #                       RUTW reader must refuse them on the PROFILE pin,
    #                       after the modality pin has already passed;
    #   rp_wide_offroot     the lawful RUTW bytes under a root that names no
    #                       RUTW modality: the RUTW reader must refuse them on
    #                       the MODALITY pin, before a payload path is formed.
    rutw_leaves = rutw_print_leaves()
    write(os.path.join(args.out_dir, "RUTW", "rp_wide", YEAR, f"{DAY}.parquet"),
          build_file(rutw_leaves, RUTW_GROUP_SIZES))
    write(os.path.join(args.out_dir, "RUTW", "rp_compact", YEAR, f"{DAY}.parquet"),
          build_file(option_print_leaves("compact"), PRINT_GROUP_SIZES))
    write(os.path.join(args.out_dir, "rp_wide_offroot", YEAR, f"{DAY}.parquet"),
          build_file(rutw_leaves, RUTW_GROUP_SIZES))
    # The same session with rows 2 and 3 — which share a millisecond — written
    # in the other order.  "Rows unordered within a group" is only a law if a
    # permuted tape produces byte-identical output, so the fixture exists to
    # prove it does.
    write(os.path.join(args.out_dir, "RUTW", "rp_permuted", YEAR, f"{DAY}.parquet"),
          build_file(permute_in_group(rutw_leaves, [(2, 3)]), RUTW_GROUP_SIZES))
    # A RUTW root the session's own day is simply not in: the modality wall
    # passes, and the ABSENCE of the payload must be reported as an absence.
    os.makedirs(os.path.join(args.out_dir, "RUTW", "rp_absent", YEAR), exist_ok=True)

    # --- B4 option quotes --------------------------------------------------
    write(day_path("oq_flat"), build_file(option_quote_leaves("compact"), OQ_GROUP_SIZES))
    sharded_root = os.path.join(args.out_dir, "oq_sharded", YEAR, DAY)
    write(os.path.join(sharded_root, f"exp{EXPIRY_A_TEXT}.parquet"),
          build_file(option_quote_leaves("wide"), OQ_GROUP_SIZES))
    write(os.path.join(sharded_root, f"exp{EXPIRY_B_TEXT}.parquet"),
          build_file(option_quote_leaves("wide"), OQ_GROUP_SIZES))
    # A tree with neither layout, for the MODALITY_ABSENT fixture.
    os.makedirs(os.path.join(args.out_dir, "oq_absent", YEAR), exist_ok=True)

    lines = [
        "# WP4 fixture literals — derived by make_source_fixtures.py, asserted by",
        "# qr_sources/tests/*.cpp. u6 = dollars x 1e6; shares = lots x 100 before",
        "# 2025-11-03.",
        "stream\tkey\tfield\tvalue",
    ]
    lines += quote_literals()
    lines.append(f"stock_quotes_dollar\t*\topen_ms_b\t{DOLLAR_OPEN_MS}")
    lines.append(f"stock_quotes_dollar\t*\tday\t{DOLLAR_DAY}")
    lines += trade_literals()
    lines += print_literals()
    lines += rutw_literals()
    lines += option_quote_literals()
    text = "\n".join(lines) + "\n"
    with open(args.literals_path, "w", encoding="utf-8", newline="\n") as handle:
        handle.write(text)
    print(f"wrote {args.literals_path} ({len(lines)} lines)")
    print()
    print("=== EXPECTED LITERALS (the C++ suite asserts exactly these) ===")
    for line in lines:
        print(line)
    return 0


if __name__ == "__main__":
    sys.exit(main())
